/**
 * Catalog of common film scanners (lab minilab units, flatbeds, dedicated film scanners).
 * Lab-side names are aligned with equipment families called out on Find My Film Lab
 * (e.g. https://findmyfilmlab.com/location/picture-this-film-lab/ — Noritsu HS-1800;
 * browse filters include Noritsu, Frontier, Imacon). Home / prosumer gear includes Epson,
 * Plustek, Nikon Coolscan, Pakon, etc.
 */

export type FilmScannerSeedRow = {
  id: string;
  name: string;
};

export const seedFilmScanners: FilmScannerSeedRow[] = [
  { id: "aztek-digital-drum", name: "Aztek Digital Drum Scanner" },
  { id: "durst-sigma", name: "Durst Sigma Scanner" },
  { id: "epson-expression-11000xl", name: "Epson Expression 11000XL" },
  { id: "epson-expression-12000xl", name: "Epson Expression 12000XL" },
  { id: "epson-perfection-v370", name: "Epson Perfection V370" },
  { id: "epson-perfection-v39", name: "Epson Perfection V39" },
  { id: "epson-perfection-v500", name: "Epson Perfection V500 Photo" },
  { id: "epson-perfection-v550", name: "Epson Perfection V550 Photo" },
  { id: "epson-perfection-v600", name: "Epson Perfection V600 Photo" },
  { id: "epson-perfection-v700", name: "Epson Perfection V700 Photo" },
  { id: "epson-perfection-v750", name: "Epson Perfection V750-M Pro" },
  { id: "epson-perfection-v800", name: "Epson Perfection V800 Photo" },
  { id: "epson-perfection-v850", name: "Epson Perfection V850 Pro" },
  { id: "canon-canoscan-9000f-ii", name: "Canon CanoScan 9000F Mark II" },
  { id: "microtek-scanmaker-i900", name: "Microtek ScanMaker i900" },
  { id: "epson-gt-x980", name: "Epson GT-X980" },
  { id: "fujifilm-frontier-sp-2000", name: "Fujifilm Frontier SP-2000" },
  { id: "fujifilm-frontier-sp-2500", name: "Fujifilm Frontier SP-2500" },
  { id: "fujifilm-frontier-sp-3000", name: "Fujifilm Frontier SP-3000" },
  { id: "fujifilm-frontier-sp-500", name: "Fujifilm Frontier SP-500" },
  { id: "hasselblad-flextight-x1", name: "Hasselblad Flextight X1" },
  { id: "hasselblad-flextight-x5", name: "Hasselblad Flextight X5" },
  { id: "howtek-drum", name: "Howtek Drum Scanner" },
  { id: "imacon-343", name: "Imacon Flextight 343" },
  { id: "imacon-646", name: "Imacon Flextight 646" },
  { id: "imacon-848", name: "Imacon Flextight 848" },
  { id: "imacon-949", name: "Imacon Flextight 949" },
  { id: "kodak-pakon-f135-plus", name: "Kodak Pakon F135 Plus" },
  { id: "kodak-pakon-f335", name: "Kodak Pakon F335" },
  { id: "kodak-qss-minilab", name: "Kodak / Noritsu QSS minilab scanner" },
  { id: "konica-dimage-scan-multi-pro", name: "Konica Minolta DiMAGE Scan Multi Pro" },
  { id: "minolta-dimage-scan-dual-iv", name: "Minolta DiMAGE Scan Dual IV" },
  { id: "minolta-dimage-scan-elite-5400", name: "Minolta DiMAGE Scan Elite 5400" },
  { id: "nikon-coolscan-iv-ed", name: "Nikon Coolscan IV ED (LS-40)" },
  { id: "nikon-coolscan-v-ed", name: "Nikon Coolscan V ED (LS-50)" },
  { id: "nikon-super-coolscan-5000-ed", name: "Nikon Super Coolscan 5000 ED" },
  { id: "nikon-super-coolscan-8000-ed", name: "Nikon Super Coolscan 8000 ED" },
  { id: "nikon-super-coolscan-9000-ed", name: "Nikon Super Coolscan 9000 ED" },
  { id: "noritsu-hs-1100", name: "Noritsu HS-1100" },
  { id: "noritsu-hs-1100-ai", name: "Noritsu HS-1100 AI" },
  { id: "noritsu-hs-1600", name: "Noritsu HS-1600" },
  { id: "noritsu-hs-1800", name: "Noritsu HS-1800" },
  { id: "noritsu-ls-1100", name: "Noritsu LS-1100" },
  { id: "noritsu-ls-600", name: "Noritsu LS-600" },
  { id: "pacific-image-primefilm-xa", name: "Pacific Image PrimeFilm XA" },
  { id: "pacific-image-primefilm-xas", name: "Pacific Image PrimeFilm XAs" },
  { id: "pacific-image-primefilm-xe", name: "Pacific Image PrimeFilm XE" },
  { id: "lasergraphics-scanstation", name: "Lasergraphics ScanStation" },
  { id: "arriscan-xt", name: "ARRISCAN XT" },
  { id: "plustek-opticfilm-120", name: "Plustek OpticFilm 120" },
  { id: "plustek-opticfilm-135", name: "Plustek OpticFilm 135" },
  { id: "plustek-opticfilm-135i", name: "Plustek OpticFilm 135i" },
  { id: "plustek-opticfilm-7400", name: "Plustek OpticFilm 7400" },
  { id: "plustek-opticfilm-7500i", name: "Plustek OpticFilm 7500i" },
  { id: "plustek-opticfilm-8100", name: "Plustek OpticFilm 8100" },
  { id: "plustek-opticfilm-8200i-ai", name: "Plustek OpticFilm 8200i Ai" },
  { id: "plustek-opticfilm-8200i-se", name: "Plustek OpticFilm 8200i SE" },
  { id: "polaroid-sprintscan-120", name: "Polaroid SprintScan 120" },
  { id: "polaroid-sprintscan-4000", name: "Polaroid SprintScan 4000" },
  { id: "reflecta-crystalscan-7200", name: "Reflecta CrystalScan 7200" },
  { id: "reflecta-proscan-7200", name: "Reflecta ProScan 7200" },
  { id: "reflecta-rps-10m", name: "Reflecta RPS 10M" },
  { id: "reflecta-rps-7200", name: "Reflecta RPS 7200" },
  { id: "screen-cezanne", name: "Screen Cezanne" },
  { id: "screen-dtex", name: "Screen DT-S1045Ai" },
  { id: "umax-powerlook-1100", name: "UMAX PowerLook 1100" },
  { id: "virtual-drum-scan", name: "Virtual drum scan (service)" },
  { id: "wolverine-f2d", name: "Wolverine F2D Super" },
  { id: "yongnuo-film-scanner", name: "Yongnuo film digitizer" },
];
