/**
 * Lightweight city normalization hints for share-a-roll metadata.
 * The intent is not strict validation: users can always keep free text.
 */

type CityRecord = {
  city: string;
  country: string;
};

const CURATED_CITY_RECORDS: CityRecord[] = [
  { city: "London", country: "United Kingdom" },
  { city: "Birmingham", country: "United Kingdom" },
  { city: "Manchester", country: "United Kingdom" },
  { city: "Glasgow", country: "United Kingdom" },
  { city: "Liverpool", country: "United Kingdom" },
  { city: "Leeds", country: "United Kingdom" },
  { city: "Edinburgh", country: "United Kingdom" },
  { city: "Bristol", country: "United Kingdom" },
  { city: "Cardiff", country: "United Kingdom" },
  { city: "Belfast", country: "United Kingdom" },
  { city: "Dublin", country: "Ireland" },
  { city: "Cork", country: "Ireland" },
  { city: "Galway", country: "Ireland" },
  { city: "Limerick", country: "Ireland" },
  { city: "Paris", country: "France" },
  { city: "Marseille", country: "France" },
  { city: "Lyon", country: "France" },
  { city: "Toulouse", country: "France" },
  { city: "Nice", country: "France" },
  { city: "Nantes", country: "France" },
  { city: "Bordeaux", country: "France" },
  { city: "Lille", country: "France" },
  { city: "Montpellier", country: "France" },
  { city: "Strasbourg", country: "France" },
  { city: "Berlin", country: "Germany" },
  { city: "Hamburg", country: "Germany" },
  { city: "Munich", country: "Germany" },
  { city: "Cologne", country: "Germany" },
  { city: "Frankfurt", country: "Germany" },
  { city: "Stuttgart", country: "Germany" },
  { city: "Dusseldorf", country: "Germany" },
  { city: "Leipzig", country: "Germany" },
  { city: "Dortmund", country: "Germany" },
  { city: "Essen", country: "Germany" },
  { city: "Madrid", country: "Spain" },
  { city: "Barcelona", country: "Spain" },
  { city: "Valencia", country: "Spain" },
  { city: "Seville", country: "Spain" },
  { city: "Zaragoza", country: "Spain" },
  { city: "Malaga", country: "Spain" },
  { city: "Murcia", country: "Spain" },
  { city: "Palma", country: "Spain" },
  { city: "Bilbao", country: "Spain" },
  { city: "Alicante", country: "Spain" },
  { city: "Rome", country: "Italy" },
  { city: "Milan", country: "Italy" },
  { city: "Naples", country: "Italy" },
  { city: "Turin", country: "Italy" },
  { city: "Palermo", country: "Italy" },
  { city: "Genoa", country: "Italy" },
  { city: "Bologna", country: "Italy" },
  { city: "Florence", country: "Italy" },
  { city: "Bari", country: "Italy" },
  { city: "Catania", country: "Italy" },
  { city: "Lisbon", country: "Portugal" },
  { city: "Porto", country: "Portugal" },
  { city: "Braga", country: "Portugal" },
  { city: "Coimbra", country: "Portugal" },
  { city: "Amsterdam", country: "Netherlands" },
  { city: "Rotterdam", country: "Netherlands" },
  { city: "The Hague", country: "Netherlands" },
  { city: "Utrecht", country: "Netherlands" },
  { city: "Eindhoven", country: "Netherlands" },
  { city: "Brussels", country: "Belgium" },
  { city: "Antwerp", country: "Belgium" },
  { city: "Ghent", country: "Belgium" },
  { city: "Bruges", country: "Belgium" },
  { city: "Vienna", country: "Austria" },
  { city: "Salzburg", country: "Austria" },
  { city: "Graz", country: "Austria" },
  { city: "Linz", country: "Austria" },
  { city: "Zurich", country: "Switzerland" },
  { city: "Geneva", country: "Switzerland" },
  { city: "Basel", country: "Switzerland" },
  { city: "Bern", country: "Switzerland" },
  { city: "Lausanne", country: "Switzerland" },
  { city: "Copenhagen", country: "Denmark" },
  { city: "Aarhus", country: "Denmark" },
  { city: "Odense", country: "Denmark" },
  { city: "Stockholm", country: "Sweden" },
  { city: "Gothenburg", country: "Sweden" },
  { city: "Malmo", country: "Sweden" },
  { city: "Uppsala", country: "Sweden" },
  { city: "Oslo", country: "Norway" },
  { city: "Bergen", country: "Norway" },
  { city: "Trondheim", country: "Norway" },
  { city: "Helsinki", country: "Finland" },
  { city: "Espoo", country: "Finland" },
  { city: "Tampere", country: "Finland" },
  { city: "Reykjavik", country: "Iceland" },
  { city: "Prague", country: "Czechia" },
  { city: "Brno", country: "Czechia" },
  { city: "Warsaw", country: "Poland" },
  { city: "Krakow", country: "Poland" },
  { city: "Lodz", country: "Poland" },
  { city: "Wroclaw", country: "Poland" },
  { city: "Poznan", country: "Poland" },
  { city: "Gdansk", country: "Poland" },
  { city: "Budapest", country: "Hungary" },
  { city: "Szeged", country: "Hungary" },
  { city: "Debrecen", country: "Hungary" },
  { city: "Bucharest", country: "Romania" },
  { city: "Cluj-Napoca", country: "Romania" },
  { city: "Timisoara", country: "Romania" },
  { city: "Sofia", country: "Bulgaria" },
  { city: "Plovdiv", country: "Bulgaria" },
  { city: "Athens", country: "Greece" },
  { city: "Thessaloniki", country: "Greece" },
  { city: "Heraklion", country: "Greece" },
  { city: "Istanbul", country: "Turkey" },
  { city: "Ankara", country: "Turkey" },
  { city: "Izmir", country: "Turkey" },
  { city: "Bursa", country: "Turkey" },
  { city: "Antalya", country: "Turkey" },
  { city: "Moscow", country: "Russia" },
  { city: "Saint Petersburg", country: "Russia" },
  { city: "Kazan", country: "Russia" },
  { city: "Yekaterinburg", country: "Russia" },
  { city: "Novosibirsk", country: "Russia" },
  { city: "Kyiv", country: "Ukraine" },
  { city: "Kharkiv", country: "Ukraine" },
  { city: "Odesa", country: "Ukraine" },
  { city: "Minsk", country: "Belarus" },
  { city: "Riga", country: "Latvia" },
  { city: "Vilnius", country: "Lithuania" },
  { city: "Tallinn", country: "Estonia" },
  { city: "Belgrade", country: "Serbia" },
  { city: "Zagreb", country: "Croatia" },
  { city: "Ljubljana", country: "Slovenia" },
  { city: "Sarajevo", country: "Bosnia and Herzegovina" },
  { city: "Skopje", country: "North Macedonia" },
  { city: "Podgorica", country: "Montenegro" },
  { city: "Tirana", country: "Albania" },
  { city: "New York", country: "United States" },
  { city: "Los Angeles", country: "United States" },
  { city: "Chicago", country: "United States" },
  { city: "Houston", country: "United States" },
  { city: "Phoenix", country: "United States" },
  { city: "Philadelphia", country: "United States" },
  { city: "San Antonio", country: "United States" },
  { city: "San Diego", country: "United States" },
  { city: "Dallas", country: "United States" },
  { city: "San Jose", country: "United States" },
  { city: "Austin", country: "United States" },
  { city: "Jacksonville", country: "United States" },
  { city: "San Francisco", country: "United States" },
  { city: "Seattle", country: "United States" },
  { city: "Denver", country: "United States" },
  { city: "Boston", country: "United States" },
  { city: "Atlanta", country: "United States" },
  { city: "Miami", country: "United States" },
  { city: "Portland", country: "United States" },
  { city: "Las Vegas", country: "United States" },
  { city: "Toronto", country: "Canada" },
  { city: "Montreal", country: "Canada" },
  { city: "Vancouver", country: "Canada" },
  { city: "Calgary", country: "Canada" },
  { city: "Edmonton", country: "Canada" },
  { city: "Ottawa", country: "Canada" },
  { city: "Winnipeg", country: "Canada" },
  { city: "Quebec City", country: "Canada" },
  { city: "Mexico City", country: "Mexico" },
  { city: "Guadalajara", country: "Mexico" },
  { city: "Monterrey", country: "Mexico" },
  { city: "Puebla", country: "Mexico" },
  { city: "Tijuana", country: "Mexico" },
  { city: "Bogota", country: "Colombia" },
  { city: "Medellin", country: "Colombia" },
  { city: "Cali", country: "Colombia" },
  { city: "Cartagena", country: "Colombia" },
  { city: "Lima", country: "Peru" },
  { city: "Arequipa", country: "Peru" },
  { city: "Cusco", country: "Peru" },
  { city: "Santiago", country: "Chile" },
  { city: "Valparaiso", country: "Chile" },
  { city: "Buenos Aires", country: "Argentina" },
  { city: "Cordoba", country: "Argentina" },
  { city: "Rosario", country: "Argentina" },
  { city: "Mendoza", country: "Argentina" },
  { city: "Sao Paulo", country: "Brazil" },
  { city: "Rio de Janeiro", country: "Brazil" },
  { city: "Brasilia", country: "Brazil" },
  { city: "Salvador", country: "Brazil" },
  { city: "Fortaleza", country: "Brazil" },
  { city: "Belo Horizonte", country: "Brazil" },
  { city: "Curitiba", country: "Brazil" },
  { city: "Recife", country: "Brazil" },
  { city: "Porto Alegre", country: "Brazil" },
  { city: "Belem", country: "Brazil" },
  { city: "Quito", country: "Ecuador" },
  { city: "Guayaquil", country: "Ecuador" },
  { city: "Caracas", country: "Venezuela" },
  { city: "Montevideo", country: "Uruguay" },
  { city: "Asuncion", country: "Paraguay" },
  { city: "La Paz", country: "Bolivia" },
  { city: "Santa Cruz", country: "Bolivia" },
  { city: "Cape Town", country: "South Africa" },
  { city: "Johannesburg", country: "South Africa" },
  { city: "Pretoria", country: "South Africa" },
  { city: "Durban", country: "South Africa" },
  { city: "Nairobi", country: "Kenya" },
  { city: "Mombasa", country: "Kenya" },
  { city: "Addis Ababa", country: "Ethiopia" },
  { city: "Accra", country: "Ghana" },
  { city: "Lagos", country: "Nigeria" },
  { city: "Abuja", country: "Nigeria" },
  { city: "Kano", country: "Nigeria" },
  { city: "Ibadan", country: "Nigeria" },
  { city: "Cairo", country: "Egypt" },
  { city: "Alexandria", country: "Egypt" },
  { city: "Casablanca", country: "Morocco" },
  { city: "Rabat", country: "Morocco" },
  { city: "Marrakesh", country: "Morocco" },
  { city: "Algiers", country: "Algeria" },
  { city: "Tunis", country: "Tunisia" },
  { city: "Dakar", country: "Senegal" },
  { city: "Kampala", country: "Uganda" },
  { city: "Kigali", country: "Rwanda" },
  { city: "Dar es Salaam", country: "Tanzania" },
  { city: "Zanzibar", country: "Tanzania" },
  { city: "Harare", country: "Zimbabwe" },
  { city: "Lusaka", country: "Zambia" },
  { city: "Luanda", country: "Angola" },
  { city: "Dubai", country: "United Arab Emirates" },
  { city: "Abu Dhabi", country: "United Arab Emirates" },
  { city: "Doha", country: "Qatar" },
  { city: "Riyadh", country: "Saudi Arabia" },
  { city: "Jeddah", country: "Saudi Arabia" },
  { city: "Mecca", country: "Saudi Arabia" },
  { city: "Medina", country: "Saudi Arabia" },
  { city: "Muscat", country: "Oman" },
  { city: "Kuwait City", country: "Kuwait" },
  { city: "Manama", country: "Bahrain" },
  { city: "Amman", country: "Jordan" },
  { city: "Jerusalem", country: "Israel" },
  { city: "Tel Aviv", country: "Israel" },
  { city: "Beirut", country: "Lebanon" },
  { city: "Baghdad", country: "Iraq" },
  { city: "Tehran", country: "Iran" },
  { city: "Shiraz", country: "Iran" },
  { city: "Isfahan", country: "Iran" },
  { city: "Karachi", country: "Pakistan" },
  { city: "Lahore", country: "Pakistan" },
  { city: "Islamabad", country: "Pakistan" },
  { city: "Dhaka", country: "Bangladesh" },
  { city: "Chittagong", country: "Bangladesh" },
  { city: "Kathmandu", country: "Nepal" },
  { city: "Colombo", country: "Sri Lanka" },
  { city: "Male", country: "Maldives" },
  { city: "New Delhi", country: "India" },
  { city: "Mumbai", country: "India" },
  { city: "Bengaluru", country: "India" },
  { city: "Hyderabad", country: "India" },
  { city: "Chennai", country: "India" },
  { city: "Kolkata", country: "India" },
  { city: "Pune", country: "India" },
  { city: "Ahmedabad", country: "India" },
  { city: "Jaipur", country: "India" },
  { city: "Goa", country: "India" },
  { city: "Beijing", country: "China" },
  { city: "Shanghai", country: "China" },
  { city: "Shenzhen", country: "China" },
  { city: "Guangzhou", country: "China" },
  { city: "Chengdu", country: "China" },
  { city: "Chongqing", country: "China" },
  { city: "Wuhan", country: "China" },
  { city: "Hangzhou", country: "China" },
  { city: "Nanjing", country: "China" },
  { city: "Tianjin", country: "China" },
  { city: "Hong Kong", country: "Hong Kong" },
  { city: "Macau", country: "Macau" },
  { city: "Taipei", country: "Taiwan" },
  { city: "Kaohsiung", country: "Taiwan" },
  { city: "Tokyo", country: "Japan" },
  { city: "Osaka", country: "Japan" },
  { city: "Kyoto", country: "Japan" },
  { city: "Yokohama", country: "Japan" },
  { city: "Nagoya", country: "Japan" },
  { city: "Sapporo", country: "Japan" },
  { city: "Fukuoka", country: "Japan" },
  { city: "Hiroshima", country: "Japan" },
  { city: "Sendai", country: "Japan" },
  { city: "Seoul", country: "South Korea" },
  { city: "Busan", country: "South Korea" },
  { city: "Incheon", country: "South Korea" },
  { city: "Daegu", country: "South Korea" },
  { city: "Bangkok", country: "Thailand" },
  { city: "Chiang Mai", country: "Thailand" },
  { city: "Phuket", country: "Thailand" },
  { city: "Hanoi", country: "Vietnam" },
  { city: "Ho Chi Minh City", country: "Vietnam" },
  { city: "Da Nang", country: "Vietnam" },
  { city: "Kuala Lumpur", country: "Malaysia" },
  { city: "George Town", country: "Malaysia" },
  { city: "Johor Bahru", country: "Malaysia" },
  { city: "Singapore", country: "Singapore" },
  { city: "Jakarta", country: "Indonesia" },
  { city: "Bali", country: "Indonesia" },
  { city: "Surabaya", country: "Indonesia" },
  { city: "Bandung", country: "Indonesia" },
  { city: "Manila", country: "Philippines" },
  { city: "Cebu", country: "Philippines" },
  { city: "Davao", country: "Philippines" },
  { city: "Phnom Penh", country: "Cambodia" },
  { city: "Siem Reap", country: "Cambodia" },
  { city: "Vientiane", country: "Laos" },
  { city: "Yangon", country: "Myanmar" },
  { city: "Naypyidaw", country: "Myanmar" },
  { city: "Brunei", country: "Brunei" },
  { city: "Ulaanbaatar", country: "Mongolia" },
  { city: "Sydney", country: "Australia" },
  { city: "Melbourne", country: "Australia" },
  { city: "Brisbane", country: "Australia" },
  { city: "Perth", country: "Australia" },
  { city: "Adelaide", country: "Australia" },
  { city: "Canberra", country: "Australia" },
  { city: "Gold Coast", country: "Australia" },
  { city: "Hobart", country: "Australia" },
  { city: "Auckland", country: "New Zealand" },
  { city: "Wellington", country: "New Zealand" },
  { city: "Christchurch", country: "New Zealand" },
  { city: "Queenstown", country: "New Zealand" },
];

type CuratedCity = {
  cityKey: string;
  city: string;
  country: string;
  label: string;
};

function normalizeToken(value: string): string {
  return value
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

const CURATED_CITIES: CuratedCity[] = CURATED_CITY_RECORDS.map((r) => ({
  cityKey: normalizeToken(r.city),
  city: r.city,
  country: r.country,
  label: `${r.city}, ${r.country}`,
}));

export function suggestNormalizedLocations(input: string, limit = 3): string[] {
  const normalizedInput = normalizeToken(input);
  if (normalizedInput.length < 2) return [];

  const commaIdx = normalizedInput.indexOf(" ");
  const firstToken = commaIdx > 0 ? normalizedInput.slice(0, commaIdx) : normalizedInput;

  const exact = CURATED_CITIES.filter((c) => c.cityKey === normalizedInput || c.cityKey === firstToken);
  const startsWith = CURATED_CITIES.filter(
    (c) =>
      c.cityKey.startsWith(normalizedInput) ||
      c.cityKey.startsWith(firstToken)
  );
  const contains = CURATED_CITIES.filter(
    (c) =>
      c.cityKey.includes(normalizedInput) ||
      c.cityKey.includes(firstToken)
  );

  const ordered = [...exact, ...startsWith, ...contains];
  const deduped: string[] = [];
  for (const item of ordered) {
    if (!deduped.includes(item.label)) deduped.push(item.label);
    if (deduped.length >= limit) break;
  }
  return deduped;
}

