import type { FilmBrand, FilmStock, ShootingNote } from "@/lib/types";
import {
  scaleToContrastFilter,
  scaleToGrainFilter,
  scaleToLatitudeFilter,
  scaleToSaturationFilter,
} from "@/lib/types";

const nowIso = new Date().toISOString();

function notes(entries: Array<[string, string]>): ShootingNote[] {
  return entries.map(([header, dek]) => ({ header, dek }));
}

function buildStock(
  stock: Omit<
    FilmStock,
    "created_at" | "updated_at" | "grain_level" | "contrast_level" | "latitude_level" | "saturation_filter"
  >
): FilmStock {
  return {
    ...stock,
    grain_level: scaleToGrainFilter(stock.grain) ?? "medium",
    contrast_level: scaleToContrastFilter(stock.contrast) ?? "balanced",
    latitude_level: scaleToLatitudeFilter(stock.latitude),
    saturation_filter: scaleToSaturationFilter(stock.saturation),
    created_at: nowIso,
    updated_at: nowIso,
  };
}

const currentColorNotes = {
  generalPurpose: notes([
    ["Skin Tones", "Clean and dependable. It keeps faces believable and avoids the exaggerated warmth or coolness that makes all-purpose stocks harder to place."],
    ["Color Bias", "Balanced with a house look. The palette has a recognizable signature, but it stays flexible enough for day-to-day shooting."],
    ["Push/Pull", "Usable within reason. It prefers box speed or a little extra light, while bigger rating changes trade away subtlety for speed."],
    ["Shadow Detail", "Good everyday retention. It keeps enough information in darker areas for mixed light and casual metering, but it still rewards generous exposure."],
    ["Highlight Roll-off", "Controlled and easy to scan. Bright areas stay smoother than slide film and keep the stock feeling practical rather than precious."],
  ]),
  slideBalanced: notes([
    ["Skin Tones", "Clean but exacting. Faces can look excellent, though slide-film exposure discipline matters far more than with negative stock."],
    ["Color Bias", "Neutral to gently vivid. The palette stays polished and crisp without pushing every hue toward maximum drama."],
    ["Push/Pull", "Moderately adaptable for E-6. A careful push can work, but the film is best when exposure is deliberate and processing stays predictable."],
    ["Shadow Detail", "Tighter than negative film. Dark areas need care, though the stock holds together better than the most contrasty slide emulsions."],
    ["Highlight Roll-off", "Precise rather than forgiving. Highlights reward careful metering and good scene control, especially in bright sun."],
  ]),
};

const sharedHistories = {
  ferraniaSolaris:
    "The Solaris line was Ferrania's mass-market color family through the late 1990s and 2000s, widely sold under Ferrania, store-brand, and rebadged packaging. It helped keep Italian-made consumer color film visible in supermarkets and camera shops long after premium slide film had become a niche.",
  kodachrome:
    "Kodachrome defined the premium slide-film ideal for decades, combining very fine grain with a distinctive archival palette and the famously complex K-14 process. Each speed had its own following, but all three variants became touchstones for editorial, travel, and documentary color before the line finally disappeared.",
  vision3:
    "Kodak's Vision3 family was developed for modern motion-picture production, with improved highlight handling, cleaner shadows, and scanning latitude compared with older cinema stocks. Still photographers usually encounter it as respooled stock, where its ECN-2 roots and remjet layer are part of the appeal.",
  luckyBw:
    "Lucky's SHD black-and-white films descend from the Chinese manufacturer's long-running domestic emulsions, which earned a reputation for affordability and practical performance. Recent availability has introduced the films to a wider audience looking for budget-friendly monochrome with a classic, unfussy look.",
  lomochrome92:
    "Lomography introduced Color '92 as a modern color negative stock designed to echo the softer consumer-film palette of the early 1990s. It expanded the company's in-house creative color line beyond effect films into a deliberately nostalgic everyday aesthetic.",
};

export const additionalFilmBrands: FilmBrand[] = [
  {
    id: "brand-lucky",
    name: "Lucky",
    slug: "lucky",
    logo_url: null,
    description:
      "Lucky Film is a long-running Chinese photographic manufacturer with roots in state-backed industrial film production. The brand became internationally known for affordable black-and-white films and has recently re-entered the color market, making it one of the few companies reviving rather than shrinking a film lineup.",
    website_url: "https://luckyfilm.net/",
    featured: null,
    created_at: nowIso,
    updated_at: nowIso,
  },
];

export const additionalFilmStocks: FilmStock[] = [
  buildStock({
    id: "stock-adox-chs-25-ii",
    name: "ADOX CHS 25 II",
    slug: "adox-chs-25-ii",
    brand_id: "brand-adox",
    format: ["35mm", "120", "4x5", "8x10"],
    type: "bw_negative",
    iso: 25,
    description:
      "An ultra-slow black-and-white film built for photographers who want classic tonality with maximum resolving power. CHS 25 II favors deliberate daylight work, large prints, and scenes where a calm tonal curve matters more than speed.",
    history:
      "ADOX revived the CHS line as a modern continuation of one of the oldest film names in photography. CHS 25 II extends that project into the slow-speed end of the range, pairing vintage-style rendering with contemporary coating quality.",
    shooting_notes: notes([
      ["Tonal Range", "Classic and gently rounded. It has a vintage-style grayscale with smooth mids instead of a technical or clinical feel."],
      ["Push/Pull", "Built for careful exposure. It is happiest at box speed or with a little extra light rather than any attempt to chase speed."],
      ["Shadow Detail", "Strong when exposed generously. Low values stay elegant and readable, but this is not a film that rescues rushed metering."],
      ["Highlight Roll-off", "Graceful and refined. Bright tones taper smoothly, which suits architecture, portraiture, and sunlit landscapes."],
    ]),
    grain: 1,
    contrast: 2,
    latitude: 3,
    saturation: null,
    color_balance: "Orthopanchromatic-style monochrome with a classic silver scale",
    color_balance_type: null,
    color_balance_kelvin: null,
    dx_coding: true,
    development_process: "bw",
    best_for: ["landscapes", "architecture", "studio", "bright_sun"],
    discontinued: false,
    price_tier: 2,
    base_price_usd: 11,
    image_url: "/films/adox-chs-25-ii.jpg",
    year_introduced: 2025,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-adox-scala-50",
    name: "ADOX SCALA 50",
    slug: "adox-scala-50",
    brand_id: "brand-adox",
    format: ["35mm"],
    type: "bw_reversal",
    iso: 50,
    description:
      "A modern black-and-white reversal film made for projection, direct positives, and a uniquely luminous monochrome slide look. SCALA 50 is slow, sharp, and exacting in the way only black-and-white transparency film can be.",
    history:
      "After Agfa's original SCALA disappeared, ADOX revived the concept for photographers who still wanted true black-and-white slides. SCALA 50 became the low-speed, high-precision option in that revival.",
    shooting_notes: notes([
      ["Tonal Range", "Bright and tightly controlled. It has the snap and clarity of monochrome transparency rather than the long cushion of negative film."],
      ["Push/Pull", "Best at box. Reversal processing leaves little room for casual rating changes, so it rewards disciplined metering more than experimentation."],
      ["Shadow Detail", "Narrow and exposure dependent. Dark tones fall away quickly if the film is starved for light."],
      ["Highlight Roll-off", "Brisk but luminous. Highlights stay beautiful when placed carefully, but overexposure shows up immediately."],
    ]),
    grain: 1,
    contrast: 4,
    latitude: 1,
    saturation: null,
    color_balance: "Black-and-white reversal transparency rendering",
    color_balance_type: null,
    color_balance_kelvin: null,
    dx_coding: true,
    development_process: "bw",
    best_for: ["architecture", "studio", "bright_sun", "experimental"],
    discontinued: false,
    price_tier: 2,
    base_price_usd: 10,
    image_url: "/films/adox-scala-50.jpg",
    year_introduced: 2019,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-adox-scala-160",
    name: "ADOX SCALA 160",
    slug: "adox-scala-160",
    brand_id: "brand-adox",
    format: ["35mm"],
    type: "bw_reversal",
    iso: 160,
    description:
      "The faster member of the ADOX reversal pair, SCALA 160 trades a little refinement for much more practical handheld speed. It keeps the direct, projected look of monochrome slides while making real-world shooting easier.",
    history:
      "ADOX reintroduced SCALA 160 in the mid-2010s as a contemporary answer to photographers who missed Agfa's historic reversal line. It remains one of the few readily available black-and-white reversal options for still photographers.",
    shooting_notes: notes([
      ["Tonal Range", "Direct and contrasty. It has more bite than slow monochrome negatives and carries the immediate transparency look well."],
      ["Push/Pull", "Limited but serviceable. Small rating changes are possible, though the film's real strength is dependable reversal performance at its intended speed."],
      ["Shadow Detail", "Moderate for reversal film. It handles everyday scenes better than slower slide emulsions, but shadows still need respect."],
      ["Highlight Roll-off", "Clean and fairly abrupt. Highlights look crisp and luminous when exposure is right, without the softness of negative film."],
    ]),
    grain: 2,
    contrast: 4,
    latitude: 2,
    saturation: null,
    color_balance: "Black-and-white reversal transparency rendering",
    color_balance_type: null,
    color_balance_kelvin: null,
    dx_coding: true,
    development_process: "bw",
    best_for: ["street", "documentary", "bright_sun", "experimental"],
    discontinued: false,
    price_tier: 2,
    base_price_usd: 10,
    image_url: "/films/adox-scala-160.jpg",
    year_introduced: 2016,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-agfa-apx-25",
    name: "Agfa APX 25",
    slug: "agfa-apx-25",
    brand_id: "brand-agfa",
    format: ["35mm", "120"],
    type: "bw_negative",
    iso: 25,
    description:
      "A discontinued ultra-fine-grain Agfa stock that paired very high sharpness with a restrained, elegant monochrome curve. APX 25 became a favorite for tripod work, architecture, and bright outdoor scenes where detail mattered most.",
    history:
      "APX 25 sat at the precision end of Agfa's black-and-white lineup during the 1990s and early 2000s. It disappeared as the analog market contracted, but it remains one of the better-remembered slow conventional films of its era.",
    shooting_notes: notes([
      ["Tonal Range", "Clean and classic. It gives a refined grayscale with less romantic softness than older emulsions and more warmth than technical microfilm."],
      ["Push/Pull", "Not a speed-seeking stock. It rewards box speed and careful development much more than any kind of push workflow."],
      ["Shadow Detail", "Strong if the negative gets enough exposure. Shadows stay tidy and well separated in bright conditions."],
      ["Highlight Roll-off", "Measured and polished. Highlights stay orderly, which helped make the film attractive for architectural and scenic work."],
    ]),
    grain: 1,
    contrast: 3,
    latitude: 3,
    saturation: null,
    color_balance: "Neutral silver rendering with strong detail separation",
    color_balance_type: null,
    color_balance_kelvin: null,
    dx_coding: true,
    development_process: "bw",
    best_for: ["landscapes", "architecture", "studio", "bright_sun"],
    discontinued: true,
    price_tier: null,
    base_price_usd: null,
    image_url: "/films/agfa-apx-25.jpg",
    year_introduced: 1992,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-agfa-scala-200x",
    name: "Agfa Scala 200x",
    slug: "agfa-scala-200x",
    brand_id: "brand-agfa",
    format: ["35mm", "120"],
    type: "bw_reversal",
    iso: 200,
    description:
      "One of the defining black-and-white reversal films of the late analog era. Scala 200x delivered projection-ready monochrome slides with a dramatic, editorial look that no ordinary negative could quite match.",
    history:
      "Agfa introduced Scala 200x as the flagship of its monochrome reversal system, complete with dedicated lab processing and projection culture around the film. Its discontinuation turned it into a reference point for every later black-and-white reversal revival.",
    shooting_notes: notes([
      ["Tonal Range", "Bold and transparent. It has the immediate, contrast-forward look that made monochrome slides feel so different from prints."],
      ["Push/Pull", "Designed for process control, not casual flexibility. Metering accuracy matters more than rating tricks."],
      ["Shadow Detail", "Relatively tight. Deep tones close quickly if exposure drifts, especially in contrasty daylight."],
      ["Highlight Roll-off", "Brilliant but unforgiving. Bright values glow beautifully when placed well, but there is little recovery margin."],
    ]),
    grain: 2,
    contrast: 5,
    latitude: 1,
    saturation: null,
    color_balance: "Black-and-white reversal transparency rendering",
    color_balance_type: null,
    color_balance_kelvin: null,
    dx_coding: true,
    development_process: "bw",
    best_for: ["architecture", "documentary", "bright_sun", "experimental"],
    discontinued: true,
    price_tier: null,
    base_price_usd: null,
    image_url: "/films/agfa-scala-200x.jpg",
    year_introduced: 1996,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-agfa-vista-plus-100",
    name: "AgfaPhoto Vista Plus 100",
    slug: "agfa-vista-plus-100",
    brand_id: "brand-agfa",
    format: ["35mm"],
    type: "color_negative",
    iso: 100,
    description:
      "A daylight consumer color film with warm reds, lively greens, and the easy, holiday-snapshot character many photographers associate with late AgfaPhoto packaging. Vista Plus 100 feels simple and sunny rather than clinical or premium.",
    history:
      "After Agfa's collapse, the AgfaPhoto name lived on through licensed consumer films sourced from other manufacturers. Vista Plus 100 became one of the more recognizable entries in that era, often associated with Ferrania-made color stock.",
    shooting_notes: notes([
      ["Skin Tones", "Warm and casual. Faces lean sunny rather than neutral, which suits family, travel, and golden-hour work."],
      ["Color Bias", "Consumer warmth with a touch of punch. Reds and greens feel cheerful without turning fully candy-colored."],
      ["Push/Pull", "Best with light to spare. It rewards box speed or mild overexposure more than any attempt to squeeze extra speed from it."],
      ["Shadow Detail", "Moderate. Shadows hold together in normal daylight, but underexposure quickly flattens the image."],
      ["Highlight Roll-off", "Pleasant and forgiving. Bright skies and light clothing stay easier to manage than on slide film."],
    ]),
    grain: 2,
    contrast: 3,
    latitude: 4,
    saturation: 3,
    color_balance: "Daylight-balanced with a warm consumer palette",
    color_balance_type: "daylight",
    color_balance_kelvin: 5500,
    dx_coding: true,
    development_process: "c41",
    best_for: ["general_purpose", "travel", "golden_hour", "bright_sun"],
    discontinued: true,
    price_tier: null,
    base_price_usd: null,
    image_url: "/films/agfa-vista-plus-100.jpg",
    year_introduced: 2005,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-agfa-vista-plus-400",
    name: "AgfaPhoto Vista Plus 400",
    slug: "agfa-vista-plus-400",
    brand_id: "brand-agfa",
    format: ["35mm"],
    type: "color_negative",
    iso: 400,
    description:
      "The faster Vista option, known for bold reds, visible grain, and a punchy daylight look that sits between family-snapshot film and travel stock. It feels a little louder and rougher than the 100-speed version in a good way.",
    history: sharedHistories.ferraniaSolaris,
    shooting_notes: notes([
      ["Skin Tones", "Lively and warm. It gives portraits a cheerful consumer-film glow rather than a restrained pro look."],
      ["Color Bias", "Punchier than the slower Vista stocks. Reds and greens come forward quickly, especially in bright sun."],
      ["Push/Pull", "Decent for a consumer 400 film. It tolerates a one-stop push in a pinch, though grain and contrast rise quickly."],
      ["Shadow Detail", "Good in ordinary scenes. There is enough negative-film cushion for street and travel use, but not a huge safety net."],
      ["Highlight Roll-off", "Friendly and printable. Highlights stay smoother than the film's saturated palette might suggest."],
    ]),
    grain: 3,
    contrast: 4,
    latitude: 4,
    saturation: 4,
    color_balance: "Daylight-balanced with warm, saturated consumer color",
    color_balance_type: "daylight",
    color_balance_kelvin: 5500,
    dx_coding: true,
    development_process: "c41",
    best_for: ["general_purpose", "travel", "street", "golden_hour"],
    discontinued: true,
    price_tier: null,
    base_price_usd: null,
    image_url: "/films/agfa-vista-plus-400.jpg",
    year_introduced: 2005,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-ferrania-ortho",
    name: "Ferrania Orto",
    slug: "ferrania-ortho",
    brand_id: "brand-ferrania",
    format: ["35mm"],
    type: "bw_negative",
    iso: 50,
    description:
      "A modern orthographic black-and-white film with crisp contrast, smooth grain, and a distinctive response to reds and skin. Orto 50 brings specialist spectral behavior into everyday still photography without feeling like a mere novelty.",
    history:
      "Film Ferrania released Orto 50 in 2023 as the second still film from its revived Italian factory. It broadened the company's lineup beyond P30 and showed that Ferrania's restart could support more than one monochrome character.",
    shooting_notes: notes([
      ["Tonal Range", "Graphic and selective. Reds go dark, blues and greens separate cleanly, and the image feels sculpted rather than neutral."],
      ["Push/Pull", "Built for box-speed control. It is a specialty 50-speed film, so careful exposure matters more than flexibility."],
      ["Shadow Detail", "Moderate but attractive. Dark values stay readable with enough light, though this is not a wide-latitude emulsion."],
      ["Highlight Roll-off", "Bright and tidy. Highlights stay crisp without the brittle feel of some technical films."],
    ]),
    grain: 1,
    contrast: 4,
    latitude: 3,
    saturation: null,
    color_balance: "Orthochromatic monochrome with darkened reds and crisp separation",
    color_balance_type: null,
    color_balance_kelvin: null,
    dx_coding: true,
    development_process: "bw",
    best_for: ["architecture", "studio", "bright_sun", "experimental"],
    discontinued: false,
    price_tier: 2,
    base_price_usd: 14,
    image_url: "/films/ferrania-ortho.jpg",
    year_introduced: 2023,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-ferrania-solaris-fg-plus-100",
    name: "Ferrania Solaris FG Plus 100",
    slug: "ferrania-solaris-fg-plus-100",
    brand_id: "brand-ferrania",
    format: ["35mm"],
    type: "color_negative",
    iso: 100,
    description:
      "A bright-light consumer color film from Ferrania's supermarket era, remembered for warm color and straightforward holiday-film charm. FG Plus 100 is less about perfection than about an easy, cheerful daylight look.",
    history: sharedHistories.ferraniaSolaris,
    shooting_notes: notes([
      ["Skin Tones", "Warm and approachable. Portraits feel casual and friendly rather than polished or fashion-forward."],
      ["Color Bias", "Sunny and slightly nostalgic. Warm tones and simple color separation define the stock more than extreme saturation."],
      ["Push/Pull", "Best near box speed. It is a daylight consumer film that rewards plenty of light more than processing acrobatics."],
      ["Shadow Detail", "Modest but usable. It handles ordinary bright scenes well, though thin exposure makes shadows collapse quickly."],
      ["Highlight Roll-off", "Easygoing for consumer film. Highlights stay pleasant and help the stock keep its family-photo feel."],
    ]),
    grain: 2,
    contrast: 3,
    latitude: 3,
    saturation: 3,
    color_balance: "Daylight-balanced with a warm, nostalgic consumer palette",
    color_balance_type: "daylight",
    color_balance_kelvin: 5500,
    dx_coding: true,
    development_process: "c41",
    best_for: ["general_purpose", "travel", "bright_sun", "golden_hour"],
    discontinued: true,
    price_tier: null,
    base_price_usd: null,
    image_url: "/films/ferrania-solaris-fg-plus-100.jpg",
    year_introduced: 1999,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-ferrania-solaris-fg-plus-200",
    name: "Ferrania Solaris FG Plus 200",
    slug: "ferrania-solaris-fg-plus-200",
    brand_id: "brand-ferrania",
    format: ["35mm"],
    type: "color_negative",
    iso: 200,
    description:
      "Probably the best-known Solaris speed, FG Plus 200 sits in the sweet spot between daylight crispness and forgiving consumer negative latitude. It carries the same warm Ferrania character with a bit more versatility than the 100-speed version.",
    history: sharedHistories.ferraniaSolaris,
    shooting_notes: notes([
      ["Skin Tones", "Healthy and warm. It gives faces a cheerful snapshot look with enough softness to stay flattering."],
      ["Color Bias", "Warm and lightly punchy. The palette feels nostalgic without becoming overly stylized."],
      ["Push/Pull", "Flexible within consumer limits. It likes slight overexposure best, while pushes make the stock rougher rather than more sophisticated."],
      ["Shadow Detail", "Better than the slower Solaris stock. There is enough cushion for travel and street scenes in mixed daylight."],
      ["Highlight Roll-off", "Smooth enough to be forgiving. Bright areas stay manageable, which helps explain the stock's broad appeal."],
    ]),
    grain: 3,
    contrast: 3,
    latitude: 4,
    saturation: 3,
    color_balance: "Daylight-balanced with warm, nostalgic consumer color",
    color_balance_type: "daylight",
    color_balance_kelvin: 5500,
    dx_coding: true,
    development_process: "c41",
    best_for: ["general_purpose", "travel", "street", "golden_hour"],
    discontinued: true,
    price_tier: null,
    base_price_usd: null,
    image_url: "/films/ferrania-solaris-fg-plus-200.jpg",
    year_introduced: 1999,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-ferrania-solaris-fg-plus-400",
    name: "Ferrania Solaris FG Plus 400",
    slug: "ferrania-solaris-fg-plus-400",
    brand_id: "brand-ferrania",
    format: ["35mm"],
    type: "color_negative",
    iso: 400,
    description:
      "The high-speed Solaris variant leans further into grain, contrast, and that rough-edged discount-store color look many photographers now seek on purpose. It is lo-fi in an appealing, fully analog way.",
    history: sharedHistories.ferraniaSolaris,
    shooting_notes: notes([
      ["Skin Tones", "Warm but less polished. Faces can look lively and nostalgic, though the faster emulsion brings more grain and bite."],
      ["Color Bias", "Bold, warm consumer color. It favors obvious reds and straightforward contrast over subtle shading."],
      ["Push/Pull", "Serviceable at higher ratings. It can be pushed in a pinch, but the film becomes grittier and less nuanced quickly."],
      ["Shadow Detail", "Fair for a consumer 400 stock. It keeps enough information for available-light shooting, though thin negatives go muddy."],
      ["Highlight Roll-off", "Still forgiving. Like many color negatives, bright areas remain easier to manage than the grainier body of the image suggests."],
    ]),
    grain: 4,
    contrast: 4,
    latitude: 4,
    saturation: 4,
    color_balance: "Daylight-balanced with bold, warm consumer color",
    color_balance_type: "daylight",
    color_balance_kelvin: 5500,
    dx_coding: true,
    development_process: "c41",
    best_for: ["general_purpose", "travel", "street", "low_light"],
    discontinued: true,
    price_tier: null,
    base_price_usd: null,
    image_url: "/films/ferrania-solaris-fg-plus-400.jpg",
    year_introduced: 1999,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-fujifilm-astia-100f",
    name: "Fujichrome Astia 100F",
    slug: "fujifilm-astia-100f",
    brand_id: "brand-fujifilm",
    format: ["35mm", "120", "4x5"],
    type: "color_reversal",
    iso: 100,
    description:
      "Fuji's portrait-friendly slide film, prized for soft skin tones and restrained saturation compared with the more famous Provia and Velvia lines. Astia 100F offered one of the gentlest ways to shoot people on E-6.",
    history:
      "Astia evolved as Fujifilm's softer professional transparency option and reached its mature form with Astia 100F in the early 2000s. It became a cult favorite among portrait and fashion photographers before Fujifilm discontinued it during the slide-film contraction.",
    shooting_notes: notes([
      ["Skin Tones", "Beautifully gentle for slide film. Faces stay luminous and flattering without the extra redness that can creep into more saturated emulsions."],
      ["Color Bias", "Soft, pastel, and polished. Astia keeps a refined palette that feels elegant rather than dramatic."],
      ["Push/Pull", "Best with precise box-speed exposure. Like most E-6 stocks, it prefers discipline over heavy processing tricks."],
      ["Shadow Detail", "Moderately narrow. It is kinder than Velvia in darker tones, but still unmistakably slide film."],
      ["Highlight Roll-off", "Smooth by transparency standards. Highlights stay attractive when metered carefully, especially for skin and fabric."],
    ]),
    grain: 1,
    contrast: 2,
    latitude: 2,
    saturation: 2,
    color_balance: "Daylight-balanced with soft pastel slide-film color",
    color_balance_type: "daylight",
    color_balance_kelvin: 5500,
    dx_coding: true,
    development_process: "e6",
    best_for: ["portrait", "weddings", "studio", "golden_hour"],
    discontinued: true,
    price_tier: null,
    base_price_usd: null,
    image_url: "/films/fujifilm-astia-100f.jpg",
    year_introduced: 2001,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-fujifilm-fujicolor-100",
    name: "Fujicolor 100",
    slug: "fujifilm-fujicolor-100",
    brand_id: "brand-fujifilm",
    format: ["35mm"],
    type: "color_negative",
    iso: 100,
    description:
      "A straightforward Fujifilm daylight consumer stock that favors clean blues, tidy grain, and simple, reliable color. It sits closer to neutral everyday film than the more stylized Superia family.",
    history:
      "Fujicolor 100 was part of Fujifilm's late consumer-film simplification, giving many markets a plain-spoken daylight option after the richer Superia lineup began to narrow. It became a quiet but useful bridge between budget consumer film and the company's more distinctive emulsions.",
    shooting_notes: currentColorNotes.generalPurpose,
    grain: 2,
    contrast: 2,
    latitude: 4,
    saturation: 2,
    color_balance: "Daylight-balanced with clean, restrained Fuji consumer color",
    color_balance_type: "daylight",
    color_balance_kelvin: 5500,
    dx_coding: true,
    development_process: "c41",
    best_for: ["general_purpose", "travel", "bright_sun"],
    discontinued: true,
    price_tier: null,
    base_price_usd: null,
    image_url: "/films/fujifilm-fujicolor-100.jpg",
    year_introduced: 2011,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-fujifilm-neopan-400",
    name: "Neopan 400",
    slug: "fujifilm-neopan-400",
    brand_id: "brand-fujifilm",
    format: ["35mm", "120"],
    type: "bw_negative",
    iso: 400,
    description:
      "A discontinued Fuji black-and-white film known for strong sharpness, crisp contrast, and a cleaner look than many older 400-speed monochrome stocks. Neopan 400 combined speed with a polished tonal structure that made it versatile beyond simple reportage.",
    history:
      "Neopan 400 was one of Fujifilm's most respected black-and-white stocks before the company withdrew from the category. Its disappearance left many photographers missing a high-speed monochrome film with a distinctly Fuji balance of clarity and restraint.",
    shooting_notes: notes([
      ["Tonal Range", "Clean and modern. It gives a crisp grayscale with more polish than many gritty 400-speed classics."],
      ["Push/Pull", "Adaptable enough. It handles a one-stop push competently, though its nicest look comes from confident box-speed exposure."],
      ["Shadow Detail", "Solid in practice. Dark values stay usable if the negative is not starved for light."],
      ["Highlight Roll-off", "Controlled and tidy. Highlights stay orderly instead of blooming, which suits the film's refined feel."],
    ]),
    grain: 2,
    contrast: 3,
    latitude: 4,
    saturation: null,
    color_balance: "Neutral monochrome with polished Fuji tonality",
    color_balance_type: null,
    color_balance_kelvin: null,
    dx_coding: true,
    development_process: "bw",
    best_for: ["street", "documentary", "general_purpose", "travel"],
    discontinued: true,
    price_tier: null,
    base_price_usd: null,
    image_url: "/films/fujifilm-neopan-400.jpg",
    year_introduced: 1980,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-fujifilm-neopan-1600",
    name: "Neopan 1600",
    slug: "fujifilm-neopan-1600",
    brand_id: "brand-fujifilm",
    format: ["35mm"],
    type: "bw_negative",
    iso: 1600,
    description:
      "A cult high-speed monochrome stock that delivered atmospheric grain, real low-light reach, and a surprisingly controlled tonal scale for its speed. Neopan 1600 is remembered as one of Fuji's most charismatic films.",
    history:
      "Fujifilm introduced Neopan 1600 as part of its professional black-and-white range for photographers who needed genuine speed without abandoning image quality. Its discontinuation turned it into a benchmark for late-night street and documentary work.",
    shooting_notes: notes([
      ["Tonal Range", "Moody and compressed in a useful way. It gives fast-film drama without collapsing completely into mush."],
      ["Push/Pull", "Built for low light. It can be pushed further, but its big appeal is already having real box-speed reach."],
      ["Shadow Detail", "Impressive for 1600-speed film. Extra light helps, though the stock still resolves dark scenes better than most rivals of its class."],
      ["Highlight Roll-off", "Reasonably controlled. Highlights stay more composed than the speed might suggest when exposure is sensible."],
    ]),
    grain: 4,
    contrast: 3,
    latitude: 4,
    saturation: null,
    color_balance: "Neutral monochrome tuned for low-light speed",
    color_balance_type: null,
    color_balance_kelvin: null,
    dx_coding: true,
    development_process: "bw",
    best_for: ["low_light", "street", "documentary", "artificial_light"],
    discontinued: true,
    price_tier: null,
    base_price_usd: null,
    image_url: "/films/fujifilm-neopan-1600.jpg",
    year_introduced: 1989,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-fujifilm-pro-160ns",
    name: "Fujicolor Pro 160NS",
    slug: "fujifilm-pro-160ns",
    brand_id: "brand-fujifilm",
    format: ["35mm", "120", "4x5"],
    type: "color_negative",
    iso: 160,
    description:
      "A portrait and wedding favorite that emphasized neutral skin, fine grain, and soft contrast over obvious color drama. Pro 160NS is one of the clearest expressions of Fuji's calm, polished professional negative look.",
    history:
      "Pro 160NS emerged from Fujifilm's professional portrait family after the earlier Pro 160S and 160C stocks. It became the neutral portrait option in the line, sitting beside the cooler Pro 400H and the faster Pro 800Z.",
    shooting_notes: notes([
      ["Skin Tones", "Smooth and understated. It was built for flattering portrait color without heavy warmth or candy-bright saturation."],
      ["Color Bias", "Neutral with a cool Fuji cleanliness. The palette is calm, tidy, and easy to shape in scanning or printing."],
      ["Push/Pull", "Best with slight overexposure. That keeps the stock creamy, while pushing works against its polished portrait strengths."],
      ["Shadow Detail", "Very good. It keeps delicate low-end separation in shade and controlled light."],
      ["Highlight Roll-off", "Soft and professional. Highlights compress gently, which made the film easy to trust for skin and white fabric."],
    ]),
    grain: 2,
    contrast: 2,
    latitude: 5,
    saturation: 2,
    color_balance: "Daylight-balanced with neutral professional portrait color",
    color_balance_type: "daylight",
    color_balance_kelvin: 5500,
    dx_coding: true,
    development_process: "c41",
    best_for: ["portrait", "weddings", "studio", "golden_hour"],
    discontinued: true,
    price_tier: null,
    base_price_usd: null,
    image_url: "/films/fujifilm-pro-160ns.jpg",
    year_introduced: 2010,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-fujifilm-pro-400",
    name: "Fujicolor Pro 400",
    slug: "fujifilm-pro-400",
    brand_id: "brand-fujifilm",
    format: ["35mm", "120"],
    type: "color_negative",
    iso: 400,
    description:
      "A professional Fuji color negative stock built for speed, cleaner grain than consumer 400 films, and a restrained palette that still held shape in mixed light. It sits historically between older pro emulsions and the later Pro 400H identity.",
    history:
      "Fujifilm's Pro 400 labeling covered more than one generation of professional 400-speed negative film before the line consolidated around 400H. The stock represents Fuji's long-running effort to offer a cooler, more neutral alternative to Kodak's portrait-negative family.",
    shooting_notes: notes([
      ["Skin Tones", "Calm and believable. Faces stay cleaner and less amber than many consumer 400-speed films."],
      ["Color Bias", "Neutral with a subtle cool lean. It reads more professional and less nostalgic than budget color stocks."],
      ["Push/Pull", "Comfortable at speed. It can be pushed modestly, though slight overexposure keeps the palette more graceful."],
      ["Shadow Detail", "Strong enough for real work. It handles mixed and lower light better than slower portrait negatives."],
      ["Highlight Roll-off", "Smooth and forgiving. Bright areas compress well, which is part of the stock's pro-negative appeal."],
    ]),
    grain: 2,
    contrast: 2,
    latitude: 5,
    saturation: 2,
    color_balance: "Daylight-balanced with neutral professional color",
    color_balance_type: "daylight",
    color_balance_kelvin: 5500,
    dx_coding: true,
    development_process: "c41",
    best_for: ["portrait", "weddings", "documentary", "general_purpose"],
    discontinued: true,
    price_tier: null,
    base_price_usd: null,
    image_url: "/films/fujifilm-pro-400.jpg",
    year_introduced: 2004,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-fujifilm-pro-800z",
    name: "Fujicolor Pro 800Z",
    slug: "fujifilm-pro-800z",
    brand_id: "brand-fujifilm",
    format: ["35mm", "120"],
    type: "color_negative",
    iso: 800,
    description:
      "A premium high-speed portrait negative film that kept Fuji's polished color style while extending into wedding-reception and available-light territory. Pro 800Z made speed feel elegant instead of merely convenient.",
    history:
      "Fuji positioned Pro 800Z as the fastest member of its professional portrait line, built for mixed light, event work, and handheld medium format. It became especially loved by wedding photographers before Fujifilm trimmed the range.",
    shooting_notes: notes([
      ["Skin Tones", "Warm enough to flatter, clean enough to stay professional. It handles event portraits with less chaos than most 800-speed color films."],
      ["Color Bias", "Balanced with gentle warmth. The palette feels polished rather than aggressively consumer-bright."],
      ["Push/Pull", "Very capable. It can stretch upward when needed, though box speed already covers a lot of low-light ground."],
      ["Shadow Detail", "Excellent for its speed. Dark areas keep more information than most 800-speed color stocks."],
      ["Highlight Roll-off", "Smooth and resilient. Bright dresses, windows, and practical lights stay easier to tame than expected."],
    ]),
    grain: 3,
    contrast: 2,
    latitude: 5,
    saturation: 3,
    color_balance: "Daylight-balanced with polished high-speed portrait color",
    color_balance_type: "daylight",
    color_balance_kelvin: 5500,
    dx_coding: true,
    development_process: "c41",
    best_for: ["portrait", "weddings", "low_light", "artificial_light"],
    discontinued: true,
    price_tier: null,
    base_price_usd: null,
    image_url: "/films/fujifilm-pro-800z.jpg",
    year_introduced: 2005,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-fujifilm-provia-400x",
    name: "Provia 400X",
    slug: "fujifilm-provia-400x",
    brand_id: "brand-fujifilm",
    format: ["35mm", "120"],
    type: "color_reversal",
    iso: 400,
    description:
      "A rare fast slide film that delivered real 400-speed practicality without giving up Fuji's crisp E-6 color. Provia 400X offered unusually flexible transparency shooting for travel, action, and dimmer outdoor light.",
    history:
      "Fujifilm launched Provia 400X as the high-speed member of the Provia family, keeping a more neutral palette than Velvia while giving slide shooters far more speed than traditional 100-speed E-6. It remains one of the most fondly remembered fast slide films ever made.",
    shooting_notes: currentColorNotes.slideBalanced,
    grain: 2,
    contrast: 4,
    latitude: 2,
    saturation: 4,
    color_balance: "Daylight-balanced with crisp, fast slide-film color",
    color_balance_type: "daylight",
    color_balance_kelvin: 5500,
    dx_coding: true,
    development_process: "e6",
    best_for: ["travel", "landscapes", "bright_sun", "sports"],
    discontinued: true,
    price_tier: null,
    base_price_usd: null,
    image_url: "/films/fujifilm-provia-400x.jpg",
    year_introduced: 2006,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-fujifilm-reala-ace-100",
    name: "Reala Ace 100",
    slug: "fujifilm-reala-ace-100",
    brand_id: "brand-fujifilm",
    format: ["35mm", "120"],
    type: "color_negative",
    iso: 100,
    description:
      "A current Fujifilm color negative stock aimed at photographers who want clean contrast, refined color separation, and a more premium feel than basic consumer film. Reala Ace 100 emphasizes clarity and polish over nostalgic softness.",
    history:
      "Reala Ace returned the Reala name to current Fujifilm use after years of absence, first drawing attention through the company's digital film simulation and then through limited-market still-film availability. It sits as a modern, premium-leaning daylight negative rather than a retro reissue.",
    shooting_notes: notes([
      ["Skin Tones", "Clean and controlled. Faces stay believable and slightly refined rather than overtly warm."],
      ["Color Bias", "Neutral with crisp Fuji separation. Greens and blues stay clear, while warm tones do not overwhelm the frame."],
      ["Push/Pull", "Best near box speed. It is designed around clean daylight performance rather than heavy rating changes."],
      ["Shadow Detail", "Very good. The negative holds enough information to stay flexible in scanning without becoming flat."],
      ["Highlight Roll-off", "Smooth and modern. Highlights keep shape well, which helps the stock feel premium and tidy."],
    ]),
    grain: 2,
    contrast: 3,
    latitude: 4,
    saturation: 3,
    color_balance: "Daylight-balanced with modern, premium Fuji color",
    color_balance_type: "daylight",
    color_balance_kelvin: 5500,
    dx_coding: true,
    development_process: "c41",
    best_for: ["general_purpose", "travel", "portrait", "bright_sun"],
    discontinued: false,
    price_tier: 2,
    base_price_usd: 15,
    image_url: "/films/fujifilm-reala-ace-100.jpg",
    year_introduced: 2024,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-fujifilm-superia-200",
    name: "Superia 200",
    slug: "fujifilm-superia-200",
    brand_id: "brand-fujifilm",
    format: ["35mm"],
    type: "color_negative",
    iso: 200,
    description:
      "A mid-speed Fuji consumer film with brighter color than C200 and a more familiar Superia bite in greens and blues. It sits in the sweet spot for travel and daylight point-and-shoot use.",
    history:
      "Superia 200 was part of the broad Superia consumer family that carried Fujifilm through the 1990s and 2000s. It gave photographers a cleaner, slightly punchier alternative to the cheaper C200-style end of the lineup.",
    shooting_notes: notes([
      ["Skin Tones", "Fresh but slightly cool. Faces can look lively, though not as creamy as portrait-focused films."],
      ["Color Bias", "Classic Fuji consumer balance. Greens and blues come forward a bit more than warm Kodak-style films."],
      ["Push/Pull", "Best with a little extra light. Overexposure smooths it out, while pushing mostly adds coarseness."],
      ["Shadow Detail", "Good in everyday scenes. It has enough negative-film forgiveness for travel and casual metering."],
      ["Highlight Roll-off", "Friendly and usable. Bright daylight stays manageable without the exactness of slide film."],
    ]),
    grain: 2,
    contrast: 3,
    latitude: 4,
    saturation: 3,
    color_balance: "Daylight-balanced with crisp Fuji consumer color",
    color_balance_type: "daylight",
    color_balance_kelvin: 5500,
    dx_coding: true,
    development_process: "c41",
    best_for: ["general_purpose", "travel", "street", "bright_sun"],
    discontinued: true,
    price_tier: null,
    base_price_usd: null,
    image_url: "/films/fujifilm-superia-200.jpg",
    year_introduced: 2003,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-fujifilm-superia-800",
    name: "Superia 800",
    slug: "fujifilm-superia-800",
    brand_id: "brand-fujifilm",
    format: ["35mm"],
    type: "color_negative",
    iso: 800,
    description:
      "A high-speed consumer color film that combined Fuji's recognizable cool-leaning palette with genuinely useful low-light flexibility. Superia 800 brought faster everyday shooting to compact cameras and casual event work.",
    history:
      "Superia 800 sat near the top of Fuji's consumer line as a practical fast film for travel, family events, and flash-free interiors. It faded away as the company narrowed its catalog, but it remains a reference point for affordable high-speed color.",
    shooting_notes: notes([
      ["Skin Tones", "Lively and a little cool. Faces stay usable, though the consumer palette is less gentle than Fuji's pro line."],
      ["Color Bias", "Cool and punchy. Greens, blues, and mixed-light scenes carry that recognizable Superia edge."],
      ["Push/Pull", "Naturally at home in low light. It can stretch, but its main strength is already starting at 800."],
      ["Shadow Detail", "Strong for a consumer-speed film. It keeps more useful information than slower films forced upward."],
      ["Highlight Roll-off", "Decent and manageable. Highlights do not have pro-film elegance, but they stay workable."],
    ]),
    grain: 3,
    contrast: 3,
    latitude: 4,
    saturation: 3,
    color_balance: "Daylight-balanced with cool, punchy high-speed Fuji color",
    color_balance_type: "daylight",
    color_balance_kelvin: 5500,
    dx_coding: true,
    development_process: "c41",
    best_for: ["low_light", "street", "travel", "general_purpose"],
    discontinued: true,
    price_tier: null,
    base_price_usd: null,
    image_url: "/films/fujifilm-superia-800.jpg",
    year_introduced: 1999,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-fujifilm-superia-reala-100",
    name: "Superia Reala 100",
    slug: "fujifilm-superia-reala-100",
    brand_id: "brand-fujifilm",
    format: ["35mm", "120"],
    type: "color_negative",
    iso: 100,
    description:
      "A premium Fuji daylight negative that mixed consumer friendliness with more sophisticated color and better skin rendering than basic Superia. It is often remembered as one of Fuji's most balanced color negatives.",
    history:
      "Superia Reala 100 continued the Reala idea of wide color separation and refined skin tones within Fujifilm's color-negative family. It bridged the gap between mass-market Superia stocks and the company's more explicitly professional portrait films.",
    shooting_notes: notes([
      ["Skin Tones", "Smooth and flattering. It gives faces a cleaner, more refined look than ordinary consumer Fuji film."],
      ["Color Bias", "Balanced with subtle Fuji coolness. Colors stay rich without feeling overcooked."],
      ["Push/Pull", "Best at box or slightly over. Its strengths show up in careful daylight use rather than pushed speed."],
      ["Shadow Detail", "Very solid. It keeps a surprising amount of low-end information for a 100-speed film."],
      ["Highlight Roll-off", "Controlled and elegant. Highlights stay smoother than you expect from a daylight consumer-adjacent stock."],
    ]),
    grain: 1,
    contrast: 3,
    latitude: 4,
    saturation: 3,
    color_balance: "Daylight-balanced with refined Fuji daylight color",
    color_balance_type: "daylight",
    color_balance_kelvin: 5500,
    dx_coding: true,
    development_process: "c41",
    best_for: ["portrait", "travel", "general_purpose", "bright_sun"],
    discontinued: true,
    price_tier: null,
    base_price_usd: null,
    image_url: "/films/fujifilm-superia-reala-100.jpg",
    year_introduced: 2004,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-fujifilm-velvia-100f",
    name: "Velvia 100F",
    slug: "fujifilm-velvia-100f",
    brand_id: "brand-fujifilm",
    format: ["35mm", "120", "4x5"],
    type: "color_reversal",
    iso: 100,
    description:
      "A more restrained branch of the Velvia family, balancing fine grain and saturated slide-film clarity with noticeably less aggression than Velvia 50 or Velvia 100. It is the Velvia name for photographers who still wanted some subtlety.",
    history:
      "Fujifilm introduced Velvia 100F as a gentler, more neutral-minded extension of the Velvia brand before later consolidating around the punchier Velvia 100. It became a favorite among photographers who liked slide-film crispness but found classic Velvia too intense.",
    shooting_notes: currentColorNotes.slideBalanced,
    grain: 1,
    contrast: 4,
    latitude: 2,
    saturation: 3,
    color_balance: "Daylight-balanced with polished, less aggressive Velvia color",
    color_balance_type: "daylight",
    color_balance_kelvin: 5500,
    dx_coding: true,
    development_process: "e6",
    best_for: ["landscapes", "travel", "architecture", "bright_sun"],
    discontinued: true,
    price_tier: null,
    base_price_usd: null,
    image_url: "/films/fujifilm-velvia-100f.jpg",
    year_introduced: 2002,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-kentmere-pan-200",
    name: "Kentmere Pan 200",
    slug: "kentmere-pan-200",
    brand_id: "brand-kentmere",
    format: ["35mm", "120"],
    type: "bw_negative",
    iso: 200,
    description:
      "A newly added middle-speed Kentmere stock that sits between the brand's 100 and 400 emulsions, giving photographers a practical blend of manageable grain and more flexible exposure than slow films. It is an everyday monochrome film built with Harman's usual reliability.",
    history:
      "Harman Technology introduced Kentmere Pan 200 in 2025 as the first expansion of the Kentmere still-film line in years. The film broadened Kentmere from a two-speed budget option into a fuller monochrome family.",
    shooting_notes: notes([
      ["Tonal Range", "Balanced and useful. It gives a straightforward grayscale without the heaviness of faster budget films."],
      ["Push/Pull", "Moderately adaptable. It can move a little in either direction, but its strength is dependable mid-speed versatility."],
      ["Shadow Detail", "Good and easy to hold. There is enough latitude for casual metering and everyday subjects."],
      ["Highlight Roll-off", "Clean with a gentle shoulder. Highlights stay pleasant and printable without drama."],
    ]),
    grain: 2,
    contrast: 3,
    latitude: 4,
    saturation: null,
    color_balance: "Neutral monochrome with Harman-made everyday tonality",
    color_balance_type: null,
    color_balance_kelvin: null,
    dx_coding: true,
    development_process: "bw",
    best_for: ["general_purpose", "street", "travel", "documentary"],
    discontinued: false,
    price_tier: 1,
    base_price_usd: 9,
    image_url: "/films/kentmere-pan-200.jpg",
    year_introduced: 2025,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-kodak-bw400cn",
    name: "Kodak BW400CN",
    slug: "kodak-bw400cn",
    brand_id: "brand-kodak",
    format: ["35mm"],
    type: "bw_negative",
    iso: 400,
    description:
      "Kodak's chromogenic black-and-white film delivered monochrome images through standard C-41 processing, making it easy for minilabs and casual shooters to work in black and white. The look is smoother and cleaner than traditional silver-rich 400-speed films.",
    history:
      "BW400CN gave Kodak a consumer-friendly black-and-white option for the one-hour lab era, standing apart from Ilford XP2 but serving a similar purpose. Its convenience and smooth scans kept it relevant long after serious darkroom users moved elsewhere.",
    shooting_notes: notes([
      ["Tonal Range", "Smooth and modern. It lacks the gritty silver look of traditional 400-speed monochrome and instead feels cleaner and more linear."],
      ["Push/Pull", "Flexible in practical use. The film handles casual exposure variation well, helped by chromogenic processing and forgiving scanning."],
      ["Shadow Detail", "Very good. It keeps dark tones more open than many traditional 400-speed black-and-white films."],
      ["Highlight Roll-off", "Soft and easy. Bright values fade out gently, which is one reason scans from BW400CN tend to feel polished."],
    ]),
    grain: 2,
    contrast: 2,
    latitude: 5,
    saturation: null,
    color_balance: "Chromogenic monochrome with smooth, scan-friendly tonality",
    color_balance_type: null,
    color_balance_kelvin: null,
    dx_coding: true,
    development_process: "c41",
    best_for: ["general_purpose", "travel", "portrait", "documentary"],
    discontinued: true,
    price_tier: null,
    base_price_usd: null,
    image_url: "/films/kodak-bw400cn.jpg",
    year_introduced: 1998,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-kodak-ektachrome-e100g",
    name: "Kodak Ektachrome E100G",
    slug: "kodak-ektachrome-e100g",
    brand_id: "brand-kodak",
    format: ["35mm", "120", "4x5"],
    type: "color_reversal",
    iso: 100,
    description:
      "A neutral professional Ektachrome designed for accurate color, fine grain, and a cooler, cleaner alternative to warmer or more saturated slide stocks. E100G is the restrained side of Kodak's modern-era transparency family.",
    history:
      "Kodak positioned E100G as the general-purpose professional option within the E100 generation, with the 'G' emphasizing more neutral color than the vivid VS variant. It became a standard choice for editorial, travel, and commercial work that wanted slide precision without theatrical saturation.",
    shooting_notes: currentColorNotes.slideBalanced,
    grain: 1,
    contrast: 4,
    latitude: 2,
    saturation: 3,
    color_balance: "Daylight-balanced with neutral, editorial Ektachrome color",
    color_balance_type: "daylight",
    color_balance_kelvin: 5500,
    dx_coding: true,
    development_process: "e6",
    best_for: ["landscapes", "travel", "portrait", "architecture"],
    discontinued: true,
    price_tier: null,
    base_price_usd: null,
    image_url: "/films/kodak-ektachrome-e100g.jpg",
    year_introduced: 2004,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-kodak-ektachrome-e100vs",
    name: "Kodak Ektachrome E100VS",
    slug: "kodak-ektachrome-e100vs",
    brand_id: "brand-kodak",
    format: ["35mm", "120", "4x5"],
    type: "color_reversal",
    iso: 100,
    description:
      "The vivid member of Kodak's E100 family, designed for photographers who wanted transparency-film sharpness with a more dramatic palette than neutral Ektachrome. E100VS pushes color harder without becoming full Velvia territory.",
    history:
      "Kodak introduced E100VS as a higher-saturation professional alternative within the E100 line, giving travel and nature shooters a more intense option while keeping Ektachrome's overall clarity and grain structure. It was especially popular among photographers who liked bold slide color but not Fuji's exact flavor.",
    shooting_notes: notes([
      ["Skin Tones", "Bold rather than forgiving. Faces can look striking, but the extra saturation needs careful scene choice."],
      ["Color Bias", "Rich and vivid. Reds, blues, and warm light all come forward more aggressively than on neutral Ektachrome."],
      ["Push/Pull", "Limited in the usual E-6 way. It is best used for its native look rather than aggressive processing shifts."],
      ["Shadow Detail", "Typical slide-film discipline. Dark values need accurate placement and do not tolerate casual underexposure."],
      ["Highlight Roll-off", "Precise and unforgiving. Highlights stay beautiful when metered carefully but offer little rescue room."],
    ]),
    grain: 1,
    contrast: 4,
    latitude: 2,
    saturation: 4,
    color_balance: "Daylight-balanced with vivid professional Ektachrome color",
    color_balance_type: "daylight",
    color_balance_kelvin: 5500,
    dx_coding: true,
    development_process: "e6",
    best_for: ["landscapes", "travel", "bright_sun", "experimental"],
    discontinued: true,
    price_tier: null,
    base_price_usd: null,
    image_url: "/films/kodak-ektachrome-e100vs.jpg",
    year_introduced: 2002,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-kodak-kodachrome-25",
    name: "Kodachrome 25",
    slug: "kodak-kodachrome-25",
    brand_id: "brand-kodak",
    format: ["35mm"],
    type: "color_reversal",
    iso: 25,
    description:
      "The slowest and finest-grained Kodachrome variant, famous for extraordinary sharpness, stable archival color, and a disciplined, luminous slide look. Kodachrome 25 rewards careful daylight work with a level of delicacy few transparency films ever matched.",
    history: sharedHistories.kodachrome,
    shooting_notes: notes([
      ["Skin Tones", "Natural and beautifully detailed. Faces can look superb when the light suits the film and exposure is exact."],
      ["Color Bias", "Rich but disciplined. Colors feel deep and archival rather than exaggerated or neon-bright."],
      ["Push/Pull", "Tied to the K-14 world. The stock was never about flexible home-style experimentation; it asked for precision from start to finish."],
      ["Shadow Detail", "Moderate and placement-sensitive. Kodachrome likes careful metering in contrasty scenes."],
      ["Highlight Roll-off", "Elegant but exacting. Highlights stay gorgeous when controlled, with none of negative film's rescue margin."],
    ]),
    grain: 1,
    contrast: 4,
    latitude: 2,
    saturation: 3,
    color_balance: "Daylight-balanced with deep, archival Kodachrome color",
    color_balance_type: "daylight",
    color_balance_kelvin: 5500,
    dx_coding: true,
    development_process: "e6",
    best_for: ["travel", "portrait", "bright_sun", "documentary"],
    discontinued: true,
    price_tier: null,
    base_price_usd: null,
    image_url: "/films/kodak-kodachrome-25.jpg",
    year_introduced: 1961,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-kodak-kodachrome-64",
    name: "Kodachrome 64",
    slug: "kodak-kodachrome-64",
    brand_id: "brand-kodak",
    format: ["35mm", "120"],
    type: "color_reversal",
    iso: 64,
    description:
      "The most iconic Kodachrome speed, balancing practical daylight usability with the line's famous color and fine grain. Kodachrome 64 became synonymous with editorial travel photography for a reason.",
    history: sharedHistories.kodachrome,
    shooting_notes: notes([
      ["Skin Tones", "Natural and memorable. It gave portraits a believable, documentary warmth without cheapening the palette."],
      ["Color Bias", "Deep, rich, and unmistakably Kodachrome. The color feels dense and stable rather than merely saturated."],
      ["Push/Pull", "A precision transparency stock. Flexibility was never the point; consistent processing and accurate exposure were."],
      ["Shadow Detail", "Good for slide film when exposed carefully. It is more practical than the 25-speed version but still not forgiving."],
      ["Highlight Roll-off", "Controlled and exact. Highlights can be beautiful, though they demand respect in bright conditions."],
    ]),
    grain: 1,
    contrast: 4,
    latitude: 2,
    saturation: 3,
    color_balance: "Daylight-balanced with rich, iconic Kodachrome color",
    color_balance_type: "daylight",
    color_balance_kelvin: 5500,
    dx_coding: true,
    development_process: "e6",
    best_for: ["travel", "documentary", "portrait", "bright_sun"],
    discontinued: true,
    price_tier: null,
    base_price_usd: null,
    image_url: "/films/kodak-kodachrome-64.jpg",
    year_introduced: 1974,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-kodak-kodachrome-200",
    name: "Kodachrome 200",
    slug: "kodak-kodachrome-200",
    brand_id: "brand-kodak",
    format: ["35mm"],
    type: "color_reversal",
    iso: 200,
    description:
      "The fastest Kodachrome, built to make the line more practical for lower light and faster work while keeping its recognizable palette. It gave up some refinement compared with K25 and K64, but it brought Kodachrome into more demanding shooting situations.",
    history: sharedHistories.kodachrome,
    shooting_notes: notes([
      ["Skin Tones", "Believable but less delicate than the slower Kodachromes. The higher speed brings a slightly rougher transparency feel."],
      ["Color Bias", "Still recognizably Kodachrome. The palette stays rich and deep, just with a touch less refinement."],
      ["Push/Pull", "Designed to be the practical Kodachrome. Even so, it remained a film that wanted accurate exposure and disciplined processing."],
      ["Shadow Detail", "Useful for its class. The extra speed makes darker scenes more manageable than the slower Kodachromes."],
      ["Highlight Roll-off", "Still a slide-film shoulder. Highlights stay attractive when placed carefully, but tolerance remains limited."],
    ]),
    grain: 2,
    contrast: 4,
    latitude: 2,
    saturation: 3,
    color_balance: "Daylight-balanced with fast, rich Kodachrome color",
    color_balance_type: "daylight",
    color_balance_kelvin: 5500,
    dx_coding: true,
    development_process: "e6",
    best_for: ["travel", "documentary", "low_light", "bright_sun"],
    discontinued: true,
    price_tier: null,
    base_price_usd: null,
    image_url: "/films/kodak-kodachrome-200.jpg",
    year_introduced: 1986,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-kodak-plus-x-pan-125",
    name: "Kodak Plus-X Pan 125",
    slug: "kodak-plus-x-pan-125",
    brand_id: "brand-kodak",
    format: ["35mm", "120", "4x5"],
    type: "bw_negative",
    iso: 125,
    description:
      "A classic Kodak medium-speed black-and-white film with fine grain, moderate contrast, and an easy tonal curve that made it a darkroom favorite for decades. Plus-X sat between highly technical slow films and the grittier drama of Tri-X.",
    history:
      "Plus-X was one of Kodak's foundational black-and-white still films and remained in production, in one form or another, through much of the twentieth century. It became shorthand for clean, traditional monochrome before being overshadowed by faster and more specialized stocks.",
    shooting_notes: notes([
      ["Tonal Range", "Traditional and graceful. It gives a classic Kodak grayscale with smooth mids and restrained contrast."],
      ["Push/Pull", "Best when treated gently. It can move a little, but the appeal is its clean box-speed elegance."],
      ["Shadow Detail", "Good and trustworthy. It keeps darker values open without turning the image flat."],
      ["Highlight Roll-off", "Soft and beautifully printable. Highlights fade out with that old-school darkroom ease."],
    ]),
    grain: 2,
    contrast: 2,
    latitude: 4,
    saturation: null,
    color_balance: "Classic neutral Kodak monochrome",
    color_balance_type: null,
    color_balance_kelvin: null,
    dx_coding: true,
    development_process: "bw",
    best_for: ["portrait", "landscapes", "documentary", "general_purpose"],
    discontinued: true,
    price_tier: null,
    base_price_usd: null,
    image_url: "/films/kodak-plus-x-pan-125.jpg",
    year_introduced: 1954,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-kodak-tri-x-professional-320",
    name: "Kodak Tri-X Professional 320",
    slug: "kodak-tri-x-professional-320",
    brand_id: "brand-kodak",
    format: ["4x5", "8x10"],
    type: "bw_negative",
    iso: 320,
    description:
      "The sheet-film expression of Tri-X, offering the same classic Kodak bite and darkroom personality in large-format sizes. It combines Tri-X atmosphere with the smoother tonality and control that come from bigger negatives.",
    history:
      "Tri-X Professional in sheet film kept the famous Tri-X look available to studio, landscape, and fine-art photographers long after most attention shifted to 35mm reportage. It remains one of the few classic-grain Kodak films still offered in large-format practice.",
    shooting_notes: notes([
      ["Tonal Range", "Rich and classic. It has the familiar Tri-X punch, but large-format use lets the tonal scale feel more spacious and elegant."],
      ["Push/Pull", "More flexible than many sheet films. It can be adjusted for zone-system work or pushed modestly without losing its identity."],
      ["Shadow Detail", "Good and expressive. It gives shadows a strong presence while keeping enough texture for printmaking."],
      ["Highlight Roll-off", "Pleasingly rounded. Highlights hold a classic silver-gelatin feel that suits large-format printing."],
    ]),
    grain: 3,
    contrast: 4,
    latitude: 4,
    saturation: null,
    color_balance: "Classic Tri-X monochrome in sheet-film form",
    color_balance_type: null,
    color_balance_kelvin: null,
    dx_coding: false,
    development_process: "bw",
    best_for: ["portrait", "studio", "landscapes", "documentary"],
    discontinued: false,
    price_tier: 3,
    base_price_usd: 45,
    image_url: "/films/kodak-tri-x-professional-320.jpg",
    year_introduced: 1954,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-kodak-vision3-50d",
    name: "Kodak Vision3 50D",
    slug: "kodak-vision3-50d",
    brand_id: "brand-kodak",
    format: ["35mm"],
    type: "color_negative",
    iso: 50,
    description:
      "A daylight-balanced motion-picture stock with extremely fine grain, long highlight handling, and that polished cinema-negative feel still photographers love in respooled form. 50D is the cleanest and brightest member of the Vision3 family.",
    history: sharedHistories.vision3,
    shooting_notes: notes([
      ["Skin Tones", "Clean and cinematic. Faces stay natural, with a polished negative look rather than consumer warmth."],
      ["Color Bias", "Balanced daylight color. It feels neutral and modern, with enough shape to scan beautifully."],
      ["Push/Pull", "Best at intended speed or with slight overexposure. Still-photography users usually lean into its latitude more than big rating changes."],
      ["Shadow Detail", "Excellent. Dark areas stay remarkably open when processed and scanned well."],
      ["Highlight Roll-off", "A major strength. Bright values compress with the soft, expensive feel people associate with cinema stock."],
    ]),
    grain: 1,
    contrast: 2,
    latitude: 5,
    saturation: 2,
    color_balance: "Daylight-balanced cinema negative with long highlight latitude",
    color_balance_type: "daylight",
    color_balance_kelvin: 5500,
    dx_coding: false,
    development_process: "ecn2",
    best_for: ["landscapes", "portrait", "bright_sun", "architecture"],
    discontinued: false,
    price_tier: 2,
    base_price_usd: 13,
    image_url: "/films/kodak-vision3-50d.jpg",
    year_introduced: 2007,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-kodak-vision3-250d",
    name: "Kodak Vision3 250D",
    slug: "kodak-vision3-250d",
    brand_id: "brand-kodak",
    format: ["35mm"],
    type: "color_negative",
    iso: 250,
    description:
      "The versatile middle-speed Vision3 stock, balancing cinema-grade latitude with far more practical speed than 50D. It is one of the most adaptable daylight motion stocks for still-photography respooling.",
    history: sharedHistories.vision3,
    shooting_notes: notes([
      ["Skin Tones", "Natural and polished. It gives faces a clean cinema-negative feel without obvious consumer-film bias."],
      ["Color Bias", "Balanced daylight color with modern restraint. It scans into either neutral or richer looks with ease."],
      ["Push/Pull", "Very usable. It can be pushed or overexposed according to the workflow, which is part of its popularity with still shooters."],
      ["Shadow Detail", "Excellent. It holds plenty of low-end information for mixed daylight and interiors with windows."],
      ["Highlight Roll-off", "Extremely smooth. Highlights stay one of the stock's defining strengths."],
    ]),
    grain: 2,
    contrast: 2,
    latitude: 5,
    saturation: 2,
    color_balance: "Daylight-balanced cinema negative with wide scanning latitude",
    color_balance_type: "daylight",
    color_balance_kelvin: 5500,
    dx_coding: false,
    development_process: "ecn2",
    best_for: ["general_purpose", "travel", "portrait", "documentary"],
    discontinued: false,
    price_tier: 2,
    base_price_usd: 14,
    image_url: "/films/kodak-vision3-250d.jpg",
    year_introduced: 2007,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-kodak-vision3-500t",
    name: "Kodak Vision3 500T",
    slug: "kodak-vision3-500t",
    brand_id: "brand-kodak",
    format: ["35mm"],
    type: "color_negative",
    iso: 500,
    description:
      "A tungsten-balanced cinema stock that has become one of the most sought-after motion-derived choices for still photographers. 500T is loved for low-light flexibility, halation when remjet is removed, and deep cinematic color under practical light.",
    history: sharedHistories.vision3,
    shooting_notes: notes([
      ["Skin Tones", "Natural under tungsten and moody in mixed light. Faces can look strikingly cinematic when the stock is used for the environments it was built for."],
      ["Color Bias", "Tungsten-balanced by design. Warm practicals look correct, while daylight without filtration turns cool and stylized."],
      ["Push/Pull", "Very capable. It is already fast, and users often lean on pushes or scanner latitude in darker conditions."],
      ["Shadow Detail", "Excellent for a fast color stock. It retains a lot of information in low-light scenes."],
      ["Highlight Roll-off", "Cinema-soft and forgiving. Bright lamps and signage stay smoother than most still films allow."],
    ]),
    grain: 3,
    contrast: 2,
    latitude: 5,
    saturation: 2,
    color_balance: "Tungsten-balanced cinema negative with strong low-light latitude",
    color_balance_type: "tungsten",
    color_balance_kelvin: 3200,
    dx_coding: false,
    development_process: "ecn2",
    best_for: ["low_light", "artificial_light", "street", "documentary"],
    discontinued: false,
    price_tier: 2,
    base_price_usd: 15,
    image_url: "/films/kodak-vision3-500t.jpg",
    year_introduced: 2007,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-kosmo-foto-agent-shadow-400",
    name: "Kosmo Foto Agent Shadow 400",
    slug: "kosmo-foto-agent-shadow-400",
    brand_id: "brand-kosmo-foto",
    format: ["35mm"],
    type: "bw_negative",
    iso: 400,
    description:
      "A fast black-and-white film released by Kosmo Foto for photographers who want a classic grain structure with practical speed and easy availability. Agent Shadow 400 leans into flexible everyday monochrome rather than exotic specialization.",
    history:
      "Kosmo Foto announced Agent Shadow in 2021 and officially launched it in 2022, extending the brand beyond its original Mono 100 offering. The stock gave the company a more versatile companion film aimed at street, travel, and general low-light use.",
    shooting_notes: notes([
      ["Tonal Range", "Classic and approachable. It has the familiar 400-speed monochrome balance of useful mids, punchy blacks, and workable highlights."],
      ["Push/Pull", "Designed to be flexible. It handles moderate pushing well enough for street and low-light work."],
      ["Shadow Detail", "Good and practical. Dark areas keep enough information for documentary shooting without feeling flat."],
      ["Highlight Roll-off", "Pleasantly controlled. Highlights stay easy to print and scan, which suits the stock's all-purpose intent."],
    ]),
    grain: 3,
    contrast: 3,
    latitude: 4,
    saturation: null,
    color_balance: "Classic panchromatic monochrome with flexible 400-speed rendering",
    color_balance_type: null,
    color_balance_kelvin: null,
    dx_coding: true,
    development_process: "bw",
    best_for: ["street", "general_purpose", "travel", "documentary"],
    discontinued: false,
    price_tier: 1,
    base_price_usd: 10,
    image_url: "/films/kosmo-foto-agent-shadow-400.jpg",
    year_introduced: 2022,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-lucky-c200",
    name: "Lucky C200",
    slug: "lucky-c200",
    brand_id: "brand-lucky",
    format: ["35mm"],
    type: "color_negative",
    iso: 200,
    description:
      "Lucky's return to color negative film, offering a fresh consumer-stock option from a manufacturer long absent from the color market. C200 is notable as much for its existence as for its character: a warm, slightly rough-edged daylight film with clear snapshot energy.",
    history:
      "Lucky re-entered the color market in 2025 after years focused away from consumer color still film, making C200 a significant launch for photographers eager to see new emulsions rather than only rebrands and discontinuations. Early coverage positioned it as the beginning of a broader Lucky color revival.",
    shooting_notes: notes([
      ["Skin Tones", "Warm and direct. Faces have a sunny, consumer-film feel rather than a refined portrait palette."],
      ["Color Bias", "Slightly warm and nostalgic. It leans into straightforward color rather than polished neutrality."],
      ["Push/Pull", "Best used simply. Box speed or a touch of overexposure keeps the stock feeling open and friendly."],
      ["Shadow Detail", "Fair to good. It works best with enough daylight and does not love thin exposure."],
      ["Highlight Roll-off", "Pleasantly forgiving. Bright scenes hold together in the easy way people expect from C-41 consumer film."],
    ]),
    grain: 3,
    contrast: 3,
    latitude: 4,
    saturation: 3,
    color_balance: "Daylight-balanced with warm, newly revived Lucky consumer color",
    color_balance_type: "daylight",
    color_balance_kelvin: 5500,
    dx_coding: true,
    development_process: "c41",
    best_for: ["general_purpose", "travel", "bright_sun", "golden_hour"],
    discontinued: false,
    price_tier: 1,
    base_price_usd: 8,
    image_url: "/films/lucky-c200.jpg",
    year_introduced: 2025,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-lucky-shd-100",
    name: "Lucky SHD 100",
    slug: "lucky-shd-100",
    brand_id: "brand-lucky",
    format: ["35mm", "120"],
    type: "bw_negative",
    iso: 100,
    description:
      "A budget-friendly black-and-white film with a traditional look, moderate contrast, and enough speed for everyday daylight shooting. SHD 100 is about honest monochrome rather than boutique polish.",
    history: sharedHistories.luckyBw,
    shooting_notes: notes([
      ["Tonal Range", "Traditional and straightforward. It gives a familiar black-and-white scale without much stylization."],
      ["Push/Pull", "Best close to box speed. Slight overexposure smooths things out, while hard pushes make the film feel rougher."],
      ["Shadow Detail", "Good when the negative gets enough light. It is forgiving enough for a budget stock, but not endlessly so."],
      ["Highlight Roll-off", "Pleasantly classic. Highlights keep a soft analog shoulder instead of turning brittle."],
    ]),
    grain: 2,
    contrast: 3,
    latitude: 3,
    saturation: null,
    color_balance: "Classic monochrome with affordable, traditional Lucky tonality",
    color_balance_type: null,
    color_balance_kelvin: null,
    dx_coding: true,
    development_process: "bw",
    best_for: ["general_purpose", "street", "travel", "bright_sun"],
    discontinued: false,
    price_tier: 1,
    base_price_usd: 7,
    image_url: "/films/lucky-shd-100.jpg",
    year_introduced: 2017,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-lucky-shd-400",
    name: "Lucky SHD 400",
    slug: "lucky-shd-400",
    brand_id: "brand-lucky",
    format: ["35mm", "120"],
    type: "bw_negative",
    iso: 400,
    description:
      "The faster SHD option adds more grit and flexibility for street, documentary, and lower-light shooting while staying firmly in the affordable-film lane. It is practical, contrasty, and intentionally unpretentious.",
    history: sharedHistories.luckyBw,
    shooting_notes: notes([
      ["Tonal Range", "Punchy and straightforward. It gives a classic budget-400 look with enough bite for street and documentary use."],
      ["Push/Pull", "Willing to stretch. It handles moderate pushes in the gritty, honest way people often want from affordable monochrome."],
      ["Shadow Detail", "Reasonably good. It keeps usable low-end information when exposure is sensible, though deep underexposure gets rough fast."],
      ["Highlight Roll-off", "Firm but manageable. Highlights stay printable if the film is not overdeveloped."],
    ]),
    grain: 4,
    contrast: 4,
    latitude: 4,
    saturation: null,
    color_balance: "Classic high-speed monochrome with gritty Lucky character",
    color_balance_type: null,
    color_balance_kelvin: null,
    dx_coding: true,
    development_process: "bw",
    best_for: ["street", "documentary", "general_purpose", "low_light"],
    discontinued: false,
    price_tier: 1,
    base_price_usd: 7,
    image_url: "/films/lucky-shd-400.jpg",
    year_introduced: 2025,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-lomography-lomochrome-color-92",
    name: "LomoChrome Color '92",
    slug: "lomography-lomochrome-color-92",
    brand_id: "brand-lomography",
    format: ["35mm", "120"],
    type: "color_negative",
    iso: 400,
    description:
      "A creative color negative film designed to channel the softer, warmer consumer-film character of the early 1990s. Color '92 is less about wild effects than about gentle nostalgia with visible personality.",
    history: sharedHistories.lomochrome92,
    shooting_notes: notes([
      ["Effect Character", "Subtle nostalgia rather than gimmickry. It softens the modern look and pushes the frame toward a warm early-1990s mood."],
      ["Effect Intensity", "Moderate. The effect is clear, but it does not overwhelm the scene the way stronger pre-exposed films do."],
      ["Scene Pairing", "Works especially well with daylight street scenes, travel, and portraits where a gentle throwback palette feels natural."],
      ["Exposure Flexibility", "Quite usable. It behaves like a normal negative film with a stylized palette, so slight overexposure is often rewarding."],
      ["Highlight Behavior", "Soft and creamy. Highlights help sell the nostalgic character instead of clipping harshly."],
    ]),
    grain: 3,
    contrast: 2,
    latitude: 4,
    saturation: 2,
    color_balance: "Daylight-balanced with warm, nostalgic early-1990s color",
    color_balance_type: "daylight",
    color_balance_kelvin: 5500,
    dx_coding: true,
    development_process: "c41",
    best_for: ["portrait", "travel", "general_purpose", "experimental", "golden_hour"],
    discontinued: false,
    price_tier: 2,
    base_price_usd: 14,
    image_url: "/films/lomography-lomochrome-color-92.jpg",
    year_introduced: 2023,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-lomography-lomochrome-color-92-sun-kissed",
    name: "LomoChrome Color '92 Sun-kissed",
    slug: "lomography-lomochrome-color-92-sun-kissed",
    brand_id: "brand-lomography",
    format: ["35mm", "120"],
    type: "color_negative",
    iso: 400,
    description:
      "A warmer, more amber-leaning variation on Color '92, built to intensify the nostalgic summer-memories side of the formula. Sun-kissed pushes the stock further toward glow, warmth, and late-day softness.",
    history:
      "Lomography followed Color '92 with Sun-kissed as an expanded expression of the same nostalgic concept, shifting the palette toward warmer highlights and more overt golden-hour character. It turned a subtle throwback film into a more scene-shaping creative stock.",
    shooting_notes: notes([
      ["Effect Character", "Warm and nostalgic. It leans harder into amber light and memory-film warmth than the standard Color '92 stock."],
      ["Effect Intensity", "Noticeable but still photographically usable. The effect shapes the frame without turning every scene into an abstract gimmick."],
      ["Scene Pairing", "Best with golden light, sunlit travel scenes, and portraits where warmth is part of the mood."],
      ["Exposure Flexibility", "Likes extra light. Overexposure strengthens the soft, amber quality that makes the film distinctive."],
      ["Highlight Behavior", "Glowy and warm. Highlights bloom into the nostalgic look instead of staying clinically neutral."],
    ]),
    grain: 3,
    contrast: 2,
    latitude: 4,
    saturation: 3,
    color_balance: "Daylight-balanced with warm, sunlit nostalgic color",
    color_balance_type: "daylight",
    color_balance_kelvin: 5500,
    dx_coding: true,
    development_process: "c41",
    best_for: ["portrait", "travel", "golden_hour", "experimental"],
    discontinued: false,
    price_tier: 2,
    base_price_usd: 14,
    image_url: "/films/lomography-lomochrome-color-92-sun-kissed.jpg",
    year_introduced: 2024,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-lomography-lomochrome-turquoise",
    name: "LomoChrome Turquoise XR 100-400",
    slug: "lomography-lomochrome-turquoise",
    brand_id: "brand-lomography",
    format: ["35mm", "120"],
    type: "color_negative",
    iso: 200,
    description:
      "A deliberately effect-driven stock that remaps familiar colors into turquoise, cobalt, and surreal false-color combinations. It is one of Lomography's clearest invitations to treat color negative film as an interpretive medium rather than a documentary one.",
    history:
      "LomoChrome Turquoise became a signature creative stock in Lomography's experimental lineup by offering dramatic color transpositions without requiring lab trickery. Its XR labeling reflected the flexible rating options users could exploit to steer the effect.",
    shooting_notes: notes([
      ["Effect Character", "Strong and surreal. Color relationships shift dramatically, turning ordinary scenes into false-color compositions."],
      ["Effect Intensity", "High. This is a clear statement film rather than a subtle mood tweak."],
      ["Scene Pairing", "Best for bold landscapes, travel, signage, and subjects with strong color blocks that can survive remapping."],
      ["Exposure Flexibility", "Part of the fun. Different ratings noticeably change how aggressively the effect shows up."],
      ["Highlight Behavior", "Stylized but usable. Highlights often intensify the unreal palette instead of simply washing out."],
    ]),
    grain: 3,
    contrast: 3,
    latitude: 3,
    saturation: 5,
    color_balance: "Daylight-balanced effect film with turquoise false-color shifts",
    color_balance_type: "daylight",
    color_balance_kelvin: 5500,
    dx_coding: true,
    development_process: "c41",
    best_for: ["travel", "landscapes", "experimental", "bright_sun"],
    discontinued: false,
    price_tier: 2,
    base_price_usd: 14,
    image_url: "/films/lomography-lomochrome-turquoise.jpg",
    year_introduced: 2021,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-lomography-redscale-xr",
    name: "Lomography Redscale XR 50-200",
    slug: "lomography-redscale-xr",
    brand_id: "brand-lomography",
    format: ["35mm", "120"],
    type: "color_negative",
    iso: 100,
    description:
      "A redscale effect film that shifts the world toward oranges, reds, yellows, and sepia by exposing through the base side of the emulsion. Redscale XR makes every scene feel heated, nostalgic, or slightly apocalyptic depending on the light.",
    history:
      "Lomography turned redscale from a DIY trick into an accessible commercial stock, then expanded it with XR variable-speed packaging so photographers could tune the effect. It remains one of the simplest ways to get a dramatic altered-color look on standard C-41 processing.",
    shooting_notes: notes([
      ["Effect Character", "Warm, heavy, and unmistakable. The film transforms the frame into a redscale world of amber, rust, and burnt orange."],
      ["Effect Intensity", "High but tunable. The variable-speed approach lets photographers move between warm nostalgia and full heat-wave intensity."],
      ["Scene Pairing", "Best with direct sun, architecture, travel scenes, and subjects where the altered palette becomes part of the message."],
      ["Exposure Flexibility", "Central to the stock. Different ratings materially shift density and the strength of the redscale effect."],
      ["Highlight Behavior", "Glowing and amber. Highlights merge into the warm cast instead of staying clean and neutral."],
    ]),
    grain: 3,
    contrast: 4,
    latitude: 3,
    saturation: 5,
    color_balance: "Daylight-balanced redscale effect with amber and orange dominance",
    color_balance_type: "daylight",
    color_balance_kelvin: 5500,
    dx_coding: true,
    development_process: "c41",
    best_for: ["travel", "experimental", "bright_sun", "golden_hour"],
    discontinued: false,
    price_tier: 2,
    base_price_usd: 13,
    image_url: "/films/lomography-redscale-xr.jpg",
    year_introduced: 2010,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-orwo-un54",
    name: "ORWO UN54",
    slug: "orwo-un54",
    brand_id: "brand-orwo",
    format: ["35mm"],
    type: "bw_negative",
    iso: 100,
    description:
      "A motion-picture black-and-white stock repurposed for still photography, valued for its classic cine tonality and smooth midtones. UN54 feels less like a boutique still film and more like a slice of working cinema stock.",
    history:
      "UN54 comes from ORWO's motion-picture heritage and has been repurposed into still-photography workflows through respooling and niche retail channels. Its renewed visibility helped connect the relaunched ORWO brand with its deeper production history.",
    shooting_notes: notes([
      ["Tonal Range", "Cinematic and classic. It gives a smooth grayscale with less bite than surveillance-derived films and more character than ultra-modern technical stocks."],
      ["Push/Pull", "Best around box speed. It can move a little, but the stock's charm is really in its native cine-negative balance."],
      ["Shadow Detail", "Good and gentle. Dark areas hold together nicely when the negative is treated generously."],
      ["Highlight Roll-off", "Soft and filmic. Highlights taper in a way that feels more motion-picture than still-photo harshness."],
    ]),
    grain: 2,
    contrast: 2,
    latitude: 4,
    saturation: null,
    color_balance: "Cinema-derived monochrome with smooth midtones",
    color_balance_type: null,
    color_balance_kelvin: null,
    dx_coding: false,
    development_process: "bw",
    best_for: ["documentary", "portrait", "general_purpose", "street"],
    discontinued: false,
    price_tier: 2,
    base_price_usd: 12,
    image_url: "/films/orwo-un54.jpg",
    year_introduced: 2022,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-orwo-wolfen-nc400",
    name: "WOLFEN NC400",
    slug: "orwo-wolfen-nc400",
    brand_id: "brand-orwo",
    format: ["35mm"],
    type: "color_negative",
    iso: 400,
    description:
      "A modern ORWO still-film stock with visible grain, muted color, and a deliberately less polished look than mainstream C-41 options. NC400 stands out for its dry, cinematic palette and refusal to mimic Kodak or Fuji directly.",
    history:
      "WOLFEN NC400 followed the relaunch of ORWO-branded color still film and helped define the company's new identity in the analog market. Rather than chasing clean consumer color, it embraced a moodier, lower-saturation aesthetic rooted in the Wolfen name.",
    shooting_notes: notes([
      ["Skin Tones", "Subdued and slightly cool. Faces feel more cinematic and moody than creamy or conventionally flattering."],
      ["Color Bias", "Muted with a dry, modern-retro cast. Colors stay restrained instead of glossy."],
      ["Push/Pull", "Better treated gently. It likes careful metering and enough exposure more than aggressive speed chasing."],
      ["Shadow Detail", "Moderate. Shadows can go dense fast, especially if the stock is underexposed."],
      ["Highlight Roll-off", "Reasonably soft. Highlights help keep the stock's moody look from turning completely harsh."],
    ]),
    grain: 4,
    contrast: 3,
    latitude: 3,
    saturation: 2,
    color_balance: "Daylight-balanced with muted, cinematic ORWO color",
    color_balance_type: "daylight",
    color_balance_kelvin: 5500,
    dx_coding: true,
    development_process: "c41",
    best_for: ["street", "documentary", "travel", "experimental"],
    discontinued: false,
    price_tier: 2,
    base_price_usd: 12,
    image_url: "/films/orwo-wolfen-nc400.jpg",
    year_introduced: 2024,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-rollei-atp-1-1",
    name: "Rollei ATP 1.1",
    slug: "rollei-atp-1-1",
    brand_id: "brand-rollei",
    format: ["35mm", "120"],
    type: "bw_negative",
    iso: 32,
    description:
      "A specialist ultra-fine-grain black-and-white film made for maximum resolution and a technical, highly detailed look. ATP 1.1 is not casual material; it is for photographers who want control, sharpness, and a very precise monochrome result.",
    history:
      "Rollei ATP 1.1 emerged from the company's technical-film side, drawing on surveillance and high-resolution emulsion traditions rather than classic pictorial rendering. It became a niche favorite among detail-focused photographers comfortable with exacting workflows.",
    shooting_notes: notes([
      ["Tonal Range", "Precise and technical. It is more about resolution and crisp separation than easy, romantic grayscale."],
      ["Push/Pull", "Very limited. The stock wants disciplined metering and matched development rather than flexible speed changes."],
      ["Shadow Detail", "Fragile if mistreated. Dark values need thoughtful exposure to avoid collapsing."],
      ["Highlight Roll-off", "Controlled but not generous. Highlights stay clean when handled properly, though the film is never especially forgiving."],
    ]),
    grain: 1,
    contrast: 4,
    latitude: 2,
    saturation: null,
    color_balance: "Technical monochrome with extremely high resolving power",
    color_balance_type: null,
    color_balance_kelvin: null,
    dx_coding: true,
    development_process: "bw",
    best_for: ["architecture", "studio", "landscapes", "bright_sun"],
    discontinued: false,
    price_tier: 2,
    base_price_usd: 10,
    image_url: "/films/rollei-atp-1-1.jpg",
    year_introduced: 2004,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-rollei-crossbird-200",
    name: "Rollei Crossbird 200",
    slug: "rollei-crossbird-200",
    brand_id: "brand-rollei",
    format: ["35mm", "120"],
    type: "color_reversal",
    iso: 200,
    description:
      "A slide film explicitly marketed with cross-processing in mind, blending conventional reversal clarity with a more playful, stylized identity than standard E-6 stocks. Crossbird 200 sits at the boundary between normal color and effect film.",
    history:
      "Rollei introduced Crossbird to serve photographers who wanted a transparency stock that welcomed experimental C-41 cross-processing rather than merely tolerating it. It became one of the more memorable specialty slide films of the boutique-film era.",
    shooting_notes: notes([
      ["Skin Tones", "Variable by workflow. In standard E-6 it is lively and contrasty; cross-processed, it becomes far more stylized."],
      ["Color Bias", "Built for drama. Even before cross-processing, the palette feels punchy and a little less neutral than mainstream slide films."],
      ["Push/Pull", "Best used creatively rather than technically. The fun lies more in process choice than careful rating shifts."],
      ["Shadow Detail", "Typical slide-film limits. Dark tones need care, especially if the photographer is also aiming for effect-driven processing."],
      ["Highlight Roll-off", "Bright and exact. Highlights reward careful metering, then get even wilder if the film is cross-processed."],
    ]),
    grain: 2,
    contrast: 4,
    latitude: 2,
    saturation: 4,
    color_balance: "Daylight-balanced slide film designed to shine in cross-processing",
    color_balance_type: "daylight",
    color_balance_kelvin: 5500,
    dx_coding: true,
    development_process: "e6",
    best_for: ["travel", "experimental", "bright_sun", "landscapes"],
    discontinued: true,
    price_tier: null,
    base_price_usd: null,
    image_url: "/films/rollei-crossbird-200.jpg",
    year_introduced: 2010,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-rollei-ortho-25-plus",
    name: "Rollei Ortho 25 Plus",
    slug: "rollei-ortho-25-plus",
    brand_id: "brand-rollei",
    format: ["35mm", "120", "4x5"],
    type: "bw_negative",
    iso: 25,
    description:
      "A very slow orthographic film that emphasizes sharpness, smooth grain, and dramatic red suppression for landscape and studio use. Ortho 25 Plus is a precision monochrome stock for controlled light and deliberate shooting.",
    history:
      "Rollei's Ortho 25 Plus reflects the boutique-film era's renewed interest in specialist spectral sensitivity and slower, tripod-friendly emulsions. It gives photographers an off-mainstream alternative to ordinary panchromatic daylight work.",
    shooting_notes: notes([
      ["Tonal Range", "Clean and sculpted. The orthographic response gives scenes a distinctive, deliberate separation."],
      ["Push/Pull", "Made for careful exposure. It is a specialty slow film, so rating changes are less useful than simply feeding it light."],
      ["Shadow Detail", "Good when treated generously. Shadows stay elegant in bright scenes, but this is not a speed film."],
      ["Highlight Roll-off", "Bright and well behaved. Highlights stay crisp without the harshness of microfilm-style emulsions."],
    ]),
    grain: 1,
    contrast: 4,
    latitude: 3,
    saturation: null,
    color_balance: "Orthochromatic monochrome with strong separation and ultra-fine grain",
    color_balance_type: null,
    color_balance_kelvin: null,
    dx_coding: true,
    development_process: "bw",
    best_for: ["architecture", "landscapes", "studio", "bright_sun"],
    discontinued: false,
    price_tier: 2,
    base_price_usd: 9,
    image_url: "/films/rollei-ortho-25-plus.jpg",
    year_introduced: 2021,
    rating: 0,
    featured: false,
  }),
  buildStock({
    id: "stock-street-candy-atm-400",
    name: "Street Candy ATM 400",
    slug: "street-candy-atm-400",
    brand_id: "brand-street-candy",
    format: ["35mm"],
    type: "bw_negative",
    iso: 400,
    description:
      "A surveillance-derived black-and-white film repackaged for still photographers who want gritty speed, sharpness, and hard-edged urban character. ATM 400 feels unapologetically utilitarian in the best way.",
    history:
      "Street Candy built its identity around repurposed industrial and monitoring films, and ATM 400 continues that approach at a faster speed than the original MTN 100. It carries the brand's CCTV-inspired aesthetic directly into handheld, lower-light work.",
    shooting_notes: notes([
      ["Tonal Range", "Graphic and gritty. It leans toward stronger separation and a more industrial monochrome feel than classic portrait films."],
      ["Push/Pull", "Well suited to being driven. The stock accepts higher ratings with the roughness many users actually want from it."],
      ["Shadow Detail", "Modest but useful. It can hold dark detail, though its aesthetic is more about grit than softness."],
      ["Highlight Roll-off", "Firm and punchy. Highlights stay bright and emphatic rather than gentle or glowing."],
    ]),
    grain: 3,
    contrast: 5,
    latitude: 3,
    saturation: null,
    color_balance: "Surveillance-derived monochrome with graphic contrast",
    color_balance_type: null,
    color_balance_kelvin: null,
    dx_coding: false,
    development_process: "bw",
    best_for: ["street", "documentary", "low_light", "experimental"],
    discontinued: false,
    price_tier: 1,
    base_price_usd: 10,
    image_url: "/films/street-candy-atm-400.jpg",
    year_introduced: 2023,
    rating: 0,
    featured: false,
  }),
];
