/**
 * Fixed pool for the share-roll tag picker “Popular tags” section.
 * Display order is this array order; tags disappear from the list once added.
 */
export const SHARE_ROLL_POPULAR_TAGS: readonly string[] = [
  "Landscapes",
  "Street",
  "Portrait",
  "Architecture",
  "Documentary",
  "Travel",
  "Black and white",
  "Night",
  "Golden hour",
  "Blue hour",
  "Sunrise",
  "Sunset",
  "Urban",
  "Nature",
  "Wildlife",
  "Macro",
  "Still life",
  "Fashion",
  "Wedding",
  "Sports",
  "Concert",
  "Film photography",
  "Analog",
  "35mm",
  "Medium format",
  "Large format",
  "Polaroid",
  "Instant",
  "Candid",
  "Minimal",
  "Abstract",
  "Fine art",
  "Editorial",
  "Commercial",
  "Studio",
  "Natural light",
  "Flash",
  "Long exposure",
  "HDR",
  "Panorama",
  "Aerial",
  "Drone",
  "Underwater",
  "Food",
  "Product",
  "Automotive",
  "Industrial",
  "Rural",
  "Coastal",
  "Mountains",
  "Forest",
  "Desert",
  "Snow",
  "Rain",
  "Fog",
  "Mist",
  "Spring",
  "Summer",
  "Autumn",
  "Winter",
  "Cherry blossoms",
  "Bokeh",
  "High key",
  "Low key",
  "Silhouette",
  "Reflection",
  "Symmetry",
  "Leading lines",
  "Negative space",
  "Vintage",
  "Grain",
  "Surreal",
  "Experimental",
  "Double exposure",
  "Light painting",
  "Astrophotography",
  "Milky way",
  "Moon",
  "Stars",
  "Cityscape",
  "Skyline",
  "Brutalism",
  "Heritage",
  "Interior",
  "Real estate",
  "Lifestyle",
  "Family",
  "Newborn",
  "Pet",
  "Bird",
  "Insect",
  "Flower",
  "Botanical",
  "Seascape",
  "Lakes",
  "River",
  "Waterfall",
  "National park",
  "Road trip",
  "Camping",
  "Hiking",
  "Backpacking",
  "Street art",
  "Graffiti",
  "Neon",
  "Noir",
  "Cinematic",
  "Moody",
  "Bright",
  "Pastel",
  "Monochrome",
  "Sepia",
  "Cross process",
  "Push process",
  "Home developed",
  "Scanned",
  "Darkroom",
] as const;
