-- Backfill grain, contrast, latitude, development_process, and best_for for all film stocks.
-- Data from src/lib/seed-data.ts and known specs. Run after 011 so CHECK constraints exist.
-- Only updates rows that exist (match slug). Safe to run multiple times.

UPDATE film_stocks AS f
SET
  grain = v.grain,
  contrast = v.contrast,
  latitude = v.latitude,
  development_process = v.development_process,
  best_for = v.best_for
FROM (VALUES
  -- (slug, grain, contrast, latitude, development_process, best_for)
  ('kodak-portra-400', 'fine', 'low', 'very_wide', 'c41', ARRAY['portrait','wedding','travel','everyday']),
  ('kodak-portra-800', 'medium', 'medium', 'wide', 'c41', ARRAY['portrait','wedding','night']),
  ('kodak-portra-160', 'fine', 'low', 'wide', 'c41', ARRAY['portrait','wedding','studio']),
  ('kodak-gold-200', 'medium', 'medium', 'wide', 'c41', ARRAY['travel','everyday','street']),
  ('kodak-ultramax-400', 'medium', 'high', 'wide', 'c41', ARRAY['travel','everyday','street']),
  ('kodak-proimage-100', 'fine', 'low', 'wide', 'c41', ARRAY['portrait','wedding','travel','everyday']),
  ('kodak-ektar-100', 'fine', 'high', 'moderate', 'c41', ARRAY['landscape','travel']),
  ('kodak-colorplus-200', 'medium', 'medium', 'moderate', 'c41', ARRAY['everyday','travel']),
  ('kodak-tri-x-400', 'medium', 'high', 'very_wide', 'bw', ARRAY['street','portrait','everyday']),
  ('kodak-tmax-400', 'fine', 'medium', 'wide', 'bw', ARRAY['portrait','studio','landscape']),
  ('kodak-tmax-100', 'fine', 'medium', 'moderate', 'bw', ARRAY['landscape','studio','portrait']),
  ('kodak-tmax-p3200', 'strong', 'high', 'moderate', 'bw', ARRAY['night','street']),
  ('kodak-ektachrome-e100', 'fine', 'high', 'narrow', 'e6', ARRAY['landscape','travel','portrait']),
  ('kodak-double-x', 'medium', 'low', 'wide', 'bw', ARRAY['street','portrait']),
  ('fujifilm-superia-400', 'medium', 'high', 'wide', 'c41', ARRAY['street','travel','everyday']),
  ('fujifilm-c200', 'medium', 'low', 'moderate', 'c41', ARRAY['everyday','travel']),
  ('fujifilm-pro-400h', 'fine', 'low', 'very_wide', 'c41', ARRAY['portrait','wedding']),
  ('fujifilm-velvia-50', 'fine', 'high', 'very_narrow', 'e6', ARRAY['landscape']),
  ('fujifilm-provia-100f', 'fine', 'medium', 'narrow', 'e6', ARRAY['landscape','portrait','travel']),
  ('fujifilm-acros-ii', 'fine', 'medium', 'moderate', 'bw', ARRAY['landscape','studio']),
  ('fujifilm-velvia-100', 'fine', 'high', 'narrow', 'e6', ARRAY['landscape','travel']),
  ('fujifilm-superia-premium-400', 'fine', 'medium', 'wide', 'c41', ARRAY['everyday','travel','portrait']),
  ('fujifilm-natura-1600', 'medium', 'low', 'wide', 'c41', ARRAY['night','everyday','street']),
  ('ilford-hp5-plus', 'medium', 'medium', 'very_wide', 'bw', ARRAY['street','portrait','everyday']),
  ('ilford-delta-3200', 'strong', 'high', 'moderate', 'bw', ARRAY['night','street']),
  ('ilford-fp4-plus', 'fine', 'medium', 'wide', 'bw', ARRAY['landscape','studio']),
  ('ilford-xp2-super', 'fine', 'medium', 'very_wide', 'c41', ARRAY['travel','everyday']),
  ('ilford-delta-100', 'fine', 'medium', 'moderate', 'bw', ARRAY['landscape','studio','portrait']),
  ('ilford-delta-400', 'fine', 'medium', 'wide', 'bw', ARRAY['portrait','street','landscape']),
  ('ilford-pan-f-plus', 'fine', 'medium', 'moderate', 'bw', ARRAY['landscape','studio']),
  ('ilford-sfx-200', 'medium', 'high', 'moderate', 'bw', ARRAY['landscape']),
  ('ilford-ortho-plus', 'fine', 'medium', 'moderate', 'bw', ARRAY['landscape','portrait','studio']),
  ('cinestill-800t', 'medium', 'medium', 'wide', 'c41', ARRAY['night','street']),
  ('cinestill-50d', 'fine', 'medium', 'wide', 'c41', ARRAY['portrait','landscape','travel']),
  ('cinestill-400d', 'fine', 'medium', 'wide', 'c41', ARRAY['everyday','portrait','travel']),
  ('cinestill-bwxx', 'medium', 'low', 'wide', 'bw', ARRAY['street','portrait','everyday']),
  ('lomography-color-negative-100', 'fine', 'medium', 'moderate', 'c41', ARRAY['landscape','travel','street','everyday']),
  ('lomography-color-negative-400', 'medium', 'medium', 'wide', 'c41', ARRAY['street','everyday','travel','portrait']),
  ('lomography-color-negative-800', 'strong', 'high', 'wide', 'c41', ARRAY['night','street','everyday','travel']),
  ('lomography-lady-grey-400', 'medium', 'medium', 'wide', 'bw', ARRAY['portrait','street','everyday']),
  ('lomography-berlin-kino-400', 'strong', 'high', 'moderate', 'bw', ARRAY['street','portrait','night']),
  ('lomography-earl-grey-100', 'fine', 'medium', 'moderate', 'bw', ARRAY['portrait','street','landscape','everyday']),
  ('lomography-lomochrome-purple', 'fine', 'medium', 'very_wide', 'c41', ARRAY['landscape','travel','portrait','everyday']),
  ('lomography-lomochrome-metropolis', 'fine', 'low', 'wide', 'c41', ARRAY['street','portrait','travel','everyday']),
  ('lomography-potsdam-kino-100', 'fine', 'medium', 'wide', 'bw', ARRAY['portrait','studio','landscape']),
  ('lomography-fantome-kino-8', 'fine', 'medium', 'narrow', 'bw', ARRAY['landscape','studio','portrait']),
  ('fomapan-100-classic', 'medium', 'medium', 'moderate', 'bw', ARRAY['portrait','landscape','street','everyday']),
  ('fomapan-200-creative', 'medium', 'medium', 'wide', 'bw', ARRAY['street','portrait','everyday','travel']),
  ('fomapan-400-action', 'strong', 'high', 'wide', 'bw', ARRAY['street','everyday','night','travel']),
  ('fomapan-r-100', 'fine', 'high', 'very_narrow', 'bw', ARRAY['landscape','studio','portrait']),
  ('retropan-320-soft', 'fine', 'low', 'wide', 'bw', ARRAY['portrait','landscape','studio']),
  ('rollei-rpx-25', 'fine', 'medium', 'moderate', 'bw', ARRAY['landscape','portrait','studio']),
  ('rollei-rpx-100', 'fine', 'medium', 'wide', 'bw', ARRAY['landscape','portrait','street','everyday']),
  ('rollei-rpx-400', 'medium', 'high', 'wide', 'bw', ARRAY['street','everyday','night','travel']),
  ('rollei-infrared-400', 'medium', 'high', 'narrow', 'bw', ARRAY['landscape','portrait','travel']),
  ('rollei-retro-80s', 'fine', 'high', 'moderate', 'bw', ARRAY['landscape','portrait','street']),
  ('rollei-retro-400s', 'medium', 'high', 'wide', 'bw', ARRAY['landscape','street','travel','everyday']),
  ('rollei-superpan-200', 'fine', 'medium', 'wide', 'bw', ARRAY['landscape','portrait','street']),
  ('adox-silvermax-100', 'fine', 'medium', 'very_wide', 'bw', ARRAY['portrait','landscape','studio']),
  ('adox-cms-20-ii', 'fine', 'high', 'very_narrow', 'bw', ARRAY['landscape','studio','portrait']),
  ('adox-chs-100-ii', 'fine', 'medium', 'moderate', 'bw', ARRAY['portrait','landscape','street','everyday']),
  ('adox-hr-50', 'fine', 'medium', 'moderate', 'bw', ARRAY['landscape','portrait','studio']),
  ('adox-color-mission-200', 'fine', 'medium', 'wide', 'c41', ARRAY['portrait','travel','street','everyday']),
  ('kentmere-pan-100', 'fine', 'medium', 'moderate', 'bw', ARRAY['landscape','portrait','everyday']),
  ('kentmere-pan-400', 'medium', 'medium', 'wide', 'bw', ARRAY['street','everyday','travel']),
  ('bergger-pancro-400', 'fine', 'medium', 'very_wide', 'bw', ARRAY['portrait','studio','landscape']),
  ('agfa-apx-100', 'fine', 'medium', 'moderate', 'bw', ARRAY['landscape','portrait','studio']),
  ('agfa-apx-400', 'medium', 'high', 'wide', 'bw', ARRAY['street','everyday','travel']),
  ('agfa-vista-plus-200', 'fine', 'medium', 'wide', 'c41', ARRAY['everyday','travel','landscape']),
  ('jch-streetpan-400', 'medium', 'high', 'moderate', 'bw', ARRAY['street','night','travel']),
  ('washi-a', 'fine', 'low', 'very_narrow', 'bw', ARRAY['studio','landscape']),
  ('washi-s', 'fine', 'high', 'very_narrow', 'bw', ARRAY['street','studio']),
  ('silberra-u100', 'fine', 'medium', 'moderate', 'bw', ARRAY['landscape','portrait','everyday']),
  ('orwo-wolfen-nc500', 'medium', 'medium', 'wide', 'c41', ARRAY['street','everyday','travel']),
  ('orwo-wolfen-np100', 'fine', 'medium', 'moderate', 'bw', ARRAY['landscape','portrait','everyday']),
  ('harman-phoenix-200', 'strong', 'high', 'moderate', 'c41', ARRAY['street','everyday','travel']),
  ('harman-red', 'medium', 'medium', 'moderate', 'c41', ARRAY['portrait','street','everyday']),
  ('harman-switch-azure', 'medium', 'medium', 'moderate', 'c41', ARRAY['landscape','travel','everyday']),
  ('harman-phoenix-ii', 'strong', 'high', 'moderate', 'c41', ARRAY['street','everyday','travel']),
  ('dubblefilm-sunstroke', 'fine', 'medium', 'moderate', 'c41', ARRAY['travel','everyday','portrait']),
  ('dubblefilm-monsoon', 'fine', 'medium', 'moderate', 'c41', ARRAY['travel','everyday','landscape']),
  ('revolog-streak', 'fine', 'medium', 'moderate', 'c41', ARRAY['travel','portrait','everyday']),
  ('revolog-kolor', 'fine', 'medium', 'moderate', 'c41', ARRAY['travel','portrait','everyday']),
  ('revolog-460nm', 'fine', 'medium', 'moderate', 'c41', ARRAY['portrait','night','street']),
  ('street-candy-mtn-100', 'fine', 'high', 'narrow', 'bw', ARRAY['street','everyday']),
  ('ferrania-p30-alpha', 'fine', 'high', 'moderate', 'bw', ARRAY['street','portrait','landscape']),
  ('kosmo-foto-mono-100', 'fine', 'medium', 'moderate', 'bw', ARRAY['street','landscape','everyday'])
) AS v(slug, grain, contrast, latitude, development_process, best_for)
WHERE f.slug = v.slug;
