-- Update color_balance for all film stocks to a consistent format.
-- Color stocks: "X-balanced (≈XXXXK)" (e.g. Daylight-balanced (≈5500K)). CineStill 800T left unchanged.
-- B&W stocks: single word (Panchromatic, Orthochromatic, Orthopanchromatic, Chromogenic, Infrared, Reversal).
-- Researched from manufacturer specs and film databases.

UPDATE film_stocks AS f
SET color_balance = v.color_balance
FROM (VALUES
  -- Color: Daylight-balanced (≈5500K) unless noted
  ('kodak-portra-400', 'Daylight-balanced (≈5500K)'),
  ('kodak-portra-800', 'Daylight-balanced (≈5500K)'),
  ('kodak-portra-160', 'Daylight-balanced (≈5500K)'),
  ('kodak-gold-200', 'Daylight-balanced (≈5500K)'),
  ('kodak-ultramax-400', 'Daylight-balanced (≈5500K)'),
  ('kodak-proimage-100', 'Daylight-balanced (≈5500K)'),
  ('kodak-ektar-100', 'Daylight-balanced (≈5500K)'),
  ('kodak-colorplus-200', 'Daylight-balanced (≈5500K)'),
  ('kodak-ektachrome-e100', 'Daylight-balanced (≈5500K)'),
  ('fujifilm-superia-400', 'Daylight-balanced (≈5500K)'),
  ('fujifilm-c200', 'Daylight-balanced (≈5500K)'),
  ('fujifilm-pro-400h', 'Daylight-balanced (≈5500K)'),
  ('fujifilm-velvia-50', 'Daylight-balanced (≈5500K)'),
  ('fujifilm-provia-100f', 'Daylight-balanced (≈5500K)'),
  ('fujifilm-velvia-100', 'Daylight-balanced (≈5500K)'),
  ('fujifilm-superia-premium-400', 'Daylight-balanced (≈5500K)'),
  ('fujifilm-natura-1600', 'Daylight-balanced (≈5500K)'),
  ('cinestill-50d', 'Daylight-balanced (≈5500K)'),
  ('cinestill-400d', 'Daylight-balanced (≈5500K)'),
  ('lomography-color-negative-100', 'Daylight-balanced (≈5500K)'),
  ('lomography-color-negative-400', 'Daylight-balanced (≈5500K)'),
  ('lomography-color-negative-800', 'Daylight-balanced (≈5500K)'),
  ('lomography-lomochrome-purple', 'Daylight-balanced (≈5500K)'),
  ('lomography-lomochrome-metropolis', 'Daylight-balanced (≈5500K)'),
  ('adox-color-mission-200', 'Daylight-balanced (≈5500K)'),
  ('agfa-vista-plus-200', 'Daylight-balanced (≈5500K)'),
  ('orwo-wolfen-nc500', 'Daylight-balanced (≈5500K)'),
  ('harman-phoenix-200', 'Daylight-balanced (≈5500K)'),
  ('harman-red', 'Daylight-balanced (≈5500K)'),
  ('harman-switch-azure', 'Daylight-balanced (≈5500K)'),
  ('harman-phoenix-ii', 'Daylight-balanced (≈5500K)'),
  ('dubblefilm-sunstroke', 'Daylight-balanced (≈5500K)'),
  ('dubblefilm-monsoon', 'Daylight-balanced (≈5500K)'),
  ('revolog-streak', 'Daylight-balanced (≈5500K)'),
  ('revolog-kolor', 'Daylight-balanced (≈5500K)'),
  ('revolog-460nm', 'Daylight-balanced (≈5500K)'),
  -- B&W: Panchromatic (standard)
  ('kodak-tri-x-400', 'Panchromatic'),
  ('kodak-tmax-400', 'Panchromatic'),
  ('kodak-tmax-100', 'Panchromatic'),
  ('kodak-tmax-p3200', 'Panchromatic'),
  ('kodak-double-x', 'Panchromatic'),
  ('ilford-hp5-plus', 'Panchromatic'),
  ('ilford-delta-3200', 'Panchromatic'),
  ('ilford-fp4-plus', 'Panchromatic'),
  ('ilford-delta-100', 'Panchromatic'),
  ('ilford-delta-400', 'Panchromatic'),
  ('ilford-pan-f-plus', 'Panchromatic'),
  ('ilford-sfx-200', 'Panchromatic'),
  ('cinestill-bwxx', 'Panchromatic'),
  ('lomography-lady-grey-400', 'Panchromatic'),
  ('lomography-berlin-kino-400', 'Panchromatic'),
  ('lomography-earl-grey-100', 'Panchromatic'),
  ('lomography-potsdam-kino-100', 'Panchromatic'),
  ('lomography-fantome-kino-8', 'Panchromatic'),
  ('fomapan-100-classic', 'Panchromatic'),
  ('fomapan-200-creative', 'Panchromatic'),
  ('fomapan-400-action', 'Panchromatic'),
  ('retropan-320-soft', 'Panchromatic'),
  ('rollei-rpx-25', 'Panchromatic'),
  ('rollei-rpx-100', 'Panchromatic'),
  ('rollei-rpx-400', 'Panchromatic'),
  ('rollei-retro-80s', 'Panchromatic'),
  ('rollei-retro-400s', 'Panchromatic'),
  ('rollei-superpan-200', 'Panchromatic'),
  ('adox-silvermax-100', 'Panchromatic'),
  ('adox-chs-100-ii', 'Panchromatic'),
  ('adox-hr-50', 'Panchromatic'),
  ('kentmere-pan-100', 'Panchromatic'),
  ('kentmere-pan-400', 'Panchromatic'),
  ('bergger-pancro-400', 'Panchromatic'),
  ('agfa-apx-100', 'Panchromatic'),
  ('agfa-apx-400', 'Panchromatic'),
  ('jch-streetpan-400', 'Panchromatic'),
  ('silberra-u100', 'Panchromatic'),
  ('orwo-wolfen-np100', 'Panchromatic'),
  ('street-candy-mtn-100', 'Panchromatic'),
  ('ferrania-p30-alpha', 'Panchromatic'),
  ('kosmo-foto-mono-100', 'Panchromatic'),
  -- B&W: Orthochromatic (blue/green only, not red)
  ('ilford-ortho-plus', 'Orthochromatic'),
  ('washi-a', 'Orthochromatic'),
  ('washi-s', 'Orthochromatic'),
  -- B&W: Orthopanchromatic (extended green/red differentiation)
  ('fujifilm-acros-ii', 'Orthopanchromatic'),
  ('adox-cms-20-ii', 'Orthopanchromatic'),
  -- B&W: Chromogenic (C-41 process)
  ('ilford-xp2-super', 'Chromogenic'),
  -- B&W: Infrared / hyperpanchromatic
  ('rollei-infrared-400', 'Infrared'),
  -- B&W: Reversal (direct positive)
  ('fomapan-r-100', 'Reversal')
  -- cinestill-800t omitted: already correct as Tungsten-balanced (≈3200K)
) AS v(slug, color_balance)
WHERE f.slug = v.slug;
