-- Insert/update missing conventional color stocks with metadata, specs, and shooting notes.

-- Scope: agfa-vista-plus-100, agfa-vista-plus-400, ferrania-solaris-fg-plus-100, ferrania-solaris-fg-plus-200, ferrania-solaris-fg-plus-400, fujifilm-astia-100f, fujifilm-fujicolor-100, fujifilm-pro-160ns, fujifilm-pro-400, fujifilm-pro-800z, fujifilm-provia-400x, fujifilm-reala-ace-100, fujifilm-superia-200, fujifilm-superia-800, fujifilm-superia-reala-100, fujifilm-velvia-100f, kodak-ektachrome-e100g, kodak-ektachrome-e100vs, kodak-kodachrome-25, kodak-kodachrome-64, kodak-kodachrome-200, kodak-vision3-50d, kodak-vision3-250d, kodak-vision3-500t, lucky-c200, orwo-wolfen-nc400, rollei-crossbird-200

-- Note schema: Skin Tones, Color Bias, Push/Pull, Shadow Detail, Highlight Roll-off



-- Ensure supporting brands exist.

INSERT INTO film_brands (name, slug, description, website_url, featured)
VALUES (
  'Lucky',
  'lucky',
  'Lucky Film is a long-running Chinese photographic manufacturer with roots in state-backed industrial film production. The brand became internationally known for affordable black-and-white films and has recently re-entered the color market, making it one of the few companies reviving rather than shrinking a film lineup.',
  'https://luckyfilm.net/',
  NULL
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  website_url = EXCLUDED.website_url,
  featured = EXCLUDED.featured,
  updated_at = now();



-- agfa-vista-plus-100
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'AgfaPhoto Vista Plus 100',
  'agfa-vista-plus-100',
  (SELECT id FROM film_brands WHERE slug = 'agfa'),
  ARRAY['35mm']::film_format[],
  'color_negative'::film_type,
  100,
  'A daylight consumer color film with warm reds, lively greens, and the easy, holiday-snapshot character many photographers associate with late AgfaPhoto packaging. Vista Plus 100 feels simple and sunny rather than clinical or premium.',
  'After Agfa''s collapse, the AgfaPhoto name lived on through licensed consumer films sourced from other manufacturers. Vista Plus 100 became one of the more recognizable entries in that era, often associated with Ferrania-made color stock.',
  '[{"header":"Skin Tones","dek":"Warm and casual. Faces lean sunny rather than neutral, which suits family, travel, and golden-hour work."},{"header":"Color Bias","dek":"Consumer warmth with a touch of punch. Reds and greens feel cheerful without turning fully candy-colored."},{"header":"Push/Pull","dek":"Best with light to spare. It rewards box speed or mild overexposure more than any attempt to squeeze extra speed from it."},{"header":"Shadow Detail","dek":"Moderate. Shadows hold together in normal daylight, but underexposure quickly flattens the image."},{"header":"Highlight Roll-off","dek":"Pleasant and forgiving. Bright skies and light clothing stay easier to manage than on slide film."}]'::jsonb,
  2,
  3,
  4,
  3,
  'Daylight-balanced with a warm consumer palette',
  'daylight',
  5500,
  TRUE,
  'c41',
  ARRAY['general_purpose', 'travel', 'golden_hour', 'bright_sun']::text[],
  TRUE,
  '/films/agfa-vista-plus-100.jpg',
  2005,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- agfa-vista-plus-400
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'AgfaPhoto Vista Plus 400',
  'agfa-vista-plus-400',
  (SELECT id FROM film_brands WHERE slug = 'agfa'),
  ARRAY['35mm']::film_format[],
  'color_negative'::film_type,
  400,
  'The faster Vista option, known for bold reds, visible grain, and a punchy daylight look that sits between family-snapshot film and travel stock. It feels a little louder and rougher than the 100-speed version in a good way.',
  'The Solaris line was Ferrania''s mass-market color family through the late 1990s and 2000s, widely sold under Ferrania, store-brand, and rebadged packaging. It helped keep Italian-made consumer color film visible in supermarkets and camera shops long after premium slide film had become a niche.',
  '[{"header":"Skin Tones","dek":"Lively and warm. It gives portraits a cheerful consumer-film glow rather than a restrained pro look."},{"header":"Color Bias","dek":"Punchier than the slower Vista stocks. Reds and greens come forward quickly, especially in bright sun."},{"header":"Push/Pull","dek":"Decent for a consumer 400 film. It tolerates a one-stop push in a pinch, though grain and contrast rise quickly."},{"header":"Shadow Detail","dek":"Good in ordinary scenes. There is enough negative-film cushion for street and travel use, but not a huge safety net."},{"header":"Highlight Roll-off","dek":"Friendly and printable. Highlights stay smoother than the film''s saturated palette might suggest."}]'::jsonb,
  3,
  4,
  4,
  4,
  'Daylight-balanced with warm, saturated consumer color',
  'daylight',
  5500,
  TRUE,
  'c41',
  ARRAY['general_purpose', 'travel', 'street', 'golden_hour']::text[],
  TRUE,
  '/films/agfa-vista-plus-400.jpg',
  2005,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- ferrania-solaris-fg-plus-100
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Ferrania Solaris FG Plus 100',
  'ferrania-solaris-fg-plus-100',
  (SELECT id FROM film_brands WHERE slug = 'ferrania'),
  ARRAY['35mm']::film_format[],
  'color_negative'::film_type,
  100,
  'A bright-light consumer color film from Ferrania''s supermarket era, remembered for warm color and straightforward holiday-film charm. FG Plus 100 is less about perfection than about an easy, cheerful daylight look.',
  'The Solaris line was Ferrania''s mass-market color family through the late 1990s and 2000s, widely sold under Ferrania, store-brand, and rebadged packaging. It helped keep Italian-made consumer color film visible in supermarkets and camera shops long after premium slide film had become a niche.',
  '[{"header":"Skin Tones","dek":"Warm and approachable. Portraits feel casual and friendly rather than polished or fashion-forward."},{"header":"Color Bias","dek":"Sunny and slightly nostalgic. Warm tones and simple color separation define the stock more than extreme saturation."},{"header":"Push/Pull","dek":"Best near box speed. It is a daylight consumer film that rewards plenty of light more than processing acrobatics."},{"header":"Shadow Detail","dek":"Modest but usable. It handles ordinary bright scenes well, though thin exposure makes shadows collapse quickly."},{"header":"Highlight Roll-off","dek":"Easygoing for consumer film. Highlights stay pleasant and help the stock keep its family-photo feel."}]'::jsonb,
  2,
  3,
  3,
  3,
  'Daylight-balanced with a warm, nostalgic consumer palette',
  'daylight',
  5500,
  TRUE,
  'c41',
  ARRAY['general_purpose', 'travel', 'bright_sun', 'golden_hour']::text[],
  TRUE,
  '/films/ferrania-solaris-fg-plus-100.jpg',
  1999,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- ferrania-solaris-fg-plus-200
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Ferrania Solaris FG Plus 200',
  'ferrania-solaris-fg-plus-200',
  (SELECT id FROM film_brands WHERE slug = 'ferrania'),
  ARRAY['35mm']::film_format[],
  'color_negative'::film_type,
  200,
  'Probably the best-known Solaris speed, FG Plus 200 sits in the sweet spot between daylight crispness and forgiving consumer negative latitude. It carries the same warm Ferrania character with a bit more versatility than the 100-speed version.',
  'The Solaris line was Ferrania''s mass-market color family through the late 1990s and 2000s, widely sold under Ferrania, store-brand, and rebadged packaging. It helped keep Italian-made consumer color film visible in supermarkets and camera shops long after premium slide film had become a niche.',
  '[{"header":"Skin Tones","dek":"Healthy and warm. It gives faces a cheerful snapshot look with enough softness to stay flattering."},{"header":"Color Bias","dek":"Warm and lightly punchy. The palette feels nostalgic without becoming overly stylized."},{"header":"Push/Pull","dek":"Flexible within consumer limits. It likes slight overexposure best, while pushes make the stock rougher rather than more sophisticated."},{"header":"Shadow Detail","dek":"Better than the slower Solaris stock. There is enough cushion for travel and street scenes in mixed daylight."},{"header":"Highlight Roll-off","dek":"Smooth enough to be forgiving. Bright areas stay manageable, which helps explain the stock''s broad appeal."}]'::jsonb,
  3,
  3,
  4,
  3,
  'Daylight-balanced with warm, nostalgic consumer color',
  'daylight',
  5500,
  TRUE,
  'c41',
  ARRAY['general_purpose', 'travel', 'street', 'golden_hour']::text[],
  TRUE,
  '/films/ferrania-solaris-fg-plus-200.jpg',
  1999,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- ferrania-solaris-fg-plus-400
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Ferrania Solaris FG Plus 400',
  'ferrania-solaris-fg-plus-400',
  (SELECT id FROM film_brands WHERE slug = 'ferrania'),
  ARRAY['35mm']::film_format[],
  'color_negative'::film_type,
  400,
  'The high-speed Solaris variant leans further into grain, contrast, and that rough-edged discount-store color look many photographers now seek on purpose. It is lo-fi in an appealing, fully analog way.',
  'The Solaris line was Ferrania''s mass-market color family through the late 1990s and 2000s, widely sold under Ferrania, store-brand, and rebadged packaging. It helped keep Italian-made consumer color film visible in supermarkets and camera shops long after premium slide film had become a niche.',
  '[{"header":"Skin Tones","dek":"Warm but less polished. Faces can look lively and nostalgic, though the faster emulsion brings more grain and bite."},{"header":"Color Bias","dek":"Bold, warm consumer color. It favors obvious reds and straightforward contrast over subtle shading."},{"header":"Push/Pull","dek":"Serviceable at higher ratings. It can be pushed in a pinch, but the film becomes grittier and less nuanced quickly."},{"header":"Shadow Detail","dek":"Fair for a consumer 400 stock. It keeps enough information for available-light shooting, though thin negatives go muddy."},{"header":"Highlight Roll-off","dek":"Still forgiving. Like many color negatives, bright areas remain easier to manage than the grainier body of the image suggests."}]'::jsonb,
  4,
  4,
  4,
  4,
  'Daylight-balanced with bold, warm consumer color',
  'daylight',
  5500,
  TRUE,
  'c41',
  ARRAY['general_purpose', 'travel', 'street', 'low_light']::text[],
  TRUE,
  '/films/ferrania-solaris-fg-plus-400.jpg',
  1999,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- fujifilm-astia-100f
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Fujichrome Astia 100F',
  'fujifilm-astia-100f',
  (SELECT id FROM film_brands WHERE slug = 'fujifilm'),
  ARRAY['35mm', '120', '4x5']::film_format[],
  'color_reversal'::film_type,
  100,
  'Fuji''s portrait-friendly slide film, prized for soft skin tones and restrained saturation compared with the more famous Provia and Velvia lines. Astia 100F offered one of the gentlest ways to shoot people on E-6.',
  'Astia evolved as Fujifilm''s softer professional transparency option and reached its mature form with Astia 100F in the early 2000s. It became a cult favorite among portrait and fashion photographers before Fujifilm discontinued it during the slide-film contraction.',
  '[{"header":"Skin Tones","dek":"Beautifully gentle for slide film. Faces stay luminous and flattering without the extra redness that can creep into more saturated emulsions."},{"header":"Color Bias","dek":"Soft, pastel, and polished. Astia keeps a refined palette that feels elegant rather than dramatic."},{"header":"Push/Pull","dek":"Best with precise box-speed exposure. Like most E-6 stocks, it prefers discipline over heavy processing tricks."},{"header":"Shadow Detail","dek":"Moderately narrow. It is kinder than Velvia in darker tones, but still unmistakably slide film."},{"header":"Highlight Roll-off","dek":"Smooth by transparency standards. Highlights stay attractive when metered carefully, especially for skin and fabric."}]'::jsonb,
  1,
  2,
  2,
  2,
  'Daylight-balanced with soft pastel slide-film color',
  'daylight',
  5500,
  TRUE,
  'e6',
  ARRAY['portrait', 'weddings', 'studio', 'golden_hour']::text[],
  TRUE,
  '/films/fujifilm-astia-100f.jpg',
  2001,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- fujifilm-fujicolor-100
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Fujicolor 100',
  'fujifilm-fujicolor-100',
  (SELECT id FROM film_brands WHERE slug = 'fujifilm'),
  ARRAY['35mm']::film_format[],
  'color_negative'::film_type,
  100,
  'A straightforward Fujifilm daylight consumer stock that favors clean blues, tidy grain, and simple, reliable color. It sits closer to neutral everyday film than the more stylized Superia family.',
  'Fujicolor 100 was part of Fujifilm''s late consumer-film simplification, giving many markets a plain-spoken daylight option after the richer Superia lineup began to narrow. It became a quiet but useful bridge between budget consumer film and the company''s more distinctive emulsions.',
  '[{"header":"Skin Tones","dek":"Clean and dependable. It keeps faces believable and avoids the exaggerated warmth or coolness that makes all-purpose stocks harder to place."},{"header":"Color Bias","dek":"Balanced with a house look. The palette has a recognizable signature, but it stays flexible enough for day-to-day shooting."},{"header":"Push/Pull","dek":"Usable within reason. It prefers box speed or a little extra light, while bigger rating changes trade away subtlety for speed."},{"header":"Shadow Detail","dek":"Good everyday retention. It keeps enough information in darker areas for mixed light and casual metering, but it still rewards generous exposure."},{"header":"Highlight Roll-off","dek":"Controlled and easy to scan. Bright areas stay smoother than slide film and keep the stock feeling practical rather than precious."}]'::jsonb,
  2,
  2,
  4,
  2,
  'Daylight-balanced with clean, restrained Fuji consumer color',
  'daylight',
  5500,
  TRUE,
  'c41',
  ARRAY['general_purpose', 'travel', 'bright_sun']::text[],
  TRUE,
  '/films/fujifilm-fujicolor-100.jpg',
  2011,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- fujifilm-pro-160ns
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Fujicolor Pro 160NS',
  'fujifilm-pro-160ns',
  (SELECT id FROM film_brands WHERE slug = 'fujifilm'),
  ARRAY['35mm', '120', '4x5']::film_format[],
  'color_negative'::film_type,
  160,
  'A portrait and wedding favorite that emphasized neutral skin, fine grain, and soft contrast over obvious color drama. Pro 160NS is one of the clearest expressions of Fuji''s calm, polished professional negative look.',
  'Pro 160NS emerged from Fujifilm''s professional portrait family after the earlier Pro 160S and 160C stocks. It became the neutral portrait option in the line, sitting beside the cooler Pro 400H and the faster Pro 800Z.',
  '[{"header":"Skin Tones","dek":"Smooth and understated. It was built for flattering portrait color without heavy warmth or candy-bright saturation."},{"header":"Color Bias","dek":"Neutral with a cool Fuji cleanliness. The palette is calm, tidy, and easy to shape in scanning or printing."},{"header":"Push/Pull","dek":"Best with slight overexposure. That keeps the stock creamy, while pushing works against its polished portrait strengths."},{"header":"Shadow Detail","dek":"Very good. It keeps delicate low-end separation in shade and controlled light."},{"header":"Highlight Roll-off","dek":"Soft and professional. Highlights compress gently, which made the film easy to trust for skin and white fabric."}]'::jsonb,
  2,
  2,
  5,
  2,
  'Daylight-balanced with neutral professional portrait color',
  'daylight',
  5500,
  TRUE,
  'c41',
  ARRAY['portrait', 'weddings', 'studio', 'golden_hour']::text[],
  TRUE,
  '/films/fujifilm-pro-160ns.jpg',
  2010,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- fujifilm-pro-400
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Fujicolor Pro 400',
  'fujifilm-pro-400',
  (SELECT id FROM film_brands WHERE slug = 'fujifilm'),
  ARRAY['35mm', '120']::film_format[],
  'color_negative'::film_type,
  400,
  'A professional Fuji color negative stock built for speed, cleaner grain than consumer 400 films, and a restrained palette that still held shape in mixed light. It sits historically between older pro emulsions and the later Pro 400H identity.',
  'Fujifilm''s Pro 400 labeling covered more than one generation of professional 400-speed negative film before the line consolidated around 400H. The stock represents Fuji''s long-running effort to offer a cooler, more neutral alternative to Kodak''s portrait-negative family.',
  '[{"header":"Skin Tones","dek":"Calm and believable. Faces stay cleaner and less amber than many consumer 400-speed films."},{"header":"Color Bias","dek":"Neutral with a subtle cool lean. It reads more professional and less nostalgic than budget color stocks."},{"header":"Push/Pull","dek":"Comfortable at speed. It can be pushed modestly, though slight overexposure keeps the palette more graceful."},{"header":"Shadow Detail","dek":"Strong enough for real work. It handles mixed and lower light better than slower portrait negatives."},{"header":"Highlight Roll-off","dek":"Smooth and forgiving. Bright areas compress well, which is part of the stock''s pro-negative appeal."}]'::jsonb,
  2,
  2,
  5,
  2,
  'Daylight-balanced with neutral professional color',
  'daylight',
  5500,
  TRUE,
  'c41',
  ARRAY['portrait', 'weddings', 'documentary', 'general_purpose']::text[],
  TRUE,
  '/films/fujifilm-pro-400.jpg',
  2004,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- fujifilm-pro-800z
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Fujicolor Pro 800Z',
  'fujifilm-pro-800z',
  (SELECT id FROM film_brands WHERE slug = 'fujifilm'),
  ARRAY['35mm', '120']::film_format[],
  'color_negative'::film_type,
  800,
  'A premium high-speed portrait negative film that kept Fuji''s polished color style while extending into wedding-reception and available-light territory. Pro 800Z made speed feel elegant instead of merely convenient.',
  'Fuji positioned Pro 800Z as the fastest member of its professional portrait line, built for mixed light, event work, and handheld medium format. It became especially loved by wedding photographers before Fujifilm trimmed the range.',
  '[{"header":"Skin Tones","dek":"Warm enough to flatter, clean enough to stay professional. It handles event portraits with less chaos than most 800-speed color films."},{"header":"Color Bias","dek":"Balanced with gentle warmth. The palette feels polished rather than aggressively consumer-bright."},{"header":"Push/Pull","dek":"Very capable. It can stretch upward when needed, though box speed already covers a lot of low-light ground."},{"header":"Shadow Detail","dek":"Excellent for its speed. Dark areas keep more information than most 800-speed color stocks."},{"header":"Highlight Roll-off","dek":"Smooth and resilient. Bright dresses, windows, and practical lights stay easier to tame than expected."}]'::jsonb,
  3,
  2,
  5,
  3,
  'Daylight-balanced with polished high-speed portrait color',
  'daylight',
  5500,
  TRUE,
  'c41',
  ARRAY['portrait', 'weddings', 'low_light', 'artificial_light']::text[],
  TRUE,
  '/films/fujifilm-pro-800z.jpg',
  2005,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- fujifilm-provia-400x
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Provia 400X',
  'fujifilm-provia-400x',
  (SELECT id FROM film_brands WHERE slug = 'fujifilm'),
  ARRAY['35mm', '120']::film_format[],
  'color_reversal'::film_type,
  400,
  'A rare fast slide film that delivered real 400-speed practicality without giving up Fuji''s crisp E-6 color. Provia 400X offered unusually flexible transparency shooting for travel, action, and dimmer outdoor light.',
  'Fujifilm launched Provia 400X as the high-speed member of the Provia family, keeping a more neutral palette than Velvia while giving slide shooters far more speed than traditional 100-speed E-6. It remains one of the most fondly remembered fast slide films ever made.',
  '[{"header":"Skin Tones","dek":"Clean but exacting. Faces can look excellent, though slide-film exposure discipline matters far more than with negative stock."},{"header":"Color Bias","dek":"Neutral to gently vivid. The palette stays polished and crisp without pushing every hue toward maximum drama."},{"header":"Push/Pull","dek":"Moderately adaptable for E-6. A careful push can work, but the film is best when exposure is deliberate and processing stays predictable."},{"header":"Shadow Detail","dek":"Tighter than negative film. Dark areas need care, though the stock holds together better than the most contrasty slide emulsions."},{"header":"Highlight Roll-off","dek":"Precise rather than forgiving. Highlights reward careful metering and good scene control, especially in bright sun."}]'::jsonb,
  2,
  4,
  2,
  4,
  'Daylight-balanced with crisp, fast slide-film color',
  'daylight',
  5500,
  TRUE,
  'e6',
  ARRAY['travel', 'landscapes', 'bright_sun', 'sports']::text[],
  TRUE,
  '/films/fujifilm-provia-400x.jpg',
  2006,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- fujifilm-reala-ace-100
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Reala Ace 100',
  'fujifilm-reala-ace-100',
  (SELECT id FROM film_brands WHERE slug = 'fujifilm'),
  ARRAY['35mm', '120']::film_format[],
  'color_negative'::film_type,
  100,
  'A current Fujifilm color negative stock aimed at photographers who want clean contrast, refined color separation, and a more premium feel than basic consumer film. Reala Ace 100 emphasizes clarity and polish over nostalgic softness.',
  'Reala Ace returned the Reala name to current Fujifilm use after years of absence, first drawing attention through the company''s digital film simulation and then through limited-market still-film availability. It sits as a modern, premium-leaning daylight negative rather than a retro reissue.',
  '[{"header":"Skin Tones","dek":"Clean and controlled. Faces stay believable and slightly refined rather than overtly warm."},{"header":"Color Bias","dek":"Neutral with crisp Fuji separation. Greens and blues stay clear, while warm tones do not overwhelm the frame."},{"header":"Push/Pull","dek":"Best near box speed. It is designed around clean daylight performance rather than heavy rating changes."},{"header":"Shadow Detail","dek":"Very good. The negative holds enough information to stay flexible in scanning without becoming flat."},{"header":"Highlight Roll-off","dek":"Smooth and modern. Highlights keep shape well, which helps the stock feel premium and tidy."}]'::jsonb,
  2,
  3,
  4,
  3,
  'Daylight-balanced with modern, premium Fuji color',
  'daylight',
  5500,
  TRUE,
  'c41',
  ARRAY['general_purpose', 'travel', 'portrait', 'bright_sun']::text[],
  FALSE,
  '/films/fujifilm-reala-ace-100.jpg',
  2024,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- fujifilm-superia-200
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Superia 200',
  'fujifilm-superia-200',
  (SELECT id FROM film_brands WHERE slug = 'fujifilm'),
  ARRAY['35mm']::film_format[],
  'color_negative'::film_type,
  200,
  'A mid-speed Fuji consumer film with brighter color than C200 and a more familiar Superia bite in greens and blues. It sits in the sweet spot for travel and daylight point-and-shoot use.',
  'Superia 200 was part of the broad Superia consumer family that carried Fujifilm through the 1990s and 2000s. It gave photographers a cleaner, slightly punchier alternative to the cheaper C200-style end of the lineup.',
  '[{"header":"Skin Tones","dek":"Fresh but slightly cool. Faces can look lively, though not as creamy as portrait-focused films."},{"header":"Color Bias","dek":"Classic Fuji consumer balance. Greens and blues come forward a bit more than warm Kodak-style films."},{"header":"Push/Pull","dek":"Best with a little extra light. Overexposure smooths it out, while pushing mostly adds coarseness."},{"header":"Shadow Detail","dek":"Good in everyday scenes. It has enough negative-film forgiveness for travel and casual metering."},{"header":"Highlight Roll-off","dek":"Friendly and usable. Bright daylight stays manageable without the exactness of slide film."}]'::jsonb,
  2,
  3,
  4,
  3,
  'Daylight-balanced with crisp Fuji consumer color',
  'daylight',
  5500,
  TRUE,
  'c41',
  ARRAY['general_purpose', 'travel', 'street', 'bright_sun']::text[],
  TRUE,
  '/films/fujifilm-superia-200.jpg',
  2003,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- fujifilm-superia-800
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Superia 800',
  'fujifilm-superia-800',
  (SELECT id FROM film_brands WHERE slug = 'fujifilm'),
  ARRAY['35mm']::film_format[],
  'color_negative'::film_type,
  800,
  'A high-speed consumer color film that combined Fuji''s recognizable cool-leaning palette with genuinely useful low-light flexibility. Superia 800 brought faster everyday shooting to compact cameras and casual event work.',
  'Superia 800 sat near the top of Fuji''s consumer line as a practical fast film for travel, family events, and flash-free interiors. It faded away as the company narrowed its catalog, but it remains a reference point for affordable high-speed color.',
  '[{"header":"Skin Tones","dek":"Lively and a little cool. Faces stay usable, though the consumer palette is less gentle than Fuji''s pro line."},{"header":"Color Bias","dek":"Cool and punchy. Greens, blues, and mixed-light scenes carry that recognizable Superia edge."},{"header":"Push/Pull","dek":"Naturally at home in low light. It can stretch, but its main strength is already starting at 800."},{"header":"Shadow Detail","dek":"Strong for a consumer-speed film. It keeps more useful information than slower films forced upward."},{"header":"Highlight Roll-off","dek":"Decent and manageable. Highlights do not have pro-film elegance, but they stay workable."}]'::jsonb,
  3,
  3,
  4,
  3,
  'Daylight-balanced with cool, punchy high-speed Fuji color',
  'daylight',
  5500,
  TRUE,
  'c41',
  ARRAY['low_light', 'street', 'travel', 'general_purpose']::text[],
  TRUE,
  '/films/fujifilm-superia-800.jpg',
  1999,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- fujifilm-superia-reala-100
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Superia Reala 100',
  'fujifilm-superia-reala-100',
  (SELECT id FROM film_brands WHERE slug = 'fujifilm'),
  ARRAY['35mm', '120']::film_format[],
  'color_negative'::film_type,
  100,
  'A premium Fuji daylight negative that mixed consumer friendliness with more sophisticated color and better skin rendering than basic Superia. It is often remembered as one of Fuji''s most balanced color negatives.',
  'Superia Reala 100 continued the Reala idea of wide color separation and refined skin tones within Fujifilm''s color-negative family. It bridged the gap between mass-market Superia stocks and the company''s more explicitly professional portrait films.',
  '[{"header":"Skin Tones","dek":"Smooth and flattering. It gives faces a cleaner, more refined look than ordinary consumer Fuji film."},{"header":"Color Bias","dek":"Balanced with subtle Fuji coolness. Colors stay rich without feeling overcooked."},{"header":"Push/Pull","dek":"Best at box or slightly over. Its strengths show up in careful daylight use rather than pushed speed."},{"header":"Shadow Detail","dek":"Very solid. It keeps a surprising amount of low-end information for a 100-speed film."},{"header":"Highlight Roll-off","dek":"Controlled and elegant. Highlights stay smoother than you expect from a daylight consumer-adjacent stock."}]'::jsonb,
  1,
  3,
  4,
  3,
  'Daylight-balanced with refined Fuji daylight color',
  'daylight',
  5500,
  TRUE,
  'c41',
  ARRAY['portrait', 'travel', 'general_purpose', 'bright_sun']::text[],
  TRUE,
  '/films/fujifilm-superia-reala-100.jpg',
  2004,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- fujifilm-velvia-100f
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Velvia 100F',
  'fujifilm-velvia-100f',
  (SELECT id FROM film_brands WHERE slug = 'fujifilm'),
  ARRAY['35mm', '120', '4x5']::film_format[],
  'color_reversal'::film_type,
  100,
  'A more restrained branch of the Velvia family, balancing fine grain and saturated slide-film clarity with noticeably less aggression than Velvia 50 or Velvia 100. It is the Velvia name for photographers who still wanted some subtlety.',
  'Fujifilm introduced Velvia 100F as a gentler, more neutral-minded extension of the Velvia brand before later consolidating around the punchier Velvia 100. It became a favorite among photographers who liked slide-film crispness but found classic Velvia too intense.',
  '[{"header":"Skin Tones","dek":"Clean but exacting. Faces can look excellent, though slide-film exposure discipline matters far more than with negative stock."},{"header":"Color Bias","dek":"Neutral to gently vivid. The palette stays polished and crisp without pushing every hue toward maximum drama."},{"header":"Push/Pull","dek":"Moderately adaptable for E-6. A careful push can work, but the film is best when exposure is deliberate and processing stays predictable."},{"header":"Shadow Detail","dek":"Tighter than negative film. Dark areas need care, though the stock holds together better than the most contrasty slide emulsions."},{"header":"Highlight Roll-off","dek":"Precise rather than forgiving. Highlights reward careful metering and good scene control, especially in bright sun."}]'::jsonb,
  1,
  4,
  2,
  3,
  'Daylight-balanced with polished, less aggressive Velvia color',
  'daylight',
  5500,
  TRUE,
  'e6',
  ARRAY['landscapes', 'travel', 'architecture', 'bright_sun']::text[],
  TRUE,
  '/films/fujifilm-velvia-100f.jpg',
  2002,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- kodak-ektachrome-e100g
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Kodak Ektachrome E100G',
  'kodak-ektachrome-e100g',
  (SELECT id FROM film_brands WHERE slug = 'kodak'),
  ARRAY['35mm', '120', '4x5']::film_format[],
  'color_reversal'::film_type,
  100,
  'A neutral professional Ektachrome designed for accurate color, fine grain, and a cooler, cleaner alternative to warmer or more saturated slide stocks. E100G is the restrained side of Kodak''s modern-era transparency family.',
  'Kodak positioned E100G as the general-purpose professional option within the E100 generation, with the ''G'' emphasizing more neutral color than the vivid VS variant. It became a standard choice for editorial, travel, and commercial work that wanted slide precision without theatrical saturation.',
  '[{"header":"Skin Tones","dek":"Clean but exacting. Faces can look excellent, though slide-film exposure discipline matters far more than with negative stock."},{"header":"Color Bias","dek":"Neutral to gently vivid. The palette stays polished and crisp without pushing every hue toward maximum drama."},{"header":"Push/Pull","dek":"Moderately adaptable for E-6. A careful push can work, but the film is best when exposure is deliberate and processing stays predictable."},{"header":"Shadow Detail","dek":"Tighter than negative film. Dark areas need care, though the stock holds together better than the most contrasty slide emulsions."},{"header":"Highlight Roll-off","dek":"Precise rather than forgiving. Highlights reward careful metering and good scene control, especially in bright sun."}]'::jsonb,
  1,
  4,
  2,
  3,
  'Daylight-balanced with neutral, editorial Ektachrome color',
  'daylight',
  5500,
  TRUE,
  'e6',
  ARRAY['landscapes', 'travel', 'portrait', 'architecture']::text[],
  TRUE,
  '/films/kodak-ektachrome-e100g.jpg',
  2004,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- kodak-ektachrome-e100vs
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Kodak Ektachrome E100VS',
  'kodak-ektachrome-e100vs',
  (SELECT id FROM film_brands WHERE slug = 'kodak'),
  ARRAY['35mm', '120', '4x5']::film_format[],
  'color_reversal'::film_type,
  100,
  'The vivid member of Kodak''s E100 family, designed for photographers who wanted transparency-film sharpness with a more dramatic palette than neutral Ektachrome. E100VS pushes color harder without becoming full Velvia territory.',
  'Kodak introduced E100VS as a higher-saturation professional alternative within the E100 line, giving travel and nature shooters a more intense option while keeping Ektachrome''s overall clarity and grain structure. It was especially popular among photographers who liked bold slide color but not Fuji''s exact flavor.',
  '[{"header":"Skin Tones","dek":"Bold rather than forgiving. Faces can look striking, but the extra saturation needs careful scene choice."},{"header":"Color Bias","dek":"Rich and vivid. Reds, blues, and warm light all come forward more aggressively than on neutral Ektachrome."},{"header":"Push/Pull","dek":"Limited in the usual E-6 way. It is best used for its native look rather than aggressive processing shifts."},{"header":"Shadow Detail","dek":"Typical slide-film discipline. Dark values need accurate placement and do not tolerate casual underexposure."},{"header":"Highlight Roll-off","dek":"Precise and unforgiving. Highlights stay beautiful when metered carefully but offer little rescue room."}]'::jsonb,
  1,
  4,
  2,
  4,
  'Daylight-balanced with vivid professional Ektachrome color',
  'daylight',
  5500,
  TRUE,
  'e6',
  ARRAY['landscapes', 'travel', 'bright_sun', 'experimental']::text[],
  TRUE,
  '/films/kodak-ektachrome-e100vs.jpg',
  2002,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- kodak-kodachrome-25
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Kodachrome 25',
  'kodak-kodachrome-25',
  (SELECT id FROM film_brands WHERE slug = 'kodak'),
  ARRAY['35mm']::film_format[],
  'color_reversal'::film_type,
  25,
  'The slowest and finest-grained Kodachrome variant, famous for extraordinary sharpness, stable archival color, and a disciplined, luminous slide look. Kodachrome 25 rewards careful daylight work with a level of delicacy few transparency films ever matched.',
  'Kodachrome defined the premium slide-film ideal for decades, combining very fine grain with a distinctive archival palette and the famously complex K-14 process. Each speed had its own following, but all three variants became touchstones for editorial, travel, and documentary color before the line finally disappeared.',
  '[{"header":"Skin Tones","dek":"Natural and beautifully detailed. Faces can look superb when the light suits the film and exposure is exact."},{"header":"Color Bias","dek":"Rich but disciplined. Colors feel deep and archival rather than exaggerated or neon-bright."},{"header":"Push/Pull","dek":"Tied to the K-14 world. The stock was never about flexible home-style experimentation; it asked for precision from start to finish."},{"header":"Shadow Detail","dek":"Moderate and placement-sensitive. Kodachrome likes careful metering in contrasty scenes."},{"header":"Highlight Roll-off","dek":"Elegant but exacting. Highlights stay gorgeous when controlled, with none of negative film''s rescue margin."}]'::jsonb,
  1,
  4,
  2,
  3,
  'Daylight-balanced with deep, archival Kodachrome color',
  'daylight',
  5500,
  TRUE,
  'e6',
  ARRAY['travel', 'portrait', 'bright_sun', 'documentary']::text[],
  TRUE,
  '/films/kodak-kodachrome-25.jpg',
  1961,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- kodak-kodachrome-64
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Kodachrome 64',
  'kodak-kodachrome-64',
  (SELECT id FROM film_brands WHERE slug = 'kodak'),
  ARRAY['35mm', '120']::film_format[],
  'color_reversal'::film_type,
  64,
  'The most iconic Kodachrome speed, balancing practical daylight usability with the line''s famous color and fine grain. Kodachrome 64 became synonymous with editorial travel photography for a reason.',
  'Kodachrome defined the premium slide-film ideal for decades, combining very fine grain with a distinctive archival palette and the famously complex K-14 process. Each speed had its own following, but all three variants became touchstones for editorial, travel, and documentary color before the line finally disappeared.',
  '[{"header":"Skin Tones","dek":"Natural and memorable. It gave portraits a believable, documentary warmth without cheapening the palette."},{"header":"Color Bias","dek":"Deep, rich, and unmistakably Kodachrome. The color feels dense and stable rather than merely saturated."},{"header":"Push/Pull","dek":"A precision transparency stock. Flexibility was never the point; consistent processing and accurate exposure were."},{"header":"Shadow Detail","dek":"Good for slide film when exposed carefully. It is more practical than the 25-speed version but still not forgiving."},{"header":"Highlight Roll-off","dek":"Controlled and exact. Highlights can be beautiful, though they demand respect in bright conditions."}]'::jsonb,
  1,
  4,
  2,
  3,
  'Daylight-balanced with rich, iconic Kodachrome color',
  'daylight',
  5500,
  TRUE,
  'e6',
  ARRAY['travel', 'documentary', 'portrait', 'bright_sun']::text[],
  TRUE,
  '/films/kodak-kodachrome-64.jpg',
  1974,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- kodak-kodachrome-200
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Kodachrome 200',
  'kodak-kodachrome-200',
  (SELECT id FROM film_brands WHERE slug = 'kodak'),
  ARRAY['35mm']::film_format[],
  'color_reversal'::film_type,
  200,
  'The fastest Kodachrome, built to make the line more practical for lower light and faster work while keeping its recognizable palette. It gave up some refinement compared with K25 and K64, but it brought Kodachrome into more demanding shooting situations.',
  'Kodachrome defined the premium slide-film ideal for decades, combining very fine grain with a distinctive archival palette and the famously complex K-14 process. Each speed had its own following, but all three variants became touchstones for editorial, travel, and documentary color before the line finally disappeared.',
  '[{"header":"Skin Tones","dek":"Believable but less delicate than the slower Kodachromes. The higher speed brings a slightly rougher transparency feel."},{"header":"Color Bias","dek":"Still recognizably Kodachrome. The palette stays rich and deep, just with a touch less refinement."},{"header":"Push/Pull","dek":"Designed to be the practical Kodachrome. Even so, it remained a film that wanted accurate exposure and disciplined processing."},{"header":"Shadow Detail","dek":"Useful for its class. The extra speed makes darker scenes more manageable than the slower Kodachromes."},{"header":"Highlight Roll-off","dek":"Still a slide-film shoulder. Highlights stay attractive when placed carefully, but tolerance remains limited."}]'::jsonb,
  2,
  4,
  2,
  3,
  'Daylight-balanced with fast, rich Kodachrome color',
  'daylight',
  5500,
  TRUE,
  'e6',
  ARRAY['travel', 'documentary', 'low_light', 'bright_sun']::text[],
  TRUE,
  '/films/kodak-kodachrome-200.jpg',
  1986,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- kodak-vision3-50d
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Kodak Vision3 50D',
  'kodak-vision3-50d',
  (SELECT id FROM film_brands WHERE slug = 'kodak'),
  ARRAY['35mm']::film_format[],
  'color_negative'::film_type,
  50,
  'A daylight-balanced motion-picture stock with extremely fine grain, long highlight handling, and that polished cinema-negative feel still photographers love in respooled form. 50D is the cleanest and brightest member of the Vision3 family.',
  'Kodak''s Vision3 family was developed for modern motion-picture production, with improved highlight handling, cleaner shadows, and scanning latitude compared with older cinema stocks. Still photographers usually encounter it as respooled stock, where its ECN-2 roots and remjet layer are part of the appeal.',
  '[{"header":"Skin Tones","dek":"Clean and cinematic. Faces stay natural, with a polished negative look rather than consumer warmth."},{"header":"Color Bias","dek":"Balanced daylight color. It feels neutral and modern, with enough shape to scan beautifully."},{"header":"Push/Pull","dek":"Best at intended speed or with slight overexposure. Still-photography users usually lean into its latitude more than big rating changes."},{"header":"Shadow Detail","dek":"Excellent. Dark areas stay remarkably open when processed and scanned well."},{"header":"Highlight Roll-off","dek":"A major strength. Bright values compress with the soft, expensive feel people associate with cinema stock."}]'::jsonb,
  1,
  2,
  5,
  2,
  'Daylight-balanced cinema negative with long highlight latitude',
  'daylight',
  5500,
  FALSE,
  'ecn2',
  ARRAY['landscapes', 'portrait', 'bright_sun', 'architecture']::text[],
  FALSE,
  '/films/kodak-vision3-50d.jpg',
  2007,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- kodak-vision3-250d
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Kodak Vision3 250D',
  'kodak-vision3-250d',
  (SELECT id FROM film_brands WHERE slug = 'kodak'),
  ARRAY['35mm']::film_format[],
  'color_negative'::film_type,
  250,
  'The versatile middle-speed Vision3 stock, balancing cinema-grade latitude with far more practical speed than 50D. It is one of the most adaptable daylight motion stocks for still-photography respooling.',
  'Kodak''s Vision3 family was developed for modern motion-picture production, with improved highlight handling, cleaner shadows, and scanning latitude compared with older cinema stocks. Still photographers usually encounter it as respooled stock, where its ECN-2 roots and remjet layer are part of the appeal.',
  '[{"header":"Skin Tones","dek":"Natural and polished. It gives faces a clean cinema-negative feel without obvious consumer-film bias."},{"header":"Color Bias","dek":"Balanced daylight color with modern restraint. It scans into either neutral or richer looks with ease."},{"header":"Push/Pull","dek":"Very usable. It can be pushed or overexposed according to the workflow, which is part of its popularity with still shooters."},{"header":"Shadow Detail","dek":"Excellent. It holds plenty of low-end information for mixed daylight and interiors with windows."},{"header":"Highlight Roll-off","dek":"Extremely smooth. Highlights stay one of the stock''s defining strengths."}]'::jsonb,
  2,
  2,
  5,
  2,
  'Daylight-balanced cinema negative with wide scanning latitude',
  'daylight',
  5500,
  FALSE,
  'ecn2',
  ARRAY['general_purpose', 'travel', 'portrait', 'documentary']::text[],
  FALSE,
  '/films/kodak-vision3-250d.jpg',
  2007,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- kodak-vision3-500t
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Kodak Vision3 500T',
  'kodak-vision3-500t',
  (SELECT id FROM film_brands WHERE slug = 'kodak'),
  ARRAY['35mm']::film_format[],
  'color_negative'::film_type,
  500,
  'A tungsten-balanced cinema stock that has become one of the most sought-after motion-derived choices for still photographers. 500T is loved for low-light flexibility, halation when remjet is removed, and deep cinematic color under practical light.',
  'Kodak''s Vision3 family was developed for modern motion-picture production, with improved highlight handling, cleaner shadows, and scanning latitude compared with older cinema stocks. Still photographers usually encounter it as respooled stock, where its ECN-2 roots and remjet layer are part of the appeal.',
  '[{"header":"Skin Tones","dek":"Natural under tungsten and moody in mixed light. Faces can look strikingly cinematic when the stock is used for the environments it was built for."},{"header":"Color Bias","dek":"Tungsten-balanced by design. Warm practicals look correct, while daylight without filtration turns cool and stylized."},{"header":"Push/Pull","dek":"Very capable. It is already fast, and users often lean on pushes or scanner latitude in darker conditions."},{"header":"Shadow Detail","dek":"Excellent for a fast color stock. It retains a lot of information in low-light scenes."},{"header":"Highlight Roll-off","dek":"Cinema-soft and forgiving. Bright lamps and signage stay smoother than most still films allow."}]'::jsonb,
  3,
  2,
  5,
  2,
  'Tungsten-balanced cinema negative with strong low-light latitude',
  'tungsten',
  3200,
  FALSE,
  'ecn2',
  ARRAY['low_light', 'artificial_light', 'street', 'documentary']::text[],
  FALSE,
  '/films/kodak-vision3-500t.jpg',
  2007,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- lucky-c200
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Lucky C200',
  'lucky-c200',
  (SELECT id FROM film_brands WHERE slug = 'lucky'),
  ARRAY['35mm']::film_format[],
  'color_negative'::film_type,
  200,
  'Lucky''s return to color negative film, offering a fresh consumer-stock option from a manufacturer long absent from the color market. C200 is notable as much for its existence as for its character: a warm, slightly rough-edged daylight film with clear snapshot energy.',
  'Lucky re-entered the color market in 2025 after years focused away from consumer color still film, making C200 a significant launch for photographers eager to see new emulsions rather than only rebrands and discontinuations. Early coverage positioned it as the beginning of a broader Lucky color revival.',
  '[{"header":"Skin Tones","dek":"Warm and direct. Faces have a sunny, consumer-film feel rather than a refined portrait palette."},{"header":"Color Bias","dek":"Slightly warm and nostalgic. It leans into straightforward color rather than polished neutrality."},{"header":"Push/Pull","dek":"Best used simply. Box speed or a touch of overexposure keeps the stock feeling open and friendly."},{"header":"Shadow Detail","dek":"Fair to good. It works best with enough daylight and does not love thin exposure."},{"header":"Highlight Roll-off","dek":"Pleasantly forgiving. Bright scenes hold together in the easy way people expect from C-41 consumer film."}]'::jsonb,
  3,
  3,
  4,
  3,
  'Daylight-balanced with warm, newly revived Lucky consumer color',
  'daylight',
  5500,
  TRUE,
  'c41',
  ARRAY['general_purpose', 'travel', 'bright_sun', 'golden_hour']::text[],
  FALSE,
  '/films/lucky-c200.jpg',
  2025,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- orwo-wolfen-nc400
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'WOLFEN NC400',
  'orwo-wolfen-nc400',
  (SELECT id FROM film_brands WHERE slug = 'orwo'),
  ARRAY['35mm']::film_format[],
  'color_negative'::film_type,
  400,
  'A modern ORWO still-film stock with visible grain, muted color, and a deliberately less polished look than mainstream C-41 options. NC400 stands out for its dry, cinematic palette and refusal to mimic Kodak or Fuji directly.',
  'WOLFEN NC400 followed the relaunch of ORWO-branded color still film and helped define the company''s new identity in the analog market. Rather than chasing clean consumer color, it embraced a moodier, lower-saturation aesthetic rooted in the Wolfen name.',
  '[{"header":"Skin Tones","dek":"Subdued and slightly cool. Faces feel more cinematic and moody than creamy or conventionally flattering."},{"header":"Color Bias","dek":"Muted with a dry, modern-retro cast. Colors stay restrained instead of glossy."},{"header":"Push/Pull","dek":"Better treated gently. It likes careful metering and enough exposure more than aggressive speed chasing."},{"header":"Shadow Detail","dek":"Moderate. Shadows can go dense fast, especially if the stock is underexposed."},{"header":"Highlight Roll-off","dek":"Reasonably soft. Highlights help keep the stock''s moody look from turning completely harsh."}]'::jsonb,
  4,
  3,
  3,
  2,
  'Daylight-balanced with muted, cinematic ORWO color',
  'daylight',
  5500,
  TRUE,
  'c41',
  ARRAY['street', 'documentary', 'travel', 'experimental']::text[],
  FALSE,
  '/films/orwo-wolfen-nc400.jpg',
  2024,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- rollei-crossbird-200
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Rollei Crossbird 200',
  'rollei-crossbird-200',
  (SELECT id FROM film_brands WHERE slug = 'rollei'),
  ARRAY['35mm', '120']::film_format[],
  'color_reversal'::film_type,
  200,
  'A slide film explicitly marketed with cross-processing in mind, blending conventional reversal clarity with a more playful, stylized identity than standard E-6 stocks. Crossbird 200 sits at the boundary between normal color and effect film.',
  'Rollei introduced Crossbird to serve photographers who wanted a transparency stock that welcomed experimental C-41 cross-processing rather than merely tolerating it. It became one of the more memorable specialty slide films of the boutique-film era.',
  '[{"header":"Skin Tones","dek":"Variable by workflow. In standard E-6 it is lively and contrasty; cross-processed, it becomes far more stylized."},{"header":"Color Bias","dek":"Built for drama. Even before cross-processing, the palette feels punchy and a little less neutral than mainstream slide films."},{"header":"Push/Pull","dek":"Best used creatively rather than technically. The fun lies more in process choice than careful rating shifts."},{"header":"Shadow Detail","dek":"Typical slide-film limits. Dark tones need care, especially if the photographer is also aiming for effect-driven processing."},{"header":"Highlight Roll-off","dek":"Bright and exact. Highlights reward careful metering, then get even wilder if the film is cross-processed."}]'::jsonb,
  2,
  4,
  2,
  4,
  'Daylight-balanced slide film designed to shine in cross-processing',
  'daylight',
  5500,
  TRUE,
  'e6',
  ARRAY['travel', 'experimental', 'bright_sun', 'landscapes']::text[],
  TRUE,
  '/films/rollei-crossbird-200.jpg',
  2010,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();
