-- Insert/update missing black-and-white stocks with metadata, scales, and shooting notes.

-- Scope: adox-chs-25-ii, adox-scala-50, adox-scala-160, agfa-apx-25, agfa-scala-200x, ferrania-ortho, fujifilm-neopan-400, fujifilm-neopan-1600, kentmere-pan-200, kodak-bw400cn, kodak-plus-x-pan-125, kodak-tri-x-professional-320, kosmo-foto-agent-shadow-400, lucky-shd-100, lucky-shd-400, orwo-un54, rollei-atp-1-1, rollei-ortho-25-plus, street-candy-atm-400

-- Note schema: Tonal Range, Push/Pull, Shadow Detail, Highlight Roll-off



-- Ensure supporting brands exist.

INSERT INTO film_brands (name, slug, description, website_url, featured)
VALUES (
  'Lucky',
  'lucky',
  'Lucky Film is a long-running Chinese photographic manufacturer with roots in state-backed industrial film production. The brand became internationally known for affordable black-and-white films and has recently re-entered the color market, making it one of the few companies reviving rather than shrinking a film lineup.',
  'https://luckyfilm.net/',
  NULL
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  website_url = EXCLUDED.website_url,
  featured = EXCLUDED.featured,
  updated_at = now();



-- adox-chs-25-ii
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'ADOX CHS 25 II',
  'adox-chs-25-ii',
  (SELECT id FROM film_brands WHERE slug = 'adox'),
  ARRAY['35mm', '120', '4x5', '8x10']::film_format[],
  'bw_negative'::film_type,
  25,
  'An ultra-slow black-and-white film built for photographers who want classic tonality with maximum resolving power. CHS 25 II favors deliberate daylight work, large prints, and scenes where a calm tonal curve matters more than speed.',
  'ADOX revived the CHS line as a modern continuation of one of the oldest film names in photography. CHS 25 II extends that project into the slow-speed end of the range, pairing vintage-style rendering with contemporary coating quality.',
  '[{"header":"Tonal Range","dek":"Classic and gently rounded. It has a vintage-style grayscale with smooth mids instead of a technical or clinical feel."},{"header":"Push/Pull","dek":"Built for careful exposure. It is happiest at box speed or with a little extra light rather than any attempt to chase speed."},{"header":"Shadow Detail","dek":"Strong when exposed generously. Low values stay elegant and readable, but this is not a film that rescues rushed metering."},{"header":"Highlight Roll-off","dek":"Graceful and refined. Bright tones taper smoothly, which suits architecture, portraiture, and sunlit landscapes."}]'::jsonb,
  1,
  2,
  3,
  NULL,
  'Orthopanchromatic-style monochrome with a classic silver scale',
  NULL,
  NULL,
  TRUE,
  'bw',
  ARRAY['landscapes', 'architecture', 'studio', 'bright_sun']::text[],
  FALSE,
  '/films/adox-chs-25-ii.jpg',
  2025,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- adox-scala-50
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'ADOX SCALA 50',
  'adox-scala-50',
  (SELECT id FROM film_brands WHERE slug = 'adox'),
  ARRAY['35mm']::film_format[],
  'bw_reversal'::film_type,
  50,
  'A modern black-and-white reversal film made for projection, direct positives, and a uniquely luminous monochrome slide look. SCALA 50 is slow, sharp, and exacting in the way only black-and-white transparency film can be.',
  'After Agfa''s original SCALA disappeared, ADOX revived the concept for photographers who still wanted true black-and-white slides. SCALA 50 became the low-speed, high-precision option in that revival.',
  '[{"header":"Tonal Range","dek":"Bright and tightly controlled. It has the snap and clarity of monochrome transparency rather than the long cushion of negative film."},{"header":"Push/Pull","dek":"Best at box. Reversal processing leaves little room for casual rating changes, so it rewards disciplined metering more than experimentation."},{"header":"Shadow Detail","dek":"Narrow and exposure dependent. Dark tones fall away quickly if the film is starved for light."},{"header":"Highlight Roll-off","dek":"Brisk but luminous. Highlights stay beautiful when placed carefully, but overexposure shows up immediately."}]'::jsonb,
  1,
  4,
  1,
  NULL,
  'Black-and-white reversal transparency rendering',
  NULL,
  NULL,
  TRUE,
  'bw',
  ARRAY['architecture', 'studio', 'bright_sun', 'experimental']::text[],
  FALSE,
  '/films/adox-scala-50.jpg',
  2019,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- adox-scala-160
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'ADOX SCALA 160',
  'adox-scala-160',
  (SELECT id FROM film_brands WHERE slug = 'adox'),
  ARRAY['35mm']::film_format[],
  'bw_reversal'::film_type,
  160,
  'The faster member of the ADOX reversal pair, SCALA 160 trades a little refinement for much more practical handheld speed. It keeps the direct, projected look of monochrome slides while making real-world shooting easier.',
  'ADOX reintroduced SCALA 160 in the mid-2010s as a contemporary answer to photographers who missed Agfa''s historic reversal line. It remains one of the few readily available black-and-white reversal options for still photographers.',
  '[{"header":"Tonal Range","dek":"Direct and contrasty. It has more bite than slow monochrome negatives and carries the immediate transparency look well."},{"header":"Push/Pull","dek":"Limited but serviceable. Small rating changes are possible, though the film''s real strength is dependable reversal performance at its intended speed."},{"header":"Shadow Detail","dek":"Moderate for reversal film. It handles everyday scenes better than slower slide emulsions, but shadows still need respect."},{"header":"Highlight Roll-off","dek":"Clean and fairly abrupt. Highlights look crisp and luminous when exposure is right, without the softness of negative film."}]'::jsonb,
  2,
  4,
  2,
  NULL,
  'Black-and-white reversal transparency rendering',
  NULL,
  NULL,
  TRUE,
  'bw',
  ARRAY['street', 'documentary', 'bright_sun', 'experimental']::text[],
  FALSE,
  '/films/adox-scala-160.jpg',
  2016,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- agfa-apx-25
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Agfa APX 25',
  'agfa-apx-25',
  (SELECT id FROM film_brands WHERE slug = 'agfa'),
  ARRAY['35mm', '120']::film_format[],
  'bw_negative'::film_type,
  25,
  'A discontinued ultra-fine-grain Agfa stock that paired very high sharpness with a restrained, elegant monochrome curve. APX 25 became a favorite for tripod work, architecture, and bright outdoor scenes where detail mattered most.',
  'APX 25 sat at the precision end of Agfa''s black-and-white lineup during the 1990s and early 2000s. It disappeared as the analog market contracted, but it remains one of the better-remembered slow conventional films of its era.',
  '[{"header":"Tonal Range","dek":"Clean and classic. It gives a refined grayscale with less romantic softness than older emulsions and more warmth than technical microfilm."},{"header":"Push/Pull","dek":"Not a speed-seeking stock. It rewards box speed and careful development much more than any kind of push workflow."},{"header":"Shadow Detail","dek":"Strong if the negative gets enough exposure. Shadows stay tidy and well separated in bright conditions."},{"header":"Highlight Roll-off","dek":"Measured and polished. Highlights stay orderly, which helped make the film attractive for architectural and scenic work."}]'::jsonb,
  1,
  3,
  3,
  NULL,
  'Neutral silver rendering with strong detail separation',
  NULL,
  NULL,
  TRUE,
  'bw',
  ARRAY['landscapes', 'architecture', 'studio', 'bright_sun']::text[],
  TRUE,
  '/films/agfa-apx-25.jpg',
  1992,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- agfa-scala-200x
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Agfa Scala 200x',
  'agfa-scala-200x',
  (SELECT id FROM film_brands WHERE slug = 'agfa'),
  ARRAY['35mm', '120']::film_format[],
  'bw_reversal'::film_type,
  200,
  'One of the defining black-and-white reversal films of the late analog era. Scala 200x delivered projection-ready monochrome slides with a dramatic, editorial look that no ordinary negative could quite match.',
  'Agfa introduced Scala 200x as the flagship of its monochrome reversal system, complete with dedicated lab processing and projection culture around the film. Its discontinuation turned it into a reference point for every later black-and-white reversal revival.',
  '[{"header":"Tonal Range","dek":"Bold and transparent. It has the immediate, contrast-forward look that made monochrome slides feel so different from prints."},{"header":"Push/Pull","dek":"Designed for process control, not casual flexibility. Metering accuracy matters more than rating tricks."},{"header":"Shadow Detail","dek":"Relatively tight. Deep tones close quickly if exposure drifts, especially in contrasty daylight."},{"header":"Highlight Roll-off","dek":"Brilliant but unforgiving. Bright values glow beautifully when placed well, but there is little recovery margin."}]'::jsonb,
  2,
  5,
  1,
  NULL,
  'Black-and-white reversal transparency rendering',
  NULL,
  NULL,
  TRUE,
  'bw',
  ARRAY['architecture', 'documentary', 'bright_sun', 'experimental']::text[],
  TRUE,
  '/films/agfa-scala-200x.jpg',
  1996,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- ferrania-ortho
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Ferrania Orto',
  'ferrania-ortho',
  (SELECT id FROM film_brands WHERE slug = 'ferrania'),
  ARRAY['35mm']::film_format[],
  'bw_negative'::film_type,
  50,
  'A modern orthographic black-and-white film with crisp contrast, smooth grain, and a distinctive response to reds and skin. Orto 50 brings specialist spectral behavior into everyday still photography without feeling like a mere novelty.',
  'Film Ferrania released Orto 50 in 2023 as the second still film from its revived Italian factory. It broadened the company''s lineup beyond P30 and showed that Ferrania''s restart could support more than one monochrome character.',
  '[{"header":"Tonal Range","dek":"Graphic and selective. Reds go dark, blues and greens separate cleanly, and the image feels sculpted rather than neutral."},{"header":"Push/Pull","dek":"Built for box-speed control. It is a specialty 50-speed film, so careful exposure matters more than flexibility."},{"header":"Shadow Detail","dek":"Moderate but attractive. Dark values stay readable with enough light, though this is not a wide-latitude emulsion."},{"header":"Highlight Roll-off","dek":"Bright and tidy. Highlights stay crisp without the brittle feel of some technical films."}]'::jsonb,
  1,
  4,
  3,
  NULL,
  'Orthochromatic monochrome with darkened reds and crisp separation',
  NULL,
  NULL,
  TRUE,
  'bw',
  ARRAY['architecture', 'studio', 'bright_sun', 'experimental']::text[],
  FALSE,
  '/films/ferrania-ortho.jpg',
  2023,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- fujifilm-neopan-400
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Neopan 400',
  'fujifilm-neopan-400',
  (SELECT id FROM film_brands WHERE slug = 'fujifilm'),
  ARRAY['35mm', '120']::film_format[],
  'bw_negative'::film_type,
  400,
  'A discontinued Fuji black-and-white film known for strong sharpness, crisp contrast, and a cleaner look than many older 400-speed monochrome stocks. Neopan 400 combined speed with a polished tonal structure that made it versatile beyond simple reportage.',
  'Neopan 400 was one of Fujifilm''s most respected black-and-white stocks before the company withdrew from the category. Its disappearance left many photographers missing a high-speed monochrome film with a distinctly Fuji balance of clarity and restraint.',
  '[{"header":"Tonal Range","dek":"Clean and modern. It gives a crisp grayscale with more polish than many gritty 400-speed classics."},{"header":"Push/Pull","dek":"Adaptable enough. It handles a one-stop push competently, though its nicest look comes from confident box-speed exposure."},{"header":"Shadow Detail","dek":"Solid in practice. Dark values stay usable if the negative is not starved for light."},{"header":"Highlight Roll-off","dek":"Controlled and tidy. Highlights stay orderly instead of blooming, which suits the film''s refined feel."}]'::jsonb,
  2,
  3,
  4,
  NULL,
  'Neutral monochrome with polished Fuji tonality',
  NULL,
  NULL,
  TRUE,
  'bw',
  ARRAY['street', 'documentary', 'general_purpose', 'travel']::text[],
  TRUE,
  '/films/fujifilm-neopan-400.jpg',
  1980,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- fujifilm-neopan-1600
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Neopan 1600',
  'fujifilm-neopan-1600',
  (SELECT id FROM film_brands WHERE slug = 'fujifilm'),
  ARRAY['35mm']::film_format[],
  'bw_negative'::film_type,
  1600,
  'A cult high-speed monochrome stock that delivered atmospheric grain, real low-light reach, and a surprisingly controlled tonal scale for its speed. Neopan 1600 is remembered as one of Fuji''s most charismatic films.',
  'Fujifilm introduced Neopan 1600 as part of its professional black-and-white range for photographers who needed genuine speed without abandoning image quality. Its discontinuation turned it into a benchmark for late-night street and documentary work.',
  '[{"header":"Tonal Range","dek":"Moody and compressed in a useful way. It gives fast-film drama without collapsing completely into mush."},{"header":"Push/Pull","dek":"Built for low light. It can be pushed further, but its big appeal is already having real box-speed reach."},{"header":"Shadow Detail","dek":"Impressive for 1600-speed film. Extra light helps, though the stock still resolves dark scenes better than most rivals of its class."},{"header":"Highlight Roll-off","dek":"Reasonably controlled. Highlights stay more composed than the speed might suggest when exposure is sensible."}]'::jsonb,
  4,
  3,
  4,
  NULL,
  'Neutral monochrome tuned for low-light speed',
  NULL,
  NULL,
  TRUE,
  'bw',
  ARRAY['low_light', 'street', 'documentary', 'artificial_light']::text[],
  TRUE,
  '/films/fujifilm-neopan-1600.jpg',
  1989,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- kentmere-pan-200
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Kentmere Pan 200',
  'kentmere-pan-200',
  (SELECT id FROM film_brands WHERE slug = 'kentmere'),
  ARRAY['35mm', '120']::film_format[],
  'bw_negative'::film_type,
  200,
  'A newly added middle-speed Kentmere stock that sits between the brand''s 100 and 400 emulsions, giving photographers a practical blend of manageable grain and more flexible exposure than slow films. It is an everyday monochrome film built with Harman''s usual reliability.',
  'Harman Technology introduced Kentmere Pan 200 in 2025 as the first expansion of the Kentmere still-film line in years. The film broadened Kentmere from a two-speed budget option into a fuller monochrome family.',
  '[{"header":"Tonal Range","dek":"Balanced and useful. It gives a straightforward grayscale without the heaviness of faster budget films."},{"header":"Push/Pull","dek":"Moderately adaptable. It can move a little in either direction, but its strength is dependable mid-speed versatility."},{"header":"Shadow Detail","dek":"Good and easy to hold. There is enough latitude for casual metering and everyday subjects."},{"header":"Highlight Roll-off","dek":"Clean with a gentle shoulder. Highlights stay pleasant and printable without drama."}]'::jsonb,
  2,
  3,
  4,
  NULL,
  'Neutral monochrome with Harman-made everyday tonality',
  NULL,
  NULL,
  TRUE,
  'bw',
  ARRAY['general_purpose', 'street', 'travel', 'documentary']::text[],
  FALSE,
  '/films/kentmere-pan-200.jpg',
  2025,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- kodak-bw400cn
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Kodak BW400CN',
  'kodak-bw400cn',
  (SELECT id FROM film_brands WHERE slug = 'kodak'),
  ARRAY['35mm']::film_format[],
  'bw_negative'::film_type,
  400,
  'Kodak''s chromogenic black-and-white film delivered monochrome images through standard C-41 processing, making it easy for minilabs and casual shooters to work in black and white. The look is smoother and cleaner than traditional silver-rich 400-speed films.',
  'BW400CN gave Kodak a consumer-friendly black-and-white option for the one-hour lab era, standing apart from Ilford XP2 but serving a similar purpose. Its convenience and smooth scans kept it relevant long after serious darkroom users moved elsewhere.',
  '[{"header":"Tonal Range","dek":"Smooth and modern. It lacks the gritty silver look of traditional 400-speed monochrome and instead feels cleaner and more linear."},{"header":"Push/Pull","dek":"Flexible in practical use. The film handles casual exposure variation well, helped by chromogenic processing and forgiving scanning."},{"header":"Shadow Detail","dek":"Very good. It keeps dark tones more open than many traditional 400-speed black-and-white films."},{"header":"Highlight Roll-off","dek":"Soft and easy. Bright values fade out gently, which is one reason scans from BW400CN tend to feel polished."}]'::jsonb,
  2,
  2,
  5,
  NULL,
  'Chromogenic monochrome with smooth, scan-friendly tonality',
  NULL,
  NULL,
  TRUE,
  'c41',
  ARRAY['general_purpose', 'travel', 'portrait', 'documentary']::text[],
  TRUE,
  '/films/kodak-bw400cn.jpg',
  1998,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- kodak-plus-x-pan-125
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Kodak Plus-X Pan 125',
  'kodak-plus-x-pan-125',
  (SELECT id FROM film_brands WHERE slug = 'kodak'),
  ARRAY['35mm', '120', '4x5']::film_format[],
  'bw_negative'::film_type,
  125,
  'A classic Kodak medium-speed black-and-white film with fine grain, moderate contrast, and an easy tonal curve that made it a darkroom favorite for decades. Plus-X sat between highly technical slow films and the grittier drama of Tri-X.',
  'Plus-X was one of Kodak''s foundational black-and-white still films and remained in production, in one form or another, through much of the twentieth century. It became shorthand for clean, traditional monochrome before being overshadowed by faster and more specialized stocks.',
  '[{"header":"Tonal Range","dek":"Traditional and graceful. It gives a classic Kodak grayscale with smooth mids and restrained contrast."},{"header":"Push/Pull","dek":"Best when treated gently. It can move a little, but the appeal is its clean box-speed elegance."},{"header":"Shadow Detail","dek":"Good and trustworthy. It keeps darker values open without turning the image flat."},{"header":"Highlight Roll-off","dek":"Soft and beautifully printable. Highlights fade out with that old-school darkroom ease."}]'::jsonb,
  2,
  2,
  4,
  NULL,
  'Classic neutral Kodak monochrome',
  NULL,
  NULL,
  TRUE,
  'bw',
  ARRAY['portrait', 'landscapes', 'documentary', 'general_purpose']::text[],
  TRUE,
  '/films/kodak-plus-x-pan-125.jpg',
  1954,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- kodak-tri-x-professional-320
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Kodak Tri-X Professional 320',
  'kodak-tri-x-professional-320',
  (SELECT id FROM film_brands WHERE slug = 'kodak'),
  ARRAY['4x5', '8x10']::film_format[],
  'bw_negative'::film_type,
  320,
  'The sheet-film expression of Tri-X, offering the same classic Kodak bite and darkroom personality in large-format sizes. It combines Tri-X atmosphere with the smoother tonality and control that come from bigger negatives.',
  'Tri-X Professional in sheet film kept the famous Tri-X look available to studio, landscape, and fine-art photographers long after most attention shifted to 35mm reportage. It remains one of the few classic-grain Kodak films still offered in large-format practice.',
  '[{"header":"Tonal Range","dek":"Rich and classic. It has the familiar Tri-X punch, but large-format use lets the tonal scale feel more spacious and elegant."},{"header":"Push/Pull","dek":"More flexible than many sheet films. It can be adjusted for zone-system work or pushed modestly without losing its identity."},{"header":"Shadow Detail","dek":"Good and expressive. It gives shadows a strong presence while keeping enough texture for printmaking."},{"header":"Highlight Roll-off","dek":"Pleasingly rounded. Highlights hold a classic silver-gelatin feel that suits large-format printing."}]'::jsonb,
  3,
  4,
  4,
  NULL,
  'Classic Tri-X monochrome in sheet-film form',
  NULL,
  NULL,
  FALSE,
  'bw',
  ARRAY['portrait', 'studio', 'landscapes', 'documentary']::text[],
  FALSE,
  '/films/kodak-tri-x-professional-320.jpg',
  1954,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- kosmo-foto-agent-shadow-400
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Kosmo Foto Agent Shadow 400',
  'kosmo-foto-agent-shadow-400',
  (SELECT id FROM film_brands WHERE slug = 'kosmo-foto'),
  ARRAY['35mm']::film_format[],
  'bw_negative'::film_type,
  400,
  'A fast black-and-white film released by Kosmo Foto for photographers who want a classic grain structure with practical speed and easy availability. Agent Shadow 400 leans into flexible everyday monochrome rather than exotic specialization.',
  'Kosmo Foto announced Agent Shadow in 2021 and officially launched it in 2022, extending the brand beyond its original Mono 100 offering. The stock gave the company a more versatile companion film aimed at street, travel, and general low-light use.',
  '[{"header":"Tonal Range","dek":"Classic and approachable. It has the familiar 400-speed monochrome balance of useful mids, punchy blacks, and workable highlights."},{"header":"Push/Pull","dek":"Designed to be flexible. It handles moderate pushing well enough for street and low-light work."},{"header":"Shadow Detail","dek":"Good and practical. Dark areas keep enough information for documentary shooting without feeling flat."},{"header":"Highlight Roll-off","dek":"Pleasantly controlled. Highlights stay easy to print and scan, which suits the stock''s all-purpose intent."}]'::jsonb,
  3,
  3,
  4,
  NULL,
  'Classic panchromatic monochrome with flexible 400-speed rendering',
  NULL,
  NULL,
  TRUE,
  'bw',
  ARRAY['street', 'general_purpose', 'travel', 'documentary']::text[],
  FALSE,
  '/films/kosmo-foto-agent-shadow-400.jpg',
  2022,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- lucky-shd-100
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Lucky SHD 100',
  'lucky-shd-100',
  (SELECT id FROM film_brands WHERE slug = 'lucky'),
  ARRAY['35mm', '120']::film_format[],
  'bw_negative'::film_type,
  100,
  'A budget-friendly black-and-white film with a traditional look, moderate contrast, and enough speed for everyday daylight shooting. SHD 100 is about honest monochrome rather than boutique polish.',
  'Lucky''s SHD black-and-white films descend from the Chinese manufacturer''s long-running domestic emulsions, which earned a reputation for affordability and practical performance. Recent availability has introduced the films to a wider audience looking for budget-friendly monochrome with a classic, unfussy look.',
  '[{"header":"Tonal Range","dek":"Traditional and straightforward. It gives a familiar black-and-white scale without much stylization."},{"header":"Push/Pull","dek":"Best close to box speed. Slight overexposure smooths things out, while hard pushes make the film feel rougher."},{"header":"Shadow Detail","dek":"Good when the negative gets enough light. It is forgiving enough for a budget stock, but not endlessly so."},{"header":"Highlight Roll-off","dek":"Pleasantly classic. Highlights keep a soft analog shoulder instead of turning brittle."}]'::jsonb,
  2,
  3,
  3,
  NULL,
  'Classic monochrome with affordable, traditional Lucky tonality',
  NULL,
  NULL,
  TRUE,
  'bw',
  ARRAY['general_purpose', 'street', 'travel', 'bright_sun']::text[],
  FALSE,
  '/films/lucky-shd-100.jpg',
  2017,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- lucky-shd-400
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Lucky SHD 400',
  'lucky-shd-400',
  (SELECT id FROM film_brands WHERE slug = 'lucky'),
  ARRAY['35mm', '120']::film_format[],
  'bw_negative'::film_type,
  400,
  'The faster SHD option adds more grit and flexibility for street, documentary, and lower-light shooting while staying firmly in the affordable-film lane. It is practical, contrasty, and intentionally unpretentious.',
  'Lucky''s SHD black-and-white films descend from the Chinese manufacturer''s long-running domestic emulsions, which earned a reputation for affordability and practical performance. Recent availability has introduced the films to a wider audience looking for budget-friendly monochrome with a classic, unfussy look.',
  '[{"header":"Tonal Range","dek":"Punchy and straightforward. It gives a classic budget-400 look with enough bite for street and documentary use."},{"header":"Push/Pull","dek":"Willing to stretch. It handles moderate pushes in the gritty, honest way people often want from affordable monochrome."},{"header":"Shadow Detail","dek":"Reasonably good. It keeps usable low-end information when exposure is sensible, though deep underexposure gets rough fast."},{"header":"Highlight Roll-off","dek":"Firm but manageable. Highlights stay printable if the film is not overdeveloped."}]'::jsonb,
  4,
  4,
  4,
  NULL,
  'Classic high-speed monochrome with gritty Lucky character',
  NULL,
  NULL,
  TRUE,
  'bw',
  ARRAY['street', 'documentary', 'general_purpose', 'low_light']::text[],
  FALSE,
  '/films/lucky-shd-400.jpg',
  2025,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- orwo-un54
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'ORWO UN54',
  'orwo-un54',
  (SELECT id FROM film_brands WHERE slug = 'orwo'),
  ARRAY['35mm']::film_format[],
  'bw_negative'::film_type,
  100,
  'A motion-picture black-and-white stock repurposed for still photography, valued for its classic cine tonality and smooth midtones. UN54 feels less like a boutique still film and more like a slice of working cinema stock.',
  'UN54 comes from ORWO''s motion-picture heritage and has been repurposed into still-photography workflows through respooling and niche retail channels. Its renewed visibility helped connect the relaunched ORWO brand with its deeper production history.',
  '[{"header":"Tonal Range","dek":"Cinematic and classic. It gives a smooth grayscale with less bite than surveillance-derived films and more character than ultra-modern technical stocks."},{"header":"Push/Pull","dek":"Best around box speed. It can move a little, but the stock''s charm is really in its native cine-negative balance."},{"header":"Shadow Detail","dek":"Good and gentle. Dark areas hold together nicely when the negative is treated generously."},{"header":"Highlight Roll-off","dek":"Soft and filmic. Highlights taper in a way that feels more motion-picture than still-photo harshness."}]'::jsonb,
  2,
  2,
  4,
  NULL,
  'Cinema-derived monochrome with smooth midtones',
  NULL,
  NULL,
  FALSE,
  'bw',
  ARRAY['documentary', 'portrait', 'general_purpose', 'street']::text[],
  FALSE,
  '/films/orwo-un54.jpg',
  2022,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- rollei-atp-1-1
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Rollei ATP 1.1',
  'rollei-atp-1-1',
  (SELECT id FROM film_brands WHERE slug = 'rollei'),
  ARRAY['35mm', '120']::film_format[],
  'bw_negative'::film_type,
  32,
  'A specialist ultra-fine-grain black-and-white film made for maximum resolution and a technical, highly detailed look. ATP 1.1 is not casual material; it is for photographers who want control, sharpness, and a very precise monochrome result.',
  'Rollei ATP 1.1 emerged from the company''s technical-film side, drawing on surveillance and high-resolution emulsion traditions rather than classic pictorial rendering. It became a niche favorite among detail-focused photographers comfortable with exacting workflows.',
  '[{"header":"Tonal Range","dek":"Precise and technical. It is more about resolution and crisp separation than easy, romantic grayscale."},{"header":"Push/Pull","dek":"Very limited. The stock wants disciplined metering and matched development rather than flexible speed changes."},{"header":"Shadow Detail","dek":"Fragile if mistreated. Dark values need thoughtful exposure to avoid collapsing."},{"header":"Highlight Roll-off","dek":"Controlled but not generous. Highlights stay clean when handled properly, though the film is never especially forgiving."}]'::jsonb,
  1,
  4,
  2,
  NULL,
  'Technical monochrome with extremely high resolving power',
  NULL,
  NULL,
  TRUE,
  'bw',
  ARRAY['architecture', 'studio', 'landscapes', 'bright_sun']::text[],
  FALSE,
  '/films/rollei-atp-1-1.jpg',
  2004,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- rollei-ortho-25-plus
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Rollei Ortho 25 Plus',
  'rollei-ortho-25-plus',
  (SELECT id FROM film_brands WHERE slug = 'rollei'),
  ARRAY['35mm', '120', '4x5']::film_format[],
  'bw_negative'::film_type,
  25,
  'A very slow orthographic film that emphasizes sharpness, smooth grain, and dramatic red suppression for landscape and studio use. Ortho 25 Plus is a precision monochrome stock for controlled light and deliberate shooting.',
  'Rollei''s Ortho 25 Plus reflects the boutique-film era''s renewed interest in specialist spectral sensitivity and slower, tripod-friendly emulsions. It gives photographers an off-mainstream alternative to ordinary panchromatic daylight work.',
  '[{"header":"Tonal Range","dek":"Clean and sculpted. The orthographic response gives scenes a distinctive, deliberate separation."},{"header":"Push/Pull","dek":"Made for careful exposure. It is a specialty slow film, so rating changes are less useful than simply feeding it light."},{"header":"Shadow Detail","dek":"Good when treated generously. Shadows stay elegant in bright scenes, but this is not a speed film."},{"header":"Highlight Roll-off","dek":"Bright and well behaved. Highlights stay crisp without the harshness of microfilm-style emulsions."}]'::jsonb,
  1,
  4,
  3,
  NULL,
  'Orthochromatic monochrome with strong separation and ultra-fine grain',
  NULL,
  NULL,
  TRUE,
  'bw',
  ARRAY['architecture', 'landscapes', 'studio', 'bright_sun']::text[],
  FALSE,
  '/films/rollei-ortho-25-plus.jpg',
  2021,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- street-candy-atm-400
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Street Candy ATM 400',
  'street-candy-atm-400',
  (SELECT id FROM film_brands WHERE slug = 'street-candy'),
  ARRAY['35mm']::film_format[],
  'bw_negative'::film_type,
  400,
  'A surveillance-derived black-and-white film repackaged for still photographers who want gritty speed, sharpness, and hard-edged urban character. ATM 400 feels unapologetically utilitarian in the best way.',
  'Street Candy built its identity around repurposed industrial and monitoring films, and ATM 400 continues that approach at a faster speed than the original MTN 100. It carries the brand''s CCTV-inspired aesthetic directly into handheld, lower-light work.',
  '[{"header":"Tonal Range","dek":"Graphic and gritty. It leans toward stronger separation and a more industrial monochrome feel than classic portrait films."},{"header":"Push/Pull","dek":"Well suited to being driven. The stock accepts higher ratings with the roughness many users actually want from it."},{"header":"Shadow Detail","dek":"Modest but useful. It can hold dark detail, though its aesthetic is more about grit than softness."},{"header":"Highlight Roll-off","dek":"Firm and punchy. Highlights stay bright and emphatic rather than gentle or glowing."}]'::jsonb,
  3,
  5,
  3,
  NULL,
  'Surveillance-derived monochrome with graphic contrast',
  NULL,
  NULL,
  FALSE,
  'bw',
  ARRAY['street', 'documentary', 'low_light', 'experimental']::text[],
  FALSE,
  '/films/street-candy-atm-400.jpg',
  2023,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();
