-- Insert/update missing experimental stocks with metadata, scales, and effect-oriented shooting notes.

-- Scope: lomography-lomochrome-color-92, lomography-lomochrome-color-92-sun-kissed, lomography-lomochrome-turquoise, lomography-redscale-xr

-- Note schema: Effect Character, Effect Intensity, Scene Pairing, Exposure Flexibility, Highlight Behavior



-- lomography-lomochrome-color-92
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'LomoChrome Color ''92',
  'lomography-lomochrome-color-92',
  (SELECT id FROM film_brands WHERE slug = 'lomography'),
  ARRAY['35mm', '120']::film_format[],
  'color_negative'::film_type,
  400,
  'A creative color negative film designed to channel the softer, warmer consumer-film character of the early 1990s. Color ''92 is less about wild effects than about gentle nostalgia with visible personality.',
  'Lomography introduced Color ''92 as a modern color negative stock designed to echo the softer consumer-film palette of the early 1990s. It expanded the company''s in-house creative color line beyond effect films into a deliberately nostalgic everyday aesthetic.',
  '[{"header":"Effect Character","dek":"Subtle nostalgia rather than gimmickry. It softens the modern look and pushes the frame toward a warm early-1990s mood."},{"header":"Effect Intensity","dek":"Moderate. The effect is clear, but it does not overwhelm the scene the way stronger pre-exposed films do."},{"header":"Scene Pairing","dek":"Works especially well with daylight street scenes, travel, and portraits where a gentle throwback palette feels natural."},{"header":"Exposure Flexibility","dek":"Quite usable. It behaves like a normal negative film with a stylized palette, so slight overexposure is often rewarding."},{"header":"Highlight Behavior","dek":"Soft and creamy. Highlights help sell the nostalgic character instead of clipping harshly."}]'::jsonb,
  3,
  2,
  4,
  2,
  'Daylight-balanced with warm, nostalgic early-1990s color',
  'daylight',
  5500,
  TRUE,
  'c41',
  ARRAY['portrait', 'travel', 'general_purpose', 'experimental', 'golden_hour']::text[],
  FALSE,
  '/films/lomography-lomochrome-color-92.jpg',
  2023,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- lomography-lomochrome-color-92-sun-kissed
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'LomoChrome Color ''92 Sun-kissed',
  'lomography-lomochrome-color-92-sun-kissed',
  (SELECT id FROM film_brands WHERE slug = 'lomography'),
  ARRAY['35mm', '120']::film_format[],
  'color_negative'::film_type,
  400,
  'A warmer, more amber-leaning variation on Color ''92, built to intensify the nostalgic summer-memories side of the formula. Sun-kissed pushes the stock further toward glow, warmth, and late-day softness.',
  'Lomography followed Color ''92 with Sun-kissed as an expanded expression of the same nostalgic concept, shifting the palette toward warmer highlights and more overt golden-hour character. It turned a subtle throwback film into a more scene-shaping creative stock.',
  '[{"header":"Effect Character","dek":"Warm and nostalgic. It leans harder into amber light and memory-film warmth than the standard Color ''92 stock."},{"header":"Effect Intensity","dek":"Noticeable but still photographically usable. The effect shapes the frame without turning every scene into an abstract gimmick."},{"header":"Scene Pairing","dek":"Best with golden light, sunlit travel scenes, and portraits where warmth is part of the mood."},{"header":"Exposure Flexibility","dek":"Likes extra light. Overexposure strengthens the soft, amber quality that makes the film distinctive."},{"header":"Highlight Behavior","dek":"Glowy and warm. Highlights bloom into the nostalgic look instead of staying clinically neutral."}]'::jsonb,
  3,
  2,
  4,
  3,
  'Daylight-balanced with warm, sunlit nostalgic color',
  'daylight',
  5500,
  TRUE,
  'c41',
  ARRAY['portrait', 'travel', 'golden_hour', 'experimental']::text[],
  FALSE,
  '/films/lomography-lomochrome-color-92-sun-kissed.jpg',
  2024,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- lomography-lomochrome-turquoise
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'LomoChrome Turquoise XR 100-400',
  'lomography-lomochrome-turquoise',
  (SELECT id FROM film_brands WHERE slug = 'lomography'),
  ARRAY['35mm', '120']::film_format[],
  'color_negative'::film_type,
  200,
  'A deliberately effect-driven stock that remaps familiar colors into turquoise, cobalt, and surreal false-color combinations. It is one of Lomography''s clearest invitations to treat color negative film as an interpretive medium rather than a documentary one.',
  'LomoChrome Turquoise became a signature creative stock in Lomography''s experimental lineup by offering dramatic color transpositions without requiring lab trickery. Its XR labeling reflected the flexible rating options users could exploit to steer the effect.',
  '[{"header":"Effect Character","dek":"Strong and surreal. Color relationships shift dramatically, turning ordinary scenes into false-color compositions."},{"header":"Effect Intensity","dek":"High. This is a clear statement film rather than a subtle mood tweak."},{"header":"Scene Pairing","dek":"Best for bold landscapes, travel, signage, and subjects with strong color blocks that can survive remapping."},{"header":"Exposure Flexibility","dek":"Part of the fun. Different ratings noticeably change how aggressively the effect shows up."},{"header":"Highlight Behavior","dek":"Stylized but usable. Highlights often intensify the unreal palette instead of simply washing out."}]'::jsonb,
  3,
  3,
  3,
  5,
  'Daylight-balanced effect film with turquoise false-color shifts',
  'daylight',
  5500,
  TRUE,
  'c41',
  ARRAY['travel', 'landscapes', 'experimental', 'bright_sun']::text[],
  FALSE,
  '/films/lomography-lomochrome-turquoise.jpg',
  2021,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();

-- lomography-redscale-xr
INSERT INTO film_stocks (
  name,
  slug,
  brand_id,
  format,
  type,
  iso,
  description,
  history,
  shooting_notes,
  grain,
  contrast,
  latitude,
  saturation,
  color_balance,
  color_balance_type,
  color_balance_kelvin,
  dx_coding,
  development_process,
  best_for,
  discontinued,
  image_url,
  year_introduced,
  featured
)
VALUES (
  'Lomography Redscale XR 50-200',
  'lomography-redscale-xr',
  (SELECT id FROM film_brands WHERE slug = 'lomography'),
  ARRAY['35mm', '120']::film_format[],
  'color_negative'::film_type,
  100,
  'A redscale effect film that shifts the world toward oranges, reds, yellows, and sepia by exposing through the base side of the emulsion. Redscale XR makes every scene feel heated, nostalgic, or slightly apocalyptic depending on the light.',
  'Lomography turned redscale from a DIY trick into an accessible commercial stock, then expanded it with XR variable-speed packaging so photographers could tune the effect. It remains one of the simplest ways to get a dramatic altered-color look on standard C-41 processing.',
  '[{"header":"Effect Character","dek":"Warm, heavy, and unmistakable. The film transforms the frame into a redscale world of amber, rust, and burnt orange."},{"header":"Effect Intensity","dek":"High but tunable. The variable-speed approach lets photographers move between warm nostalgia and full heat-wave intensity."},{"header":"Scene Pairing","dek":"Best with direct sun, architecture, travel scenes, and subjects where the altered palette becomes part of the message."},{"header":"Exposure Flexibility","dek":"Central to the stock. Different ratings materially shift density and the strength of the redscale effect."},{"header":"Highlight Behavior","dek":"Glowing and amber. Highlights merge into the warm cast instead of staying clean and neutral."}]'::jsonb,
  3,
  4,
  3,
  5,
  'Daylight-balanced redscale effect with amber and orange dominance',
  'daylight',
  5500,
  TRUE,
  'c41',
  ARRAY['travel', 'experimental', 'bright_sun', 'golden_hour']::text[],
  FALSE,
  '/films/lomography-redscale-xr.jpg',
  2010,
  FALSE
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_id = EXCLUDED.brand_id,
  format = EXCLUDED.format,
  type = EXCLUDED.type,
  iso = EXCLUDED.iso,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  shooting_notes = EXCLUDED.shooting_notes,
  grain = EXCLUDED.grain,
  contrast = EXCLUDED.contrast,
  latitude = EXCLUDED.latitude,
  saturation = EXCLUDED.saturation,
  color_balance = EXCLUDED.color_balance,
  color_balance_type = EXCLUDED.color_balance_type,
  color_balance_kelvin = EXCLUDED.color_balance_kelvin,
  dx_coding = EXCLUDED.dx_coding,
  development_process = EXCLUDED.development_process,
  best_for = EXCLUDED.best_for,
  discontinued = EXCLUDED.discontinued,
  image_url = EXCLUDED.image_url,
  year_introduced = EXCLUDED.year_introduced,
  featured = EXCLUDED.featured,
  updated_at = now();
